/**
 * Shared product-shot prompt for ingredient thumbnails (used by
 * scripts/ingredient-images/vendor.ts and scripts/fix-ingredient-images.ts).
 * Pure — no env, no network.
 */

// Hard cases where the generic prompt produced the wrong subject on the first
// generation pass (verified visually): a more literal subject description
// beats a reseed. Keyed by the lowercase ingredient name / canonical key.
export const PROMPT_OVERRIDES: Record<string, string> = {
  'bell pepper': 'a whole fresh red bell pepper',
  cumin: 'ground cumin spice powder in a small ceramic bowl',
  dill: 'a bunch of fresh dill herb fronds',
  thyme: 'fresh thyme herb sprigs',
  paprika: 'red paprika spice powder in a small ceramic bowl',
  pepper: 'ground black pepper in a small ceramic bowl',
  tamari: 'a small glass bottle of dark tamari soy sauce',
  'tamari (paleo)': 'a small glass bottle of dark tamari soy sauce',
  'soy sauce (or tamari)': 'a small glass bottle of dark soy sauce',
  'fajita seasoning (paleo)': 'fajita spice seasoning mix in a small ceramic bowl',
  'ground lamb': 'raw ground minced lamb meat on butcher paper',
  'ground pork': 'raw ground minced pork meat on butcher paper',
  'ground tempeh': 'crumbled tempeh pieces in a small bowl',
  'lean turkey mince': 'raw ground minced turkey meat on butcher paper',
  'green lentils (cooked)': 'cooked green lentils in a small ceramic bowl',
  // R-21: the generic prompt rendered a lime / a tart. Literal subjects, with
  // the colour and shape spelled out so the model cannot drift to citrus or pastry.
  cucumber: 'a whole long dark green cucumber vegetable',
  cucumbers: 'two whole long dark green cucumber vegetables',
  radishes: 'a small bunch of fresh round red radish root vegetables with green leaves',
  radish: 'a few fresh round red radish root vegetables with green leaves',
};

/**
 * Extra subjects found while reviewing the vendored thumbnails (WP-24, 2026-10-07):
 * the terse prompt drifted (chicken breast → bread, olive oil → abstract bowl,
 * canned tuna → sushi…). Vendor-only, so the legacy fix script's URLs stay stable.
 */
export const VENDOR_PROMPT_OVERRIDES: Record<string, string> = {
  'boneless chicken thighs': 'raw boneless skinless chicken thighs on a white plate',
  'canned tuna': 'an open tin can of tuna chunks',
  'canned black beans': 'black beans in a small white bowl',
  'cayenne pepper': 'red cayenne pepper powder in a small ceramic bowl',
  'chia seeds': 'chia seeds in a small white bowl',
  'buckwheat groats': 'raw buckwheat groats in a small white bowl',
  'arborio rice': 'dry short-grain arborio rice in a small white bowl',
  'coconut oil': 'a small glass jar of white coconut oil',
  'cooked sushi rice': 'a white bowl of cooked sticky white rice',
  courgette: 'a whole fresh green zucchini',
  'olive oil': 'a glass bottle of golden olive oil',
  'cooked king prawns': 'cooked pink shrimp on a white plate',
  'balsamic vinegar': 'a glass bottle of dark balsamic vinegar',
  // Second review pass (full sheet, 215 images).
  besan: 'yellow chickpea gram flour in a small white bowl',
  'boiled potato': 'a few whole boiled potatoes on a white plate',
  'chestnut mushrooms': 'fresh brown chestnut mushrooms',
  'coconut yogurt': 'a white bowl of coconut yogurt',
  'corn tortillas': 'a stack of round corn tortillas',
  'dark chocolate': 'broken pieces of dark chocolate bar',
  'dijon mustard': 'a small glass jar of dijon mustard',
  'dried apricots': 'dried orange apricots in a small bowl',
  'egg yolk': 'a single raw egg yolk in a small white bowl',
  'firm tofu': 'a block of white firm tofu',
  'plain flour': 'white wheat flour in a small bowl',
  'frozen banana': 'frozen banana slices on a plate',
  'frozen strawberries': 'frozen strawberries in a small bowl',
  'ground ginger': 'ground ginger spice powder in a small ceramic bowl',
  halloumi: 'grilled halloumi cheese slices on a plate',
  honey: 'a glass jar of golden honey with a honey dipper',
  hummus: 'a bowl of creamy hummus',
  'kalamata olives': 'dark purple kalamata olives in a small bowl',
  'lemon zest': 'finely grated yellow lemon zest in a small bowl',
  mango: 'a whole ripe yellow mango',
  'maple syrup': 'a glass bottle of maple syrup',
  'medjool dates': 'sticky brown medjool dates in a small bowl',
  'mixed leaves': 'a bowl of mixed green salad leaves',
  'miso paste': 'a small bowl of brown miso paste',
  'pumpkin seeds': 'green pumpkin seeds in a small white bowl',
  'peanut butter': 'a glass jar of peanut butter',
  potato: 'three whole raw brown potatoes',
  rocket: 'fresh arugula rocket leaves',
  'rye bread': 'a loaf of dark rye bread',
  'sauerkraut leaves': 'a bowl of sauerkraut',
  'sirloin steak': 'a raw sirloin beef steak on a white plate',
  'snap peas': 'fresh green snap pea pods',
  'sour pickles': 'dill pickles in a glass jar',
  sriracha: 'a red bottle of sriracha hot chili sauce',
  'sushi-grade salmon': 'a raw salmon fillet on a white plate',
  tahini: 'a glass jar of tahini sesame paste',
  'vanilla protein powder': 'a white scoop of protein powder',
  'vegetable oil': 'a glass bottle of yellow vegetable oil',
  'whole-wheat couscous': 'dry couscous grains in a small bowl',
  'whole-wheat tortilla': 'a stack of round flour tortillas',
  'wholewheat tortillas': 'a stack of round flour tortillas',
  'wholemeal bread': 'a loaf of wholemeal bread',
  zacusca: 'a small glass jar of red roasted vegetable spread',
  onion:
    'a whole yellow onion with golden-brown papery skin next to a halved onion showing white rings',
  cashews: 'raw kidney-shaped cashew nuts in a small white bowl',
  'ground pork': 'raw minced pork meat in a white bowl',
  'lean beef mince': 'raw minced beef meat in a white bowl',
  'lean turkey mince': 'raw minced turkey meat in a white bowl',
  'chicken breast': 'a raw pale pink chicken breast fillet on a white plate',
  'ground coriander': 'light brown ground coriander powder in a small white bowl',
};

/**
 * Full-catalog review pass (WP-25, 2026-10): every thumbnail was checked on a contact sheet and the
 * ones a shopper could mistake for another food (or that were abstract, an animal, or a person) got
 * a literal subject with colour, shape and container spelled out. Wins over VENDOR_PROMPT_OVERRIDES.
 */
export const REVIEW_PROMPT_OVERRIDES: Record<string, string> = {
  'acerola raw': 'a small pile of round bright red acerola cherries with tiny stems',
  'adzuki beans dry': 'dry adzuki beans, small dark red beans, heap on a white plate',
  'almond paste': 'a block of pale yellow marzipan almond paste wrapped in paper',
  'almonds oil roasted': 'a heap of roasted almonds on a white plate',
  'amaranth cooked': 'a small white bowl of cooked amaranth porridge, pale beige tiny grains',
  'amaranth dry': 'a small white bowl of tiny round pale yellow amaranth seeds',
  'anchovy canned oil': 'an open small tin of anchovy fillets in oil, rolled brown fillets',
  'anchovy raw': 'three small raw silver anchovy fish lying on a white plate',
  'anise seed': 'a small white bowl of greenish-brown anise seeds',
  'antelope raw': 'raw dark red antelope meat steak on a white plate',
  'apples dehydrated': 'dried apple chips, thin pale apple slices with red peel edge',
  'arrowroot flour': 'a small white bowl of fine white arrowroot starch powder',
  'avocado oil': 'a glass bottle of pale green avocado oil next to half an avocado',
  allspice: 'whole allspice berries, small round brown peppercorns, on a white plate',
  'baking powder': 'a small white bowl of white baking powder with a measuring spoon',
  'baking soda': 'a small white bowl of white baking soda powder with a spoon',
  'banana chips': 'dried banana chips, flat round golden slices, heap on a white plate',
  'banana dried':
    'dehydrated banana slices, small flat round pale brown discs scattered on a white plate',
  'banana pepper raw': 'three pale yellow-green banana peppers with pointed tips, chili vegetables',
  'banana ripe raw': 'a bunch of ripe yellow bananas',
  'beef eye round raw':
    'a raw beef roast joint, deep red lean meat with a thin white fat edge, on a wooden cutting board',
  'beef round cooked': 'slices of cooked roast beef, brown crust and pink centre, on a white plate',
  'beef round raw':
    'a raw beef roast, red lean meat with fine white marbling, on a wooden cutting board',
  'beef tripe raw': 'raw honeycomb tripe, white honeycomb textured stomach meat',
  'bison ground cooked': 'browned cooked minced beef in a frying pan',
  'black beans canned': 'a bowl full of glossy black turtle beans',
  'black pepper': 'a small white bowl of coarsely ground black pepper',
  'blackcurrants raw': 'a small bunch of dark purple-black blackcurrant berries on the stem',
  'blood sausage': 'sliced black pudding blood sausage, round dark slices',
  'blue cheese': 'a wedge of gorgonzola blue cheese, creamy white with blue veins',
  'blueberries dried':
    'dried blueberries, small dark purple wrinkled berries in a small white bowl',
  'boneless chicken thigh': 'raw chicken thigh fillets, pale pink poultry meat',
  'brazil nuts': 'brazil nuts, dark brown elongated three-sided nuts in a wooden bowl',
  breadsticks: 'a bundle of grissini breadsticks lying on a white table',
  'buckwheat roasted dry': 'roasted brown buckwheat kasha groats in a small white bowl',
  'bulgur cooked': 'a small white bowl of cooked bulgur wheat, fluffy light brown grains',
  'burger sauce': 'a small white bowl of creamy pale orange burger sauce',
  'burger bun': 'two sesame seed hamburger buns, golden brown, one cut open, empty',
  'butternut squash raw': 'a whole butternut squash, pale tan peanut-shaped squash',
  'cabbage white raw': 'a whole round pale green white cabbage head',
  'candied fruit': 'assorted candied fruit pieces, glossy sugared orange and green and red cubes',
  'caraway seed': 'caraway seeds, dark brown crescent seeds, heap on a white plate',
  cardamom: 'green cardamom pods, small pale green oval pods, in a wooden spoon',
  'cashews oil roasted':
    'roasted cashew nuts, curved kidney-shaped golden-beige nuts in a small white bowl',
  'cassava raw': 'two whole brown bark-skinned cassava roots, one cut showing white flesh',
  celeriac: 'a celeriac root bulb, knobbly brown round root vegetable',
  'celery seed': 'celery seeds, tiny dark brown seeds, heap on a white plate',
  'chervil dried': 'a small white bowl of dried green chervil herb flakes',
  'chestnut cream': 'a small glass jar of sweet brown chestnut puree spread',
  'chestnuts roasted': 'roasted chestnuts with cracked brown shells',
  'chicken breast': 'two raw skinless chicken breasts on a cutting board',
  'chicken breast skin raw': 'a raw skin-on chicken breast fillet on a cutting board',
  'chicken canned': 'shredded cooked chicken meat in an open tin can',
  'chicken drumstick cooked': 'two roasted golden-brown chicken drumsticks on a white plate',
  'chicken drumstick raw': 'two raw chicken drumsticks with pale skin on a white plate',
  'chicken fat': 'a small bowl of white solid rendered chicken fat',
  'chicken feet boiled': 'boiled chicken feet, yellow chicken claws, on a white plate',
  'chicken giblets raw':
    'raw chicken liver and heart giblets, dark red-brown organ meat pieces, in a white bowl',
  'chicken gizzards raw': 'raw chicken gizzards, grey-pink muscular organ pieces, in a white bowl',
  'chicken ground raw': 'raw ground chicken meat, pale pink minced poultry, in a white bowl',
  'chicken hearts raw': 'raw chicken hearts on a white plate, small dark red organ meat',
  'chicken liver raw': 'raw chicken livers on a white plate, glossy dark maroon organ meat',
  'chicken meat raw': 'raw chicken drumsticks and wings on a butcher tray, uncooked poultry',
  'chicory witloof raw': 'two pale cream-white belgian endive chicory heads with yellow tips',
  'chili pepper green raw': 'three long thin green chili peppers with stems',
  'chorizo dry': 'sliced chorizo sausage, dark red round slices with white fat specks',
  'clams raw': 'fresh clams in their shells on crushed ice',
  'cocoa butter': 'chunks of pale yellow cocoa butter',
  'coffee ground': 'a heap of dark brown ground coffee on a white plate with a few coffee beans',
  cola: 'a glass of dark brown cola soda with ice and bubbles',
  colby: 'a wedge of orange colby cheese with a slice cut off',
  'condensed milk sweetened':
    'an open tin can of sweetened condensed milk with a spoon of thick pale cream milk',
  coppa: 'thin slices of cured coppa pork, pink with white fat marbling, on a white plate',
  'coriander leaf dried': 'a small white bowl of dried green coriander cilantro leaf flakes',
  'corn flakes': 'a bowl of cornflakes breakfast cereal',
  'corn syrup': 'a bottle of clear corn syrup and a spoon dripping syrup',
  cotija: 'a crumbled white block of cotija cheese, dry crumbly white cheese',
  'crab canned': 'an open tin can of crab meat, white and pink flaked crabmeat',
  'crab cooked': 'a whole cooked red crab on a white plate',
  'cream cheese': 'a tub of soft white cream cheese, smooth white spread, with a butter knife',
  'crispbread rye': 'a stack of rectangular rye crispbread crackers',
  croissant: 'a butter croissant pastry on a white plate',
  'cuttlefish raw':
    'raw squid and cuttlefish, white tubes and tentacles, on ice at a seafood counter',
  'daikon raw': 'a whole long white daikon radish',
  'dates deglet noor': 'dark brown wrinkled deglet noor dates in a small white bowl',
  'dates dried ciqual': 'dried dark brown pitted dates in a small white bowl',
  'dill seed': 'a small white bowl of tiny pale brown flat dill seeds',
  'duck fat': 'a small glass jar of white solid duck fat',
  'duck liver raw': 'a raw duck liver, cream-pink smooth lobe, on a white plate',
  'duck meat raw': 'raw duck leg pieces, dark red meat, on a white plate',
  'duck meat skin raw': 'a raw duck breast with white fatty skin side up, on a cutting board',
  'eel raw': 'a raw whole eel, long slim dark grey-brown snake-like fish, on ice',
  'egg powder': 'pale yellow powdered egg in a white bowl next to an eggshell',
  'elderberries raw': 'a small cluster of tiny dark purple-black elderberries on red stems',
  'elk raw': 'a raw dark red elk steak, lean venison meat, on a white plate',
  'fajita seasoning': 'a small white bowl of red-orange fajita spice seasoning powder',
  'fennel raw': 'a fennel bulb, white bulb vegetable with short green stalks',
  'fig raw': 'three whole ripe purple-brown figs, one cut in half showing red seedy flesh',
  'figs dried': 'dried figs, wrinkled brown whole figs, on a white plate',
  'fish fingers': 'four golden breaded fish fingers on a white plate',
  'fish roe raw': 'salmon roe ikura, tiny round orange-red pearls in a small white bowl',
  'flageolet beans dry': 'a small white bowl of pale green dried flageolet beans',
  'flaxseed oil': 'a small dark glass bottle of golden flaxseed oil with a few flax seeds',
  'flour potato': 'a small white bowl of fine white potato flour powder',
  'flour soy': 'a small white bowl of fine pale yellow soy flour',
  'flour rye dark': 'a small white bowl of dark grey-brown whole rye flour',
  'flour rye light': 'a small white bowl of pale grey-beige light rye flour',
  'flour sorghum': 'a small white bowl of fine pale cream sorghum flour',
  'flour spelt': 'a small white bowl of fine light beige spelt flour',
  'flour wheat whole': 'a small white bowl of coarse light brown wholemeal wheat flour',
  frankfurter: 'two cooked pink frankfurter sausages on a white plate',
  'frozen banana': 'frozen banana slices with frost, on a white plate',
  fructose: 'a small white bowl of white fructose sugar crystals',
  'garlic powder': 'a small white bowl of fine pale cream garlic powder',
  gelatin: 'gelatin leaves, clear sheets of leaf gelatine, on a white plate',
  'gherkins vinegar': 'pickled gherkins, small bumpy green cucumbers, on a white plate',
  ginger: 'fresh ginger root on a white surface',
  'ginger pickled': 'thin slices of pale pink pickled sushi ginger on a white plate',
  'glass noodles dry': 'a bundle of dry white vermicelli glass noodles',
  'goat raw': 'raw goat meat pieces, dark red, on a white plate',
  'goat yogurt': 'a small white bowl of plain white goat milk yogurt',
  'goji berries dried': 'a small white bowl of dried orange-red goji berries',
  'goose liver raw': 'raw goose liver, a large smooth pale pink-beige lobe',
  'goose meat raw': 'raw goose breast with skin, red meat, on a white plate',
  'gooseberries raw': 'a small bowl of light green striped gooseberries',
  'grain crouton': 'golden-brown crunchy bread croutons cubes in a small white bowl',
  'grapefruit juice': 'a glass of pink grapefruit juice with a halved pink grapefruit',
  'grapeseed oil': 'a glass bottle of pale green-yellow grapeseed oil',
  'greek yogurt 10': 'a small white bowl of thick white greek yogurt',
  'ground coriander': 'a small white bowl of fine light brown beige ground coriander powder',
  'ground lamb raw': 'raw minced lamb meat, pinkish-red, in a white bowl',
  'ground pork': 'raw minced pork meat, pale pink, in a white plastic tray',
  'guava raw': 'a whole yellow-green guava fruit and a halved guava showing pink flesh and seeds',
  'halibut raw': 'a raw white halibut fish fillet on a white plate',
  harissa: 'a small glass jar of red harissa chili paste',
  hazelnuts: 'shelled hazelnuts, round brown nuts, heap on a white plate',
  'head cheese':
    'sliced head cheese brawn terrine, pale gelatin with chunks of pink meat, on a white plate',
  'herring pickled': 'pickled herring fillets with onion rings on a white plate',
  'hoisin sauce': 'a small white bowl of thick dark brown hoisin sauce',
  'honeydew raw': 'a honeydew melon cut in half, pale green flesh, cream-yellow rind',
  'horseradish raw': 'a long thick white-beige horseradish root with rough skin',
  'jalapeno pickled': 'pickled jalapeno slices, green pepper rings, in a small white bowl',
  'jerusalem artichoke raw':
    'knobbly light brown jerusalem artichoke tubers, like small ginger roots',
  'kidney beans dry': 'dry red kidney beans, dark red glossy kidney-shaped beans, in a white bowl',
  kimchi: 'a glass jar of red napa cabbage kimchi',
  kiwi: 'two kiwi fruits, one cut in half showing bright green flesh and black seeds, fuzzy brown skin',
  lard: 'a small white bowl of white solid pork lard',
  'lardons raw': 'raw bacon lardons, small pink and white pork belly cubes, on a white plate',
  'lean beef mince': 'raw minced beef, dark red ground meat, in a white plastic tray',
  'lemon zest': 'finely grated pale yellow lemon zest next to a whole lemon',
  'lettuce red leaf raw':
    'a head of red leaf lettuce, frilly green leaves with dark red tips, on a white surface',
  'liver pate': 'smooth brown liver pate spread on a slice of toast',
  'liver sausage': 'a slice of pale pink-brown liverwurst sausage on a white plate',
  'lupin beans cooked': 'a small white bowl of yellow lupini beans',
  'lychee raw': 'fresh lychees, bumpy pink-red skin, one peeled showing white flesh',
  'macadamia nuts': 'round cream-white macadamia nuts in a small white bowl',
  'macadamia roasted': 'roasted golden macadamia nuts in a small white bowl',
  mace: 'dried orange-red mace spice strips, in a small white bowl',
  mango: 'a whole ripe mango, red and yellow skin, next to mango cubes',
  'maple sugar': 'a small white bowl of light brown granulated maple sugar',
  'marjoram dried': 'a small white bowl of dried green marjoram herb',
  marsala: 'a glass bottle of dark amber marsala wine with a small glass',
  marshmallows: 'a pile of white fluffy round marshmallows',
  'melba toast': 'thin crisp dry rectangular melba toast slices, golden',
  'milk chocolate': 'broken pieces of light brown milk chocolate bar',
  'milk goat': 'a glass of white goat milk next to a small bottle',
  'milk powder skimmed': 'white milk powder in a white bowl with a scoop',
  'milk protein powder': 'a white scoop of fine white milk protein powder in a tub',
  'milk skimmed': 'a tall glass of thin white skimmed milk',
  'millet puffed': 'puffed millet cereal, tiny light puffed grains, in a white bowl',
  'miso paste': 'thick light brown miso paste in a small white dish, viewed from above',
  mortadella: 'thin slices of mortadella, pale pink with white fat dots and pistachios',
  'mulberries raw': 'a small bowl of dark purple-black elongated mulberries',
  'mushroom shiitake dried': 'dried shiitake mushrooms, wrinkled dark brown caps, on a white plate',
  'mushroom shiitake raw':
    'fresh shiitake mushrooms, flat brown umbrella caps with cream gills and slim stems',
  'mushroom white boiled': 'sliced cooked button mushrooms in a white bowl',
  'mushrooms canned': 'sliced canned button mushrooms in an open tin can',
  'mustard seed': 'a small white bowl of tiny round yellow-brown mustard seeds',
  'mustard wholegrain': 'a small glass jar of wholegrain mustard with visible brown seeds',
  naan: 'a round puffy naan flatbread with golden-brown spots',
  natto: 'natto fermented soybeans, sticky brown beans with stringy threads, in a small bowl',
  nutmeg: 'whole nutmeg seeds, small oval brown nuts, with a grater',
  'nutritional yeast': 'a small white bowl of pale yellow nutritional yeast flakes',
  'oatmeal cooked': 'a white bowl of creamy cooked oatmeal porridge',
  'okra raw': 'fresh green okra pods, ridged tapered pods with small caps',
  'olives green': 'green olives with a stone, in a small white bowl',
  'onion flakes dried': 'a small white bowl of dried pale beige onion flakes',
  'onion powder': 'onion powder, fine pale beige spice powder, heap on a white plate',
  'oyster sauce': 'a small glass bottle of dark brown oyster sauce',
  'passion fruit raw':
    'a halved passion fruit showing yellow pulp and black seeds, beside a whole purple one',
  'pasta whole wheat cooked': 'cooked brown wholewheat spaghetti in a white bowl',
  'pastrami beef': 'thin slices of pastrami with black pepper crust on a wooden board',
  'peaches dried': 'dried peach halves, wrinkled orange chewy dried fruit, on a white plate',
  'peanut oil':
    'a glass bottle of golden peanut oil, clear yellow oil, with a few peanuts in shell beside it',
  'peanuts raw': 'raw shelled peanuts with red-brown skins, heap on a white plate',
  'pears dried': 'dried pear slices, chewy beige-brown pear rings, on a white plate',
  'peppermint fresh': 'a sprig of fresh green peppermint leaves',
  pepperoni: 'thin round slices of pepperoni sausage on a wooden board',
  'phyllo dough': 'a stack of thin phyllo pastry sheets, paper-thin pale dough',
  'pickle relish': 'sweet pickle relish, finely diced green cucumber pieces in a glass jar',
  'pine nuts': 'small cream-coloured pine nuts in a small white bowl',
  'pinto beans canned drained': 'speckled beige-brown pinto beans in a small white bowl',
  'pizza dough': 'a round ball of raw pale white pizza dough on a floured surface',
  'pizza sauce': 'a small white bowl of red pizza tomato sauce with a spoon',
  'plant milk generic': 'a glass of white plant-based milk with a carton',
  'plantain raw': 'two green plantains, large green unripe cooking bananas',
  'polenta cooked': 'creamy yellow cooked polenta in a white bowl',
  'pollock raw': 'a raw white pollock fish fillet on a white plate',
  'poppy seeds': 'blue-black poppy seeds, tiny dark grey seeds, heap on a white plate',
  'pork feet raw': 'raw pork trotters, pale pink pig feet, on a butcher tray',
  'pork liver raw': 'raw pork liver slices, dark brown-red, in a white tray',
  'pork rinds': 'crispy puffed golden pork rinds crackling on a white plate',
  'pork shoulder lean raw': 'a raw pork shoulder roast, pink meat with white fat, on a white plate',
  'potato chips': 'a bowl of crispy potato chips crisps',
  'potato red raw': 'three whole red-skinned potatoes',
  'poultry seasoning': 'a small white bowl of green-brown dried herb poultry seasoning mix',
  'puff pastry': 'a sheet of raw puff pastry dough on a floured board',
  'puffed rice': 'puffed rice cereal, small white airy puffed grains in a bowl',
  'pumpkin pie spice': 'a small white bowl of brown pumpkin pie spice powder',
  'pumpkin seeds in shell roasted':
    'roasted pumpkin seeds in their white shells, flat oval seeds, on a white plate',
  'quail egg raw': 'small speckled quail eggs, one cracked open showing yolk',
  'quark 0': 'a small white bowl of smooth white quark',
  'quark low fat': 'a small white bowl of white low-fat quark with a spoon',
  'rabbit cooked': 'roasted rabbit pieces, golden brown, on a white plate',
  'rabbit raw': 'raw rabbit meat, pale pink saddle and legs, on a white plate',
  raclette: 'slices of pale yellow raclette cheese, melted on one side',
  radish:
    'red globe radishes, round red-purple root vegetables with a thin white tail and green leafy tops, bunched',
  'radish black raw':
    'a whole black radish, round root with rough black skin, cut showing white flesh',
  'raisins dark': 'raisins, small dark brown-purple wrinkled dried grapes, in a white bowl',
  'ranch dressing': 'a small white bowl of creamy white ranch dressing with green herbs',
  'rapeseed oil': 'a glass bottle of yellow rapeseed canola oil next to yellow rapeseed flowers',
  'red lentil': 'dry red split lentils, small orange lentils, in a white bowl',
  'refried beans': 'a white bowl of brown refried beans with a spoon',
  'rhubarb raw': 'fresh rhubarb stalks, long pink-red celery-like stems',
  'rice glutinous dry': 'a small white bowl of short, opaque white glutinous sticky rice grains',
  'rice red dry': 'a small white bowl of dry reddish-brown red rice grains',
  'rutabaga raw': 'a whole rutabaga swede, round root, yellow with purple top',
  'rye grain': 'a small white bowl of whole brown-grey rye grains',
  saffron: 'a small white dish of thin red saffron threads',
  sake: 'a small white ceramic bottle of sake with a tiny cup of clear sake',
  'salami dry': 'thin slices of dry salami, dark red with white fat specks, on a wooden board',
  'salsa verde': 'a small white bowl of green salsa verde sauce with herbs',
  'salsify raw': 'long thin black salsify roots, dark brown-black skin, one peeled white',
  salt: 'a small white bowl of white coarse salt crystals',
  'salt pork': 'a block of salt pork, white fat with pink meat streaks, on a white plate',
  'savory dried': 'a small white bowl of dried green savory herb',
  seitan: 'sliced seitan wheat gluten, beige-brown chewy slices on a white plate',
  'semisweet chocolate chips': 'a small white bowl of dark brown chocolate chips',
  'sesame dressing':
    'creamy beige sesame salad dressing in a small white bowl with sesame seeds on top',
  'sheep yogurt': 'a small white bowl of white sheep milk yogurt',
  shortening: 'a small white tub of white vegetable shortening, solid white fat',
  'smoked paprika': 'a small white bowl of red-brown smoked paprika powder',
  'sorghum dry': 'a small white bowl of round tan-brown sorghum grains',
  'sorrel raw': 'a bunch of fresh green sorrel leaves, arrow-shaped',
  'sour cherries frozen': 'frozen dark red sour cherries with frost in a white bowl',
  'soy protein isolate': 'a small white bowl of fine white-beige soy protein powder',
  'soy protein powder': 'a white scoop of beige soy protein powder',
  'soybean oil': 'a glass bottle of clear pale yellow soybean oil',
  'spaghetti squash raw':
    'a whole pale yellow oval spaghetti squash, one cut half showing yellow strands',
  'spelt dry': 'a small white bowl of dry brown spelt grains',
  'spinach frozen boiled': 'cooked chopped spinach, dark green leaves, in a white bowl',
  'spirulina dried': 'a small white bowl of dark green spirulina powder',
  'split peas dry': 'a small white bowl of dry yellow-green split peas',
  'spring onion': 'a bunch of green spring onions scallions with white bulbs',
  'squid raw': 'a raw whole squid, pale white tube body with tentacles, on ice',
  'starfruit raw':
    'a whole yellow star fruit carambola with five ridges, and a cross-section star slice',
  stevia: 'a small white bowl of white stevia powder with a green stevia leaf',
  'sugar brown': 'a small white bowl of moist brown sugar',
  'sugar white': 'a small white bowl of white granulated sugar',
  'sun dried tomatoes oil': 'sun-dried tomato pieces in a glass jar of oil',
  'sunflower seeds': 'a small white bowl of grey-white striped sunflower seeds in shell',
  'sunflower seeds oil roasted':
    'roasted shelled sunflower seeds, small grey-beige kernels, heap on a white plate',
  'sunflower seeds roasted':
    'roasted salted sunflower seed kernels, small beige-grey seeds, in a white bowl',
  surimi: 'a few pink-and-white crab stick surimi sticks on a white plate',
  'sweet soy sauce': 'a small glass bottle of thick dark brown sweet soy sauce kecap manis',
  'swiss chard raw': 'a bunch of swiss chard with dark green leaves and thick red stems',
  'taro raw': 'two whole brown hairy taro roots, one cut showing white flesh with purple dots',
  'tartar sauce': 'a small white bowl of white tartar sauce with pickle bits',
  'teff cooked': 'a small white bowl of cooked tan teff porridge',
  'teff dry': 'a small white bowl of tiny dark brown teff grains',
  'telemea cow': 'a block of white telemea brined cheese, cut slices',
  'teriyaki sauce': 'a glass bottle of dark brown teriyaki sauce',
  'thousand island dressing': 'a small white bowl of pale orange-pink thousand island dressing',
  tilsit: 'a wedge of pale yellow tilsit cheese with small holes',
  'tofu dried frozen': 'a block of pale tan dried tofu koya tofu, spongy',
  'tomatillo raw': 'three whole tomatillos in papery husks, green tomato-like fruit',
  'tomato passata': 'a glass jar of smooth red tomato passata puree with a whole tomato beside',
  'tortellini cheese': 'cooked ring-shaped tortellini pasta stuffed, in a white bowl',
  'tortilla chips': 'golden triangular corn tortilla chips in a bowl',
  'tuna canned oil': 'an open tin can of tuna chunks in olive oil',
  'tuna white canned water': 'an open tin can of flaky pale white albacore tuna',
  'turkey bacon': 'crispy cooked slices of pale pink-brown turkey bacon strips on a plate',
  'turkey ground cooked': 'browned cooked ground turkey mince in a frying pan',
  'turkey salami': 'thin round slices of turkey salami on a wooden board',
  'turkey thigh cooked': 'a roasted turkey thigh, golden-brown skin, on a white plate',
  'turkey thigh raw': 'a raw turkey thigh with pale pink skin on a white plate',
  'tvp dry': 'a small white bowl of dry brown textured vegetable protein granules',
  'tvp rehydrated': 'a white bowl of rehydrated textured soy protein mince, brown crumbles',
  urda: 'a small white bowl of soft white urda ricotta-style cheese',
  'vanilla sugar':
    'white sugar with black vanilla bean seeds in a small white bowl next to a vanilla pod',
  'veal leg raw': 'raw veal leg roast, pale pink meat joint tied with string, on a cutting board',
  'veal liver raw': 'a raw calf liver slice, smooth glossy reddish-brown, on a white plate',
  'veal loin cooked': 'sliced roasted veal loin, pale pink centre, on a white plate',
  'veal stock': 'a white bowl of clear golden-brown veal stock broth',
  'venison cooked': 'two cooked venison steak medallions with a brown crust, on a plate',
  'vinaigrette light': 'a small glass bottle of light vinaigrette dressing, oil and vinegar',
  'vital wheat gluten': 'a small white bowl of pale beige vital wheat gluten flour',
  'wakame seaweed': 'rehydrated wakame seaweed salad, dark green glossy ribbons, in a small bowl',
  'walnuts black': 'black walnuts, cracked dark hard shells with walnut kernels, on a white plate',
  wasabi: 'a small mound of bright green wasabi paste on a white dish',
  'water chestnuts raw':
    'fresh water chestnuts, dark brown corms, one peeled showing crisp white flesh',
  'wheat bran': 'a small white bowl of brown flaky wheat bran',
  'wheat germ': 'a small white bowl of pale golden wheat germ flakes',
  'whey liquid': 'a glass of thin pale yellow-white whey liquid',
  'white beans canned drained': 'white cannellini beans in a small white bowl',
  'white chocolate': 'broken pieces of ivory white chocolate bar',
  'white pepper': 'a small white bowl of ground pale beige white pepper',
  'whiting raw': 'a raw whole whiting fish, silvery, on a white plate',
  'wild boar raw': 'raw dark red wild boar meat steak on a white plate',
  'yam raw': 'a whole long brown yam tuber, one cut showing white flesh',
  'yeast dry': 'a small white bowl of tiny dry active yeast granules next to a packet',
  'yeast fresh': "a small cube of beige fresh compressed baker's yeast",
  'yogurt fruit nonfat': 'a white bowl of pink strawberry fruit yogurt with a strawberry on top',
  'yogurt plain nonfat': 'a small white bowl of thick white plain yogurt with a spoon',
};

/** The literal subject to draw for an ingredient (override, else the name itself). */
export function productShotSubject(
  name: string,
  alternateKey?: string,
  overrides: Record<string, string> = PROMPT_OVERRIDES,
): string {
  const keys = [name, alternateKey].flatMap((k) => (k ? [k.toLowerCase().trim()] : []));
  for (const k of keys) if (overrides[k]) return overrides[k];
  return name;
}

/**
 * Deterministic product-shot prompt for an ingredient name. Deliberately terse:
 * Pollinations' anonymous Flux tier drifted to abstract discs / people / pill
 * shapes with the older long "single food ingredient … top-down … no text"
 * wording (apple → a white disc), while "<subject>, food photography, white
 * background" is reliably on-subject.
 */
export function productShotPrompt(name: string, alternateKey?: string): string {
  return `${productShotSubject(name, alternateKey, { ...PROMPT_OVERRIDES, ...VENDOR_PROMPT_OVERRIDES, ...REVIEW_PROMPT_OVERRIDES })}, food photography, centered on a plain white background, studio lighting`;
}

/**
 * The long prompt the API's generated fallback and scripts/fix-ingredient-images.ts
 * use. Kept byte-for-byte so those deterministic Pollinations URLs stay valid.
 */
export function legacyProductShotPrompt(name: string): string {
  return (
    `A clean product photo of ${productShotSubject(name)}, single food ingredient on a plain light background, ` +
    'top-down, soft natural light, no text, no hands, no packaging branding.'
  );
}
