import { mealPlanRepository, prisma } from '@chefer/database';
import { mealPlanService } from '../application/meal-plan/meal-plan.service.js';

// ─── Weekly auto-generation (PW-5) ────────────────────────────────────────────
// The premium pitch in one sentence: it cooked for me while I slept. Every
// Sunday from GENERATION_HOUR_UTC, pre-generates NEXT week's plan for premium
// users with a complete profile. Pinned favourites and rating signals flow in
// automatically (P1-1 lives in MealPlanService.generate), so Monday's plan is
// personalised, not generic.
//
// Idempotency comes from the data, not from worker state: a user who already
// has a plan for next week (auto-generated earlier today, or generated by
// hand) is skipped, so restarts and repeated ticks are safe.

const TICK_INTERVAL_MS = 60 * 60 * 1000; // hourly discovery tick
const SUNDAY_UTC = 0; // Date.getUTCDay(): 0 = Sunday
const GENERATION_HOUR_UTC = 8; // don't generate in the middle of the night
/** Pause between users — each generation is a full AI call. */
const PER_USER_DELAY_MS = 5_000;

/** Monday 00:00 (local server time, matching getMondayOfWeek) of NEXT week. */
function mondayOfNextWeek(now = new Date()): Date {
  const day = now.getDay();
  const diffToMonday = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + diffToMonday + 7);
  monday.setHours(0, 0, 0, 0);
  return monday;
}

export class WeeklyPlanWorker {
  private timer: NodeJS.Timeout | null = null;
  private running = false;

  start(): void {
    if (this.timer) return;
    console.log('[WeeklyPlanWorker] started (Sundays from %d:00 UTC)', GENERATION_HOUR_UTC);
    this.timer = setInterval(() => void this.tick(), TICK_INTERVAL_MS);
    void this.tick();
  }

  stop(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    console.log('[WeeklyPlanWorker] stopped');
  }

  /** Exposed for tests — runs one pass regardless of the timer. */
  async tick(now = new Date()): Promise<void> {
    if (this.running) return;
    if (now.getUTCDay() !== SUNDAY_UTC || now.getUTCHours() < GENERATION_HOUR_UTC) return;

    this.running = true;
    try {
      await this.generateForEligibleUsers(now);
    } catch (err) {
      console.error('[WeeklyPlanWorker] sweep failed:', err);
    } finally {
      this.running = false;
    }
  }

  private async generateForEligibleUsers(now: Date): Promise<void> {
    // Premium subscribers with a complete profile. Admins are implicitly
    // premium for ACCESS, but auto-generation is a subscriber perk — an admin
    // who wants it can flip their own tier.
    const users = await prisma.user.findMany({
      where: {
        planTier: 'PREMIUM',
        chefProfile: {
          age: { not: null },
          weightKg: { not: null },
          heightCm: { not: null },
          activityLevel: { not: null },
        },
      },
      select: { id: true },
    });
    if (users.length === 0) return;

    const nextMonday = mondayOfNextWeek(now);
    let generated = 0;
    for (const user of users) {
      try {
        const existing = await mealPlanRepository.findByWeekStart(user.id, nextMonday);
        if (existing) continue;

        await mealPlanService.generate(user.id, 1, true);
        generated += 1;
        console.log(`[WeeklyPlanWorker] generated next week's plan for user ${user.id}`);
        await new Promise((r) => setTimeout(r, PER_USER_DELAY_MS));
      } catch (err) {
        // One user's failure must not starve the rest of the sweep.
        console.error(`[WeeklyPlanWorker] generation failed for user ${user.id}:`, err);
      }
    }
    if (generated > 0) {
      console.log(`[WeeklyPlanWorker] sweep done — ${generated}/${users.length} plans generated`);
    }
  }
}

export const weeklyPlanWorker = new WeeklyPlanWorker();
