import { MealPlanOrigin, mealPlanRepository, prisma, type Prisma } from '@chefer/database';
import { coachService } from '../application/coach/coach.service.js';
import { mealPlanService } from '../application/meal-plan/meal-plan.service.js';
import { isAiCapacityFailure } from '../lib/ai/friendly-error.js';

// ─── Weekly auto-generation (PW-5) ────────────────────────────────────────────
// The premium pitch in one sentence: it cooked for me while I slept. Every
// Sunday from GENERATION_HOUR_UTC, pre-generates NEXT week's plan for premium
// users with a complete profile. Pinned favourites and rating signals flow in
// automatically (P1-1 lives in MealPlanService.generate), so Monday's plan is
// personalised, not generic. Free users who signed in recently get a curated
// week (no AI) the same way (audit P2-5) — the difference is that the premium
// week learns. WeeklyEmailWorker announces both on Monday morning.
//
// Idempotency comes from the data, not from worker state: a user who already
// has a plan for next week (auto-generated earlier today, or generated by
// hand) is skipped, so restarts and repeated ticks are safe.
//
// Audit F-PLAN-4-1/2/3:
// - A followed "My weeks" template repeats — the worker applies it instead of
//   generating over it.
// - An untouched carry-forward copy (created just by viewing next week, no
//   edits, no shopping ticks) is replaced with a fresh week; anything the
//   user touched is theirs.
// - Users can switch it off (ChefProfile.autoPlanWeekly).
// - Premium AI generation only for users with AI data consent (App Store
//   5.1.2(i)); free curated weeks involve no AI and are unaffected.

const TICK_INTERVAL_MS = 60 * 60 * 1000; // hourly discovery tick
const SUNDAY_UTC = 0; // Date.getUTCDay(): 0 = Sunday
const GENERATION_HOUR_UTC = 8; // don't generate in the middle of the night
/** Pause between users — each generation is a full AI call. */
const PER_USER_DELAY_MS = 5_000;

/** Monday 00:00 (local server time, matching getMondayOfWeek) of NEXT week. */
function mondayOfNextWeek(now = new Date()): Date {
  const day = now.getDay();
  const diffToMonday = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + diffToMonday + 7);
  monday.setHours(0, 0, 0, 0);
  return monday;
}

export class WeeklyPlanWorker {
  private timer: NodeJS.Timeout | null = null;
  private running = false;

  start(): void {
    if (this.timer) return;
    console.log('[WeeklyPlanWorker] started (Sundays from %d:00 UTC)', GENERATION_HOUR_UTC);
    this.timer = setInterval(() => void this.tick(), TICK_INTERVAL_MS);
    void this.tick();
  }

  stop(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    console.log('[WeeklyPlanWorker] stopped');
  }

  /** Exposed for tests — runs one pass regardless of the timer. */
  async tick(now = new Date()): Promise<void> {
    if (this.running) return;
    if (now.getUTCDay() !== SUNDAY_UTC || now.getUTCHours() < GENERATION_HOUR_UTC) return;

    this.running = true;
    try {
      // F1 Adaptive Chef: reviews run BEFORE plan generation so this week's
      // target adjustments shape next week's calorie budget (premium_plan.md
      // W1-A#3). Idempotent via @@unique(userId, weekStart) — a second tick
      // the same Sunday is a no-op. A review-sweep failure must never block
      // plan generation.
      try {
        const { reviewed } = await coachService.runReviewSweep(now);
        if (reviewed > 0) console.log(`[WeeklyPlanWorker] wrote ${reviewed} chef review(s)`);
      } catch (err) {
        console.error('[WeeklyPlanWorker] review sweep failed:', err);
      }

      await this.generateForEligibleUsers(now);
    } catch (err) {
      console.error('[WeeklyPlanWorker] sweep failed:', err);
    } finally {
      this.running = false;
    }
  }

  /** A carry-forward copy nobody has edited or shopped against. */
  private async isReplaceableCopy(plan: { id: string; origin: MealPlanOrigin }): Promise<boolean> {
    if (plan.origin !== MealPlanOrigin.CARRY_FORWARD) return false;
    return !(await mealPlanRepository.hasShoppingProgress(plan.id));
  }

  private async generateForEligibleUsers(now: Date): Promise<void> {
    // Premium subscribers with a complete profile. Admins are implicitly
    // premium for ACCESS, but auto-generation is a subscriber perk — an admin
    // who wants it can flip their own tier.
    const premiumEligible = {
      planTier: 'PREMIUM',
      chefProfile: {
        age: { not: null },
        weightKg: { not: null },
        heightCm: { not: null },
        activityLevel: { not: null },
        autoPlanWeekly: true,
      },
    } satisfies Prisma.UserWhereInput;
    // AI data consent (App Store 5.1.2(i)): premium generation sends the
    // profile to the AI provider, so only users who allowed it are included.
    // The rest are skipped (counted, logged) — no curated stand-in, so a
    // premium user never silently gets a non-personalised week; they are
    // asked the next time they tap Generate.
    const [premium, premiumNoConsent] = await Promise.all([
      prisma.user.findMany({
        where: { ...premiumEligible, aiDataConsentAt: { not: null } },
        select: { id: true },
      }),
      prisma.user.count({ where: { ...premiumEligible, aiDataConsentAt: null } }),
    ]);
    if (premiumNoConsent > 0) {
      console.log(
        `[WeeklyPlanWorker] skipped ${premiumNoConsent} premium user(s) without AI data consent`,
      );
    }
    // Free accounts get the curated week (audit P2-5, PM review §3 #4):
    // deterministic, zero AI cost, so Monday's "your week is ready" works on
    // every tier. Only accounts signed in within the session lifetime (a live
    // session) — abandoned signups don't collect a new week forever. No
    // ChefProfile row means the toggle was never touched (default on).
    const free = await prisma.user.findMany({
      where: {
        planTier: 'FREE',
        OR: [{ chefProfile: null }, { chefProfile: { autoPlanWeekly: true } }],
        sessions: { some: { expires: { gt: now } } },
      },
      select: { id: true },
    });
    const users = [
      ...premium.map((u) => ({ id: u.id, premium: true })),
      ...free.map((u) => ({ id: u.id, premium: false })),
    ];
    if (users.length === 0) return;

    const nextMonday = mondayOfNextWeek(now);
    let generated = 0;
    // Once the AI providers are out of capacity (free-tier daily caps), the
    // remaining premium users would only hit the same wall — seven calls a
    // plan. They are left for the next hourly tick (they still have no plan
    // for next week, so they are picked up again); free curated weeks go on.
    let aiExhausted = false;
    for (const user of users) {
      if (user.premium && aiExhausted) continue;
      try {
        const existing = await mealPlanRepository.findByWeekStart(user.id, nextMonday);
        if (existing && !(await this.isReplaceableCopy(existing))) continue;

        const followed = await mealPlanRepository.findFollowedTemplate(user.id);
        if (followed) {
          // The week they follow repeats (no AI call).
          await mealPlanService.applyTemplateToWeek(user.id, followed, nextMonday);
          console.log(`[WeeklyPlanWorker] applied followed week for user ${user.id}`);
          continue;
        }

        await mealPlanService.generate(user.id, 1, user.premium, {
          origin: MealPlanOrigin.WEEKLY_AUTO,
        });
        generated += 1;
        console.log(
          `[WeeklyPlanWorker] generated next week's ${user.premium ? 'AI' : 'curated'} plan for user ${user.id}`,
        );
        // Only the premium path is an AI call worth spacing out.
        if (user.premium) await new Promise((r) => setTimeout(r, PER_USER_DELAY_MS));
      } catch (err) {
        // One user's failure must not starve the rest of the sweep (a free
        // user's restrictions can exhaust the curated pool, for example).
        console.error(`[WeeklyPlanWorker] generation failed for user ${user.id}:`, err);
        if (user.premium && isAiCapacityFailure(err)) {
          aiExhausted = true;
          console.warn(
            '[WeeklyPlanWorker] AI over capacity — remaining premium plans wait for the next tick',
          );
        }
      }
    }
    if (generated > 0) {
      console.log(`[WeeklyPlanWorker] sweep done — ${generated}/${users.length} plans generated`);
    }
  }
}

export const weeklyPlanWorker = new WeeklyPlanWorker();
