// Motion tokens — docs/audit-2026-09/motion-system.md §2.2.
// Plain data, zero dependencies: both apps import these at runtime and both
// Tailwind configs can import them at build time.

/** Durations in ms. Exits use `exit(d)` ≈ 70% of the enter. */
export const duration = {
  instant: 100, // press, hover colour, focus-adjacent state
  fast: 150, // check tick, chip select, icon morph, tooltip, crossfade under reduced motion
  base: 220, // element enter, skeleton→content, expand/collapse, sheet EXIT, list insert/remove
  slow: 320, // sheet/drawer ENTER, step and route transitions
  deliberate: 600, // progress-to-value (rings, bars, count-ups), chart draw-in
  celebrate: 1000, // tier-3 success choreography, total (rare)
} as const;

/** Exit duration for an enter of `ms`: quick in, quicker out (≈ 70%). */
export const exit = (ms: number): number => Math.round(ms * 0.7);

/** Cubic-bézier control points. Shared by CSS and Reanimated's Easing.bezier. */
export const easing = {
  standard: [0.2, 0, 0, 1], // on-screen movement and state changes
  enter: [0.05, 0.7, 0.1, 1], // emphasized decelerate: things arriving
  exit: [0.3, 0, 0.8, 0.15], // emphasized accelerate: things leaving
  linear: [0, 0, 1, 1], // time-truthful progress only (timers)
} as const;

export type EasingName = keyof typeof easing;

export const cssEasing = (k: EasingName): string => `cubic-bezier(${easing[k].join(', ')})`;

/** Physical springs for Reanimated's withSpring (mass 1). Settle times are to 1%. */
export const spring = {
  snappy: { damping: 30, stiffness: 500, mass: 1 }, // ≈360 ms, 5.6% overshoot. Press release, thumbs, toggles
  gentle: { damping: 26, stiffness: 260, mass: 1 }, // ≈400 ms, 1.3%. Sheets, reorders, drag release
  bouncy: { damping: 18, stiffness: 420, mass: 1 }, // ≈510 ms, 21%. Success pop, heart, PR badge
} as const;

export type SpringName = keyof typeof spring;

/**
 * The same springs sampled into CSS linear() for web (Chrome 113+, Safari
 * 17.2+, Firefox 112+). Generated by integrating each spring at 1 ms steps
 * (semi-implicit Euler, 17 samples, last pinned to 1) — motion.test.ts holds
 * the generator and fails if a spring changes without regenerating these.
 */
export const cssSpring = {
  snappy: {
    ms: 360,
    fn: 'linear(0, 0.109, 0.321, 0.559, 0.752, 0.9, 0.989, 1.038, 1.055, 1.054, 1.043, 1.03, 1.018, 1.009, 1.002, 0.999, 1)',
  },
  gentle: {
    ms: 400,
    fn: 'linear(0, 0.068, 0.215, 0.384, 0.545, 0.687, 0.795, 0.875, 0.931, 0.969, 0.992, 1.005, 1.011, 1.013, 1.012, 1.01, 1)',
  },
  bouncy: {
    ms: 510,
    fn: 'linear(0, 0.179, 0.54, 0.888, 1.118, 1.209, 1.194, 1.124, 1.047, 0.988, 0.959, 0.956, 0.968, 0.985, 0.999, 1.007, 1)',
  },
} as const;

/** Stagger for list reveals. Cap it: never more than 6 staggered items, and never more than 200 ms total delay. */
export const stagger = { step: 30, maxItems: 6 } as const;

/** Haptic vocabulary (mobile). Web maps only `tick` and `warning` to navigator.vibrate on Android. */
export const haptic = {
  selection: 'selection', // chip, segmented control, stepper ±, day pill
  tick: 'impactLight', // check-off, set ✓, heart
  lift: 'impactMedium', // drag start (reorder)
  success: 'notificationSuccess', // tier-2/3 success: log saved, workout finished, PR
  warning: 'notificationWarning', // rest/cook timer reached zero
  error: 'notificationError', // optimistic rollback
} as const;

export type HapticName = keyof typeof haptic;

/** Press-feedback scale targets (MO-01): controls shrink to 0.97, whole cards to 0.98. */
export const pressScale = { control: 0.97, card: 0.98 } as const;

/** Colour for "over target" progress (MO-06): amber-600. */
export const overTargetColor = '#d97706';
