// ─── Word-filter list (PRD §9.4, implementation-plan §3.2) ─────────────────────
//
// DATA ONLY. Matching lives in `text-filter.ts`.
//
// Attribution: curated with reference to the "List of Dirty, Naughty, Obscene,
// and Otherwise Bad Words" (LDNOOBW) by Shutterstock,
// https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words,
// licensed CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/). This is a
// reduced, edited adaptation: English and Romanian slurs, sexual terms and
// severe profanity, with inflections added and ambiguous words removed.
//
// HOW IT IS MATCHED. Whole words / whole phrases on normalised tokens, never
// substrings (so "Scunthorpe", "assessment", "cocktail", "Sussex", "shiitake",
// "Dickens", "cockles", "Penistone" are all fine). Text is lowercased, diacritics
// stripped, leet-speak mapped, repeated letters collapsed and non-letters turned
// into spaces first, so write every term here in plain lowercase; diacritics are
// harmless but unnecessary. A letter stretched three or more times still matches
// ("fuuuck", "shiiit"), and a run of single letters ("f u c k") is joined. A
// letter doubled on purpose ("fuuck") is NOT treated as a stretch: doubled
// letters are normal in words ("pulla" is a Finnish bun, "annal" is English).
//
// CURATION RULE: a word is on this list only if it is unambiguous in a recipe,
// a food name or a person's name. The filter rejects a recipe's save and a
// profile name, so a false positive costs a real user something. Words
// deliberately LEFT OFF, because they are common in food or names:
//   - "dick", "cock", "fanny", "willy", "bush", "butt", "prick", "tit", "rape"
//     (real given names and surnames; "spotted dick", "cock-a-leekie",
//     "prick the potatoes with a fork", "broccoli rape", "pork butt"). The
//     compounds (dickhead, cocksucker) are on the list.
//   - "faggots": a traditional British meatball dish, written in the plural. The
//     singular slur "faggot", "fag" and derivatives ARE on the list; a recipe
//     literally titled with the singular word is rejected (accepted trade-off).
//   - "ass", "badass", "kickass", "piss", "crap", "damn", "sex", "sexy",
//     "creampie", "bukkake" ("kick-ass chili", "Sex on the Beach",
//     "bukkake udon" are real recipe names), "orgasmic", "cum" ("rice cum dal"),
//     "negro" (Spanish/Portuguese "black": arroz negro), "kraut", "redskin",
//     "jap" ("Jap Chae"), "coon", "gay", "hooker", "testicles".
//   - Romanian: "pulpă" / "pulpe" (drumsticks) are different tokens from "pula"
//     and are never matched; "mici", "ciorbă", "sarmale", "cozonac", "mușchi",
//     "ficat", "papanași", "mămăligă", "cârnați" are all fine.
//
// Reports, blocks and the threshold auto-hide (PRD §9.1-9.3) are the backstop
// for everything a word list cannot know.

export const BLOCKED_TERMS: readonly string[] = [
  // ─── English: racial, ethnic and religious slurs ───────────────────────────
  'nigger',
  'niggers',
  'nigga',
  'niggas',
  'niggaz',
  'nigguh',
  'chink',
  'chinks',
  'ching chong',
  'gook',
  'gooks',
  'spic',
  'spics',
  'wetback',
  'wetbacks',
  'beaner',
  'beaners',
  'kike',
  'kikes',
  'paki',
  'pakis',
  'wop',
  'wops',
  'dago',
  'dagos',
  'towelhead',
  'towelheads',
  'raghead',
  'ragheads',
  'sandnigger',
  'camel jockey',
  'nazi',
  'nazis',
  'neonazi',
  'sieg heil',
  'heil hitler',
  'white power',

  // ─── English: homophobic, transphobic and ableist slurs ────────────────────
  'faggot',
  'faggy',
  'fag',
  'fags',
  'tranny',
  'trannies',
  'shemale',
  'retard',
  'retards',
  'retarded',
  'spastic',
  'spaz',
  'mongoloid',

  // ─── English: severe profanity and abuse ───────────────────────────────────
  'fuck',
  'fucks',
  'fucked',
  'fucker',
  'fuckers',
  'fucking',
  'fuckin',
  'fuckface',
  'fuckhead',
  'fuckwit',
  'fuckwits',
  'motherfucker',
  'motherfuckers',
  'motherfucking',
  'mofo',
  'clusterfuck',
  'shit',
  'shits',
  'shitty',
  'shitting',
  'shithead',
  'shitface',
  'shitbag',
  'bullshit',
  'horseshit',
  'dipshit',
  'cunt',
  'cunts',
  'cuntface',
  'bitch',
  'bitches',
  'bitchy',
  'bastard',
  'bastards',
  'asshole',
  'assholes',
  'arsehole',
  'arseholes',
  'asshat',
  'assface',
  'dumbass',
  'dickhead',
  'dickheads',
  'twat',
  'twats',
  'wanker',
  'wankers',
  'wank',
  'wanking',
  'tosser',
  'bellend',
  'bollocks',
  'douchebag',
  'cuck',
  'cucks',
  'kys',
  'kill yourself',

  // ─── English: sexual terms ─────────────────────────────────────────────────
  'pussy',
  'pussies',
  'cocksucker',
  'cocksuckers',
  'cocksucking',
  'cockhead',
  'blowjob',
  'blowjobs',
  'handjob',
  'handjobs',
  'rimjob',
  'footjob',
  'dildo',
  'dildos',
  'jizz',
  'cumshot',
  'cumslut',
  'cunnilingus',
  'fellatio',
  'anal',
  'anus',
  'gangbang',
  'threesome',
  'porn',
  'porno',
  'pornstar',
  'hentai',
  'milf',
  'whore',
  'whores',
  'slut',
  'sluts',
  'slutty',
  'skank',
  'skanks',
  'masturbate',
  'masturbating',
  'masturbation',
  'jerkoff',
  'rapist',
  'rapists',
  'molester',
  'pedophile',
  'pedophiles',
  'paedophile',
  'paedophiles',
  'pedo',
  'incest',

  // ─── Romanian: severe profanity, sexual terms, slurs ───────────────────────
  'pizda',
  'pizde',
  'pizdii',
  'pizdit',
  'pizdet',
  'pula',
  'pulii',
  'pulica',
  'muie',
  'muist',
  'muisti',
  'muistule',
  'fut',
  'fute',
  'futu',
  'futui',
  'futut',
  'fututi',
  'futai',
  'cacat',
  'cacati',
  'coaie',
  'coaiele',
  'curva',
  'curvar',
  'curvari',
  'curvele',
  'poponar',
  'poponari',
  'pederast',
  'retardat',
  'retardata',
  'prostituata',
];
