// ─── Curated exercise library ────────────────────────────────────────────────
// THE source of truth for the shared exercise pool. The API upserts it into the
// `exercises` table at boot (ensureExerciseLibrary — prod never runs the seed).
// Structural fields drive the engine (increments, volume, templates); content
// fields (cues/mistakes/blurb/media) come from docs/gym/exercise-library-research.md.
// Slugs are PERMANENT ids: sessions reference them. Never rename — add aliases.

import type { ExerciseMeta } from './engine';
import { EXERCISE_CONTENT, type ExerciseContent } from './exercise-content';
import { ExerciseTrackingType, type Muscle } from './vocab';

export interface ExerciseCatalogEntry extends ExerciseMeta {
  aliases: string[];
  /** 3–4 imperative cues, ≤ 12 words each ("Drive your elbows down to your hips"). */
  cues: string[];
  /** 2 common mistakes, ≤ 12 words each. */
  mistakes: string[];
  blurb: string | null;
  /** free-exercise-db id (public domain photos), or null. */
  freeExerciseDbId: string | null;
  videoId: string | null;
  videoStartSec: number | null;
  videoChannel: string | null;
}

type Struct = Omit<
  ExerciseCatalogEntry,
  | 'cues'
  | 'mistakes'
  | 'blurb'
  | 'freeExerciseDbId'
  | 'videoId'
  | 'videoStartSec'
  | 'videoChannel'
  | 'aliases'
> & { aliases?: string[] };

const C = 'COMPOUND' as const;
const I = 'ISOLATION' as const;

function ex(
  id: string,
  name: string,
  category: typeof C | typeof I,
  movementPattern: string,
  equipment: ExerciseCatalogEntry['equipment'],
  primaryMuscles: Muscle[],
  secondaryMuscles: Muscle[],
  [repMin, repMax]: [number, number],
  restSec: number,
  incrementKg: number,
  opts: Partial<Struct> = {},
): Struct {
  return {
    id,
    name,
    category,
    movementPattern,
    equipment,
    loadType: 'WEIGHTED',
    primaryMuscles,
    secondaryMuscles,
    repMin,
    repMax,
    restSec,
    incrementKg,
    perHand: false,
    isLowerBody: false,
    isTimed: false,
    swapGroup: null,
    ...opts,
  };
}

const L = { isLowerBody: true } as const;
const PH = { perHand: true } as const;
/** Reps-only progression (loadModel NONE): no load, so no belt / plates. */
const BW = { loadType: 'BODYWEIGHT' } as const;

/**
 * T-42.1 (06 §6, Δ2.2): a cardio catalogue entry, beside ex(). No weight/reps
 * progression exists for these (progression.service.ts recompute skips
 * non-strength tracking types), so repMin/repMax/incrementKg are unused
 * placeholders kept only so ExerciseMeta stays one shape — the client never
 * renders them for a cardio trackingType. Empty muscle lists are deliberate:
 * cardio contributes no fractional set to volumeByGroup (V1–V11 stay
 * strength-only), matching "PR, e1RM and volume code skip cardio" (T-42.2).
 */
function cardio(
  id: string,
  name: string,
  equipment: ExerciseCatalogEntry['equipment'],
  trackingType:
    | typeof ExerciseTrackingType.DURATION
    | typeof ExerciseTrackingType.DURATION_DISTANCE,
  opts: Partial<Struct> = {},
): Struct {
  return {
    id,
    name,
    category: C,
    movementPattern: 'cardio',
    equipment,
    // WEIGHTED (not BODYWEIGHT): the loadType↔equipment invariant
    // (catalog.test.ts "tag bodyweight moves consistently") reserves
    // `loadType: 'BODYWEIGHT'` for `equipment: 'BODYWEIGHT'` rows. No load is
    // tracked for cardio either way — the field is unused once trackingType
    // isn't a strength type.
    loadType: 'WEIGHTED',
    primaryMuscles: [],
    secondaryMuscles: [],
    repMin: 1,
    repMax: 1,
    restSec: 0,
    incrementKg: 0,
    perHand: false,
    isLowerBody: false,
    // Every W2 slice type (DURATION, DURATION_DISTANCE) is time-based
    // (isTimedFor, `@chefer/utils` gym/tracking.ts) — a level-0/1 client that
    // never sees this row anyway (Δ2.1) would still read a seconds label if
    // it somehow did.
    isTimed: true,
    swapGroup: null,
    trackingType,
    ...opts,
  };
}

/** Structural definitions — content is merged in below from EXERCISE_CONTENT. */
const STRUCTURE: Struct[] = [
  // Chest
  ex(
    'barbell-bench-press',
    'Barbell Bench Press',
    C,
    'horizontal-push',
    'BARBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [6, 10],
    180,
    2.5,
    { swapGroup: 'horizontal-press', aliases: ['Bench Press', 'Flat Bench'] },
  ),
  ex(
    'dumbbell-bench-press',
    'Dumbbell Bench Press',
    C,
    'horizontal-push',
    'DUMBBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'horizontal-press', aliases: ['DB Bench Press'] },
  ),
  ex(
    // T-05.10 (library staples, UX-05 A5, AC27-29): the barbell incline press
    // was a gap — only the dumbbell version existed. Sorted alphabetically
    // before "Incline Dumbbell Press" within the shared 'incline-press' swap
    // group, so it leads the "Similar" list when swapping out of either.
    'incline-barbell-bench-press',
    'Incline Barbell Bench Press',
    C,
    'incline-push',
    'BARBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [6, 10],
    180,
    2.5,
    { swapGroup: 'incline-press', aliases: ['Incline Bench Press', 'Incline Bench'] },
  ),
  ex(
    'incline-dumbbell-press',
    'Incline Dumbbell Press',
    C,
    'incline-push',
    'DUMBBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'incline-press', aliases: ['Incline DB Press'] },
  ),
  ex(
    'machine-chest-press',
    'Machine Chest Press',
    C,
    'horizontal-push',
    'MACHINE',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-press' },
  ),
  ex(
    'incline-machine-chest-press',
    'Incline Machine Chest Press',
    C,
    'incline-push',
    'MACHINE',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    5,
    {
      swapGroup: 'incline-press',
      aliases: ['Incline Chest Press Machine', 'Incline Machine Press'],
    },
  ),
  ex(
    'smith-machine-bench-press',
    'Smith Machine Bench Press',
    C,
    'horizontal-push',
    'SMITH',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2.5,
    { swapGroup: 'horizontal-press', aliases: ['Smith Bench Press', 'Smith Bench'] },
  ),
  ex(
    'smith-machine-incline-press',
    'Smith Machine Incline Press',
    C,
    'incline-push',
    'SMITH',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2.5,
    { swapGroup: 'incline-press', aliases: ['Smith Incline Press', 'Smith Incline Bench'] },
  ),
  ex(
    'decline-barbell-bench-press',
    'Decline Barbell Bench Press',
    C,
    'horizontal-push',
    'BARBELL',
    ['chest'],
    ['triceps', 'front-delts'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'horizontal-press', aliases: ['Decline Bench Press', 'Decline Bench'] },
  ),
  ex(
    'dumbbell-floor-press',
    'Dumbbell Floor Press',
    C,
    'horizontal-push',
    'DUMBBELL',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'horizontal-press', aliases: ['DB Floor Press', 'Floor Press'] },
  ),
  ex(
    'standing-cable-chest-press',
    'Standing Cable Chest Press',
    C,
    'horizontal-push',
    'CABLE',
    ['chest'],
    ['front-delts', 'triceps'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'horizontal-press', aliases: ['Cable Chest Press', 'Standing Cable Press'] },
  ),
  ex(
    // "Pec Deck" and "Cable Crossover" were aliases here until 2026-10; both
    // now have their own slugs (pec-deck, cable-crossover).
    'cable-fly',
    'Cable Fly',
    I,
    'chest-fly',
    'CABLE',
    ['chest'],
    ['front-delts'],
    [12, 15],
    90,
    2.5,
    { swapGroup: 'chest-fly' },
  ),
  ex(
    'pec-deck',
    'Pec Deck',
    I,
    'chest-fly',
    'MACHINE',
    ['chest'],
    ['front-delts'],
    [12, 15],
    90,
    5,
    { swapGroup: 'chest-fly', aliases: ['Machine Fly', 'Pec Deck Fly', 'Butterfly Machine'] },
  ),
  ex(
    'cable-crossover',
    'Cable Crossover',
    I,
    'chest-fly',
    'CABLE',
    ['chest'],
    ['front-delts'],
    [12, 15],
    90,
    2.5,
    { swapGroup: 'chest-fly', aliases: ['High-to-Low Cable Fly', 'High Cable Fly'] },
  ),
  ex(
    'low-to-high-cable-fly',
    'Low-to-High Cable Fly',
    I,
    'chest-fly',
    'CABLE',
    ['chest'],
    ['front-delts'],
    [12, 15],
    90,
    2.5,
    { swapGroup: 'chest-fly', aliases: ['Low Cable Crossover', 'Low Cable Fly'] },
  ),
  ex(
    'push-up',
    'Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 20],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'horizontal-press', aliases: ['Press-Up'] },
  ),
  ex(
    'chest-dip',
    'Dip',
    C,
    'dip',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [6, 12],
    120,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'dip', aliases: ['Chest Dip', 'Parallel Bar Dip'] },
  ),
  // Back
  ex(
    'pull-up',
    'Pull-Up',
    C,
    'vertical-pull',
    'BODYWEIGHT',
    ['lats'],
    ['biceps', 'upper-back'],
    [5, 10],
    150,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'vertical-pull' },
  ),
  ex(
    'chin-up',
    'Chin-Up',
    C,
    'vertical-pull',
    'BODYWEIGHT',
    ['lats'],
    ['biceps', 'upper-back'],
    [5, 10],
    150,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'vertical-pull' },
  ),
  ex(
    'assisted-pull-up',
    'Assisted Pull-Up',
    C,
    'vertical-pull',
    'ASSISTED',
    ['lats'],
    ['biceps', 'upper-back'],
    [6, 10],
    120,
    5,
    { loadType: 'ASSISTED', swapGroup: 'vertical-pull', aliases: ['Assisted Pull-Up Machine'] },
  ),
  ex(
    'lat-pulldown',
    'Lat Pulldown',
    C,
    'vertical-pull',
    'CABLE',
    ['lats'],
    ['biceps', 'upper-back'],
    [8, 12],
    120,
    5,
    { swapGroup: 'vertical-pull', aliases: ['Pulldown'] },
  ),
  ex(
    'close-grip-lat-pulldown',
    'Close-Grip Lat Pulldown',
    C,
    'vertical-pull',
    'CABLE',
    ['lats'],
    ['biceps', 'upper-back'],
    [8, 12],
    120,
    5,
    { swapGroup: 'vertical-pull', aliases: ['V-Bar Pulldown', 'Neutral-Grip Pulldown'] },
  ),
  ex(
    'underhand-lat-pulldown',
    'Reverse-Grip Lat Pulldown',
    C,
    'vertical-pull',
    'CABLE',
    ['lats'],
    ['biceps', 'upper-back'],
    [8, 12],
    120,
    5,
    { swapGroup: 'vertical-pull', aliases: ['Underhand Pulldown', 'Supinated Pulldown'] },
  ),
  ex(
    'single-arm-lat-pulldown',
    'Single-Arm Lat Pulldown',
    C,
    'vertical-pull',
    'CABLE',
    ['lats'],
    ['biceps', 'upper-back'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'vertical-pull', aliases: ['One-Arm Pulldown'] },
  ),
  ex(
    'barbell-row',
    'Barbell Row',
    C,
    'horizontal-pull',
    'BARBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts', 'lower-back'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'horizontal-row', aliases: ['Bent-Over Row'] },
  ),
  ex(
    'pendlay-row',
    'Pendlay Row',
    C,
    'horizontal-pull',
    'BARBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts', 'lower-back'],
    [5, 8],
    150,
    2.5,
    { swapGroup: 'horizontal-row', aliases: ['Dead-Stop Barbell Row'] },
  ),
  ex(
    // Its own slug since 2026-10; "T-Bar Row" used to be an alias of
    // chest-supported-row, which is a different machine.
    't-bar-row',
    'T-Bar Row',
    C,
    'horizontal-pull',
    'BARBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts', 'lower-back'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'horizontal-row', aliases: ['T Bar Row', 'Landmine Row'] },
  ),
  ex(
    'chest-supported-row',
    'Chest-Supported Row',
    C,
    'horizontal-pull',
    'MACHINE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-row', aliases: ['Seal Row'] },
  ),
  ex(
    'machine-row',
    'Seated Machine Row',
    C,
    'horizontal-pull',
    'MACHINE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-row', aliases: ['Machine Row', 'Iso-Lateral Row'] },
  ),
  ex(
    'seated-cable-row',
    'Seated Cable Row',
    C,
    'horizontal-pull',
    'CABLE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-row', aliases: ['Cable Row'] },
  ),
  ex(
    'single-arm-cable-row',
    'Single-Arm Cable Row',
    C,
    'horizontal-pull',
    'CABLE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'horizontal-row', aliases: ['One-Arm Cable Row', 'Single-Arm Seated Cable Row'] },
  ),
  ex(
    'single-arm-dumbbell-row',
    'Single-Arm Dumbbell Row',
    C,
    'horizontal-pull',
    'DUMBBELL',
    ['lats', 'upper-back'],
    ['biceps', 'rear-delts'],
    [8, 12],
    90,
    2,
    { ...PH, swapGroup: 'horizontal-row', aliases: ['One-Arm DB Row'] },
  ),
  ex(
    'face-pull',
    'Face Pull',
    I,
    'rear-delt',
    'CABLE',
    ['rear-delts'],
    ['upper-back', 'traps'],
    [12, 20],
    90,
    2.5,
    { swapGroup: 'rear-delt' },
  ),
  ex(
    'band-pull-apart',
    'Band Pull-Apart',
    I,
    'rear-delt',
    'BAND',
    ['rear-delts'],
    ['upper-back', 'traps'],
    [15, 25],
    60,
    2.5,
    { swapGroup: 'rear-delt', aliases: ['Resistance Band Pull-Apart', 'Pull-Apart'] },
  ),
  ex(
    'straight-arm-pulldown',
    'Straight-Arm Pulldown',
    I,
    'lat-isolation',
    'CABLE',
    ['lats'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'lat-isolation' },
  ),
  ex(
    'dumbbell-pullover',
    'Dumbbell Pullover',
    I,
    'lat-isolation',
    'DUMBBELL',
    ['lats'],
    ['chest', 'triceps'],
    [10, 15],
    90,
    2,
    { swapGroup: 'lat-isolation', aliases: ['DB Pullover', 'Pullover'] },
  ),
  // Shoulders
  ex(
    'overhead-press',
    'Overhead Press',
    C,
    'vertical-push',
    'BARBELL',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'vertical-press', aliases: ['OHP', 'Military Press'] },
  ),
  ex(
    'smith-machine-shoulder-press',
    'Smith Machine Shoulder Press',
    C,
    'vertical-push',
    'SMITH',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [8, 12],
    120,
    2.5,
    { swapGroup: 'vertical-press', aliases: ['Smith Shoulder Press', 'Smith Overhead Press'] },
  ),
  ex(
    'landmine-press',
    'Landmine Press',
    C,
    'vertical-push',
    'BARBELL',
    ['front-delts'],
    ['chest', 'triceps'],
    [8, 12],
    120,
    2.5,
    {
      swapGroup: 'vertical-press',
      aliases: ['Landmine Shoulder Press', 'Single-Arm Landmine Press'],
    },
  ),
  ex(
    'seated-dumbbell-shoulder-press',
    'Seated Dumbbell Shoulder Press',
    C,
    'vertical-push',
    'DUMBBELL',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'vertical-press', aliases: ['DB Shoulder Press'] },
  ),
  ex(
    'standing-dumbbell-shoulder-press',
    'Standing Dumbbell Shoulder Press',
    C,
    'vertical-push',
    'DUMBBELL',
    ['front-delts'],
    ['side-delts', 'triceps', 'abs'],
    [8, 12],
    120,
    2,
    {
      ...PH,
      swapGroup: 'vertical-press',
      aliases: ['Standing DB Press', 'Standing Dumbbell Press'],
    },
  ),
  ex(
    'arnold-press',
    'Arnold Press',
    C,
    'vertical-push',
    'DUMBBELL',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'vertical-press', aliases: ['Arnold Dumbbell Press'] },
  ),
  ex(
    'machine-shoulder-press',
    'Machine Shoulder Press',
    C,
    'vertical-push',
    'MACHINE',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [8, 12],
    120,
    5,
    { swapGroup: 'vertical-press', aliases: ['Shoulder Press Machine', 'Machine Overhead Press'] },
  ),
  ex(
    // One bell, one arm at a time: the logged weight is the bell (perHand is
    // reserved for DUMBBELL rows — catalog.test.ts).
    'kettlebell-press',
    'Single-Arm Kettlebell Press',
    C,
    'vertical-push',
    'KETTLEBELL',
    ['front-delts'],
    ['triceps', 'side-delts', 'abs'],
    [6, 10],
    120,
    4,
    { swapGroup: 'vertical-press', aliases: ['Kettlebell Press', 'KB Overhead Press'] },
  ),
  ex(
    'dumbbell-lateral-raise',
    'Dumbbell Lateral Raise',
    I,
    'lateral-raise',
    'DUMBBELL',
    ['side-delts'],
    [],
    [12, 20],
    90,
    2,
    { ...PH, swapGroup: 'lateral-raise', aliases: ['Lateral Raise', 'Side Raise'] },
  ),
  ex(
    'cable-lateral-raise',
    'Cable Lateral Raise',
    I,
    'lateral-raise',
    'CABLE',
    ['side-delts'],
    [],
    [12, 20],
    90,
    2.5,
    { swapGroup: 'lateral-raise' },
  ),
  ex(
    'machine-lateral-raise',
    'Machine Lateral Raise',
    I,
    'lateral-raise',
    'MACHINE',
    ['side-delts'],
    [],
    [12, 20],
    90,
    5,
    { swapGroup: 'lateral-raise', aliases: ['Lateral Raise Machine'] },
  ),
  ex(
    'band-lateral-raise',
    'Band Lateral Raise',
    I,
    'lateral-raise',
    'BAND',
    ['side-delts'],
    [],
    [15, 25],
    60,
    2.5,
    { swapGroup: 'lateral-raise', aliases: ['Resistance Band Lateral Raise'] },
  ),
  ex(
    'upright-row',
    'Upright Row',
    C,
    'upright-row',
    'BARBELL',
    ['side-delts', 'traps'],
    ['front-delts', 'biceps'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'lateral-raise', aliases: ['Barbell Upright Row'] },
  ),
  ex(
    'dumbbell-front-raise',
    'Dumbbell Front Raise',
    I,
    'front-raise',
    'DUMBBELL',
    ['front-delts'],
    ['side-delts'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'front-raise', aliases: ['Front Raise', 'DB Front Raise'] },
  ),
  ex(
    'reverse-pec-deck',
    'Reverse Pec Deck',
    I,
    'rear-delt',
    'MACHINE',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    90,
    5,
    { swapGroup: 'rear-delt', aliases: ['Rear-Delt Fly'] },
  ),
  ex(
    'cable-rear-delt-fly',
    'Cable Rear-Delt Fly',
    I,
    'rear-delt',
    'CABLE',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    90,
    2.5,
    { swapGroup: 'rear-delt', aliases: ['Cable Reverse Fly', 'Reverse Cable Crossover'] },
  ),
  ex(
    // Rotator-cuff work is filed under rear-delts (decision L-D4: no new
    // muscle value); swap group 'rotator-cuff' keeps it apart from fly work.
    'dumbbell-external-rotation',
    'Side-Lying Dumbbell External Rotation',
    I,
    'shoulder-external-rotation',
    'DUMBBELL',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    60,
    2,
    {
      ...PH,
      swapGroup: 'rotator-cuff',
      aliases: ['Dumbbell External Rotation', 'Side-Lying External Rotation'],
    },
  ),
  ex(
    'band-external-rotation',
    'Band External Rotation',
    I,
    'shoulder-external-rotation',
    'BAND',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    60,
    2.5,
    {
      swapGroup: 'rotator-cuff',
      aliases: ['Banded External Rotation', 'Resistance Band External Rotation'],
    },
  ),
  // Arms
  ex(
    'barbell-curl',
    'Barbell Curl',
    I,
    'elbow-flexion',
    'BARBELL',
    ['biceps'],
    ['forearms'],
    [8, 12],
    90,
    2.5,
    { swapGroup: 'biceps-curl' },
  ),
  ex(
    'ez-bar-curl',
    'EZ-Bar Curl',
    I,
    'elbow-flexion',
    'EZ_BAR',
    ['biceps'],
    ['forearms'],
    [8, 12],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['EZ Curl', 'EZ Bar Curl'] },
  ),
  ex(
    'dumbbell-curl',
    'Dumbbell Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['DB Curl'] },
  ),
  ex(
    'incline-dumbbell-curl',
    'Incline Dumbbell Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    [],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['Incline Curl'] },
  ),
  ex(
    'hammer-curl',
    'Hammer Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl' },
  ),
  ex(
    'zottman-curl',
    'Zottman Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    ['forearms'],
    [8, 12],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl' },
  ),
  ex(
    'concentration-curl',
    'Concentration Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    [],
    [10, 15],
    60,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['Seated Concentration Curl'] },
  ),
  ex(
    'preacher-curl',
    'Preacher Curl',
    I,
    'elbow-flexion',
    'EZ_BAR',
    ['biceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['EZ-Bar Preacher Curl', 'Cable Preacher Curl'] },
  ),
  ex(
    'dumbbell-preacher-curl',
    'Dumbbell Preacher Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    [],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['Single-Arm Preacher Curl', 'DB Preacher Curl'] },
  ),
  ex(
    'spider-curl',
    'Spider Curl',
    I,
    'elbow-flexion',
    'EZ_BAR',
    ['biceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['Prone Incline Curl'] },
  ),
  ex(
    'machine-biceps-curl',
    'Machine Biceps Curl',
    I,
    'elbow-flexion',
    'MACHINE',
    ['biceps'],
    [],
    [10, 15],
    90,
    5,
    { swapGroup: 'biceps-curl', aliases: ['Biceps Curl Machine', 'Machine Preacher Curl'] },
  ),
  ex(
    'cable-biceps-curl',
    'Cable Biceps Curl',
    I,
    'elbow-flexion',
    'CABLE',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['Cable Curl', 'Standing Cable Curl'] },
  ),
  ex(
    'cable-rope-hammer-curl',
    'Cable Rope Hammer Curl',
    I,
    'elbow-flexion',
    'CABLE',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['Rope Hammer Curl', 'Cable Hammer Curl'] },
  ),
  ex(
    'triceps-pushdown',
    'Triceps Pushdown',
    I,
    'elbow-extension',
    'CABLE',
    ['triceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Pressdown', 'Straight-Bar Pushdown'] },
  ),
  ex(
    // Owns the "Rope Pushdown" alias since 2026-10 (it used to point at the
    // straight-bar triceps-pushdown).
    'rope-triceps-pushdown',
    'Rope Triceps Pushdown',
    I,
    'elbow-extension',
    'CABLE',
    ['triceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Rope Pushdown', 'Rope Pressdown'] },
  ),
  ex(
    'overhead-cable-triceps-extension',
    'Overhead Cable Triceps Extension',
    I,
    'elbow-extension-overhead',
    'CABLE',
    ['triceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Overhead Triceps Extension'] },
  ),
  ex(
    'skull-crusher',
    'Skull Crusher',
    I,
    'elbow-extension',
    'EZ_BAR',
    ['triceps'],
    [],
    [8, 12],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Lying Triceps Extension'] },
  ),
  ex(
    'close-grip-bench-press',
    'Close-Grip Bench Press',
    C,
    'horizontal-push',
    'BARBELL',
    ['triceps'],
    ['chest', 'front-delts'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'triceps-compound', aliases: ['CGBP'] },
  ),
  ex(
    'triceps-dip',
    'Triceps Dip',
    C,
    'dip',
    'BODYWEIGHT',
    ['triceps'],
    ['chest', 'front-delts'],
    [6, 12],
    120,
    2.5,
    {
      loadType: 'BODYWEIGHT_PLUS',
      swapGroup: 'dip',
      aliases: ['Parallel Bar Triceps Dip', 'Upright Dip'],
    },
  ),
  ex(
    'assisted-dip',
    'Assisted Dip',
    C,
    'dip',
    'ASSISTED',
    ['triceps', 'chest'],
    ['front-delts'],
    [6, 12],
    120,
    5,
    {
      loadType: 'ASSISTED',
      swapGroup: 'dip',
      aliases: ['Assisted Dip Machine', 'Machine-Assisted Dip'],
    },
  ),
  ex(
    'seated-dip-machine',
    'Seated Dip Machine',
    C,
    'dip',
    'MACHINE',
    ['triceps'],
    ['chest', 'front-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'dip', aliases: ['Dip Machine', 'Seated Dip'] },
  ),
  // Forearms
  ex(
    'reverse-curl',
    'Reverse-Grip Barbell Curl',
    I,
    'elbow-flexion',
    'BARBELL',
    ['forearms'],
    ['biceps'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'forearm', aliases: ['Reverse Curl', 'Reverse Barbell Curl'] },
  ),
  ex(
    'barbell-wrist-curl',
    'Barbell Wrist Curl',
    I,
    'wrist-flexion',
    'BARBELL',
    ['forearms'],
    [],
    [12, 20],
    60,
    2.5,
    { swapGroup: 'forearm', aliases: ['Wrist Curl', 'Seated Wrist Curl'] },
  ),
  // Legs
  ex(
    'back-squat',
    'Back Squat',
    C,
    'squat',
    'BARBELL',
    ['quads'],
    ['glutes', 'adductors', 'lower-back'],
    [5, 8],
    180,
    2.5,
    { ...L, swapGroup: 'squat', aliases: ['Squat', 'Barbell Squat'] },
  ),
  ex(
    'front-squat',
    'Front Squat',
    C,
    'squat',
    'BARBELL',
    ['quads'],
    ['glutes', 'upper-back'],
    [5, 8],
    180,
    2.5,
    { ...L, swapGroup: 'squat' },
  ),
  ex(
    'smith-machine-squat',
    'Smith Machine Squat',
    C,
    'squat',
    'SMITH',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    150,
    2.5,
    { ...L, swapGroup: 'squat', aliases: ['Smith Squat'] },
  ),
  ex('hack-squat', 'Hack Squat', C, 'squat', 'MACHINE', ['quads'], ['glutes'], [8, 12], 150, 5, {
    ...L,
    swapGroup: 'squat',
  }),
  ex(
    'pendulum-squat',
    'Pendulum Squat',
    C,
    'squat',
    'MACHINE',
    ['quads'],
    ['glutes'],
    [8, 12],
    150,
    5,
    { ...L, swapGroup: 'squat', aliases: ['Pendulum Squat Machine'] },
  ),
  ex(
    'belt-squat',
    'Belt Squat',
    C,
    'squat',
    'MACHINE',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    150,
    5,
    { ...L, swapGroup: 'squat', aliases: ['Belt Squat Machine'] },
  ),
  ex(
    'goblet-squat',
    'Goblet Squat',
    C,
    'squat',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    2,
    { ...L, swapGroup: 'squat' },
  ),
  ex(
    'dumbbell-sumo-squat',
    'Dumbbell Sumo Squat',
    C,
    'squat',
    'DUMBBELL',
    ['quads', 'adductors'],
    ['glutes'],
    [10, 15],
    90,
    2,
    { ...L, swapGroup: 'squat', aliases: ['Dumbbell Plie Squat', 'Plie Squat'] },
  ),
  ex(
    'kettlebell-goblet-squat',
    'Kettlebell Goblet Squat',
    C,
    'squat',
    'KETTLEBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    4,
    { ...L, swapGroup: 'squat', aliases: ['KB Goblet Squat'] },
  ),
  ex(
    'leg-press',
    'Leg Press',
    C,
    'squat',
    'MACHINE',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 15],
    150,
    5,
    { ...L, swapGroup: 'squat' },
  ),
  ex(
    'romanian-deadlift',
    'Romanian Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [6, 10],
    150,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['RDL'] },
  ),
  ex(
    'good-morning',
    'Good Morning',
    C,
    'hinge',
    'BARBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 12],
    120,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Barbell Good Morning'] },
  ),
  ex(
    'deadlift',
    'Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['glutes', 'hamstrings'],
    ['quads', 'lower-back', 'upper-back', 'traps', 'forearms'],
    [4, 6],
    180,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Conventional Deadlift'] },
  ),
  ex(
    'sumo-deadlift',
    'Sumo Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['glutes', 'hamstrings'],
    ['quads', 'adductors', 'lower-back', 'traps', 'forearms'],
    [4, 6],
    180,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Sumo DL'] },
  ),
  ex(
    // Trap bar = BARBELL (decision L-D4: no new equipment value).
    'trap-bar-deadlift',
    'Trap Bar Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['glutes', 'quads'],
    ['hamstrings', 'lower-back', 'traps', 'forearms'],
    [4, 8],
    180,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Hex Bar Deadlift'] },
  ),
  ex(
    'rack-pull',
    'Rack Pull',
    C,
    'hinge',
    'BARBELL',
    ['glutes', 'hamstrings'],
    ['lower-back', 'upper-back', 'traps', 'forearms'],
    [4, 8],
    180,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Block Pull', 'Rack Deadlift'] },
  ),
  ex(
    'kettlebell-swing',
    'Kettlebell Swing',
    C,
    'hinge',
    'KETTLEBELL',
    ['glutes', 'hamstrings'],
    ['lower-back', 'forearms', 'abs'],
    [10, 20],
    90,
    4,
    { ...L, swapGroup: 'hinge', aliases: ['KB Swing', 'Russian Kettlebell Swing'] },
  ),
  ex(
    'kettlebell-deadlift',
    'Kettlebell Deadlift',
    C,
    'hinge',
    'KETTLEBELL',
    ['glutes', 'hamstrings'],
    ['quads', 'lower-back', 'forearms'],
    [10, 15],
    90,
    4,
    { ...L, swapGroup: 'hinge', aliases: ['KB Deadlift'] },
  ),
  ex(
    'kettlebell-single-leg-deadlift',
    'Kettlebell Single-Leg Deadlift',
    C,
    'hinge',
    'KETTLEBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 12],
    90,
    4,
    { ...L, swapGroup: 'hinge', aliases: ['KB Single-Leg RDL', 'Kettlebell Single-Leg RDL'] },
  ),
  ex(
    'bulgarian-split-squat',
    'Bulgarian Split Squat',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['BSS', 'Rear-Foot-Elevated Split Squat'] },
  ),
  ex(
    'walking-lunge',
    'Walking Lunge',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 16],
    120,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['Lunge'] },
  ),
  ex(
    'dumbbell-reverse-lunge',
    'Dumbbell Reverse Lunge',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    90,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['DB Reverse Lunge', 'Dumbbell Rear Lunge'] },
  ),
  ex(
    'dumbbell-step-up',
    'Dumbbell Step-Up',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes'],
    [8, 12],
    90,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['DB Step-Up', 'Weighted Step-Up'] },
  ),
  ex(
    'barbell-lunge',
    'Barbell Lunge',
    C,
    'lunge',
    'BARBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    2.5,
    { ...L, swapGroup: 'lunge', aliases: ['BB Lunge'] },
  ),
  ex(
    'leg-extension',
    'Leg Extension',
    I,
    'knee-extension',
    'MACHINE',
    ['quads'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'knee-extension' },
  ),
  ex(
    'seated-leg-curl',
    'Seated Leg Curl',
    I,
    'knee-flexion',
    'MACHINE',
    ['hamstrings'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'leg-curl' },
  ),
  ex(
    'lying-leg-curl',
    'Lying Leg Curl',
    I,
    'knee-flexion',
    'MACHINE',
    ['hamstrings'],
    ['calves'],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'leg-curl' },
  ),
  ex(
    'standing-leg-curl',
    'Standing Leg Curl',
    I,
    'knee-flexion',
    'MACHINE',
    ['hamstrings'],
    [],
    [10, 15],
    90,
    5,
    {
      ...L,
      swapGroup: 'leg-curl',
      aliases: ['Standing Single-Leg Curl', 'Single-Leg Curl Machine'],
    },
  ),
  ex(
    'hip-thrust',
    'Hip Thrust',
    C,
    'hip-extension',
    'BARBELL',
    ['glutes'],
    ['hamstrings'],
    [8, 12],
    120,
    2.5,
    { ...L, swapGroup: 'hip-thrust', aliases: ['Barbell Hip Thrust'] },
  ),
  ex(
    'barbell-glute-bridge',
    'Barbell Glute Bridge',
    C,
    'hip-extension',
    'BARBELL',
    ['glutes'],
    ['hamstrings'],
    [8, 12],
    120,
    2.5,
    { ...L, swapGroup: 'hip-thrust', aliases: ['Barbell Hip Bridge'] },
  ),
  ex(
    'cable-glute-kickback',
    'Cable Glute Kickback',
    I,
    'hip-extension',
    'CABLE',
    ['glutes'],
    ['hamstrings'],
    [12, 15],
    60,
    2.5,
    { ...L, swapGroup: 'glute-kickback', aliases: ['Cable Kickback'] },
  ),
  ex(
    'glute-kickback-machine',
    'Glute Kickback Machine',
    I,
    'hip-extension',
    'MACHINE',
    ['glutes'],
    ['hamstrings'],
    [12, 15],
    60,
    5,
    { ...L, swapGroup: 'glute-kickback', aliases: ['Machine Glute Kickback'] },
  ),
  ex(
    'standing-calf-raise',
    'Standing Calf Raise',
    I,
    'calf-raise',
    'MACHINE',
    ['calves'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'calf-raise' },
  ),
  ex(
    'seated-calf-raise',
    'Seated Calf Raise',
    I,
    'calf-raise',
    'MACHINE',
    ['calves'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'calf-raise' },
  ),
  ex(
    'leg-press-calf-raise',
    'Leg Press Calf Raise',
    I,
    'calf-raise',
    'MACHINE',
    ['calves'],
    [],
    [12, 20],
    60,
    5,
    { ...L, swapGroup: 'calf-raise', aliases: ['Calf Press', 'Leg Press Calf Press'] },
  ),
  // Core
  ex(
    'hanging-knee-raise',
    'Hanging Knee Raise',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'core-flexion' },
  ),
  ex(
    // Its own slug since 2026-10; "Hanging Leg Raise" used to be an alias of
    // hanging-knee-raise, its easier bent-knee regression.
    'hanging-leg-raise',
    'Hanging Leg Raise',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [6, 12],
    90,
    2.5,
    { ...BW, swapGroup: 'core-flexion', aliases: ['Hanging Straight-Leg Raise'] },
  ),
  ex(
    'captains-chair-knee-raise',
    "Captain's Chair Knee Raise",
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    2.5,
    {
      ...BW,
      swapGroup: 'core-flexion',
      aliases: ["Captain's Chair Leg Raise", 'Vertical Knee Raise'],
    },
  ),
  ex(
    'cable-crunch',
    'Cable Crunch',
    I,
    'core-flexion',
    'CABLE',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'core-flexion', aliases: ['Rope Crunch'] },
  ),
  ex(
    'ab-crunch-machine',
    'Ab Crunch Machine',
    I,
    'core-flexion',
    'MACHINE',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    5,
    { swapGroup: 'core-flexion', aliases: ['Crunch Machine', 'Machine Crunch'] },
  ),
  ex(
    'crunch',
    'Crunch',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [12, 20],
    60,
    2.5,
    { ...BW, swapGroup: 'core-flexion', aliases: ['Ab Crunch', 'Floor Crunch'] },
  ),
  ex(
    'reverse-crunch',
    'Reverse Crunch',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [10, 15],
    60,
    2.5,
    { ...BW, swapGroup: 'core-flexion' },
  ),
  ex(
    'lying-leg-raise',
    'Lying Leg Raise',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    [],
    [10, 15],
    60,
    2.5,
    { ...BW, swapGroup: 'core-flexion', aliases: ['Leg Raise', 'Flat Bench Leg Raise'] },
  ),
  ex(
    'plank',
    'Plank',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [30, 60],
    60,
    2.5,
    { loadType: 'BODYWEIGHT', isTimed: true, swapGroup: 'core-stability' },
  ),
  ex(
    'side-plank',
    'Side Plank',
    I,
    'anti-lateral-flexion',
    'BODYWEIGHT',
    ['obliques'],
    ['abs', 'abductors'],
    [20, 45],
    60,
    2.5,
    { ...BW, isTimed: true, swapGroup: 'core-stability', aliases: ['Side Bridge'] },
  ),
  ex(
    'hollow-body-hold',
    'Hollow Body Hold',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    [],
    [20, 40],
    60,
    2.5,
    { ...BW, isTimed: true, swapGroup: 'core-stability', aliases: ['Hollow Hold', 'Hollow Body'] },
  ),
  ex(
    'ab-wheel-rollout',
    'Ab Wheel Rollout',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    ['lats', 'obliques'],
    [6, 12],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'core-stability', aliases: ['Ab Rollout'] },
  ),
  ex(
    'dead-bug',
    'Dead Bug',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [8, 12],
    60,
    2.5,
    { ...BW, swapGroup: 'core-stability', aliases: ['Deadbug'] },
  ),
  ex(
    'bird-dog',
    'Bird Dog',
    I,
    'anti-rotation',
    'BODYWEIGHT',
    ['abs', 'lower-back'],
    ['glutes', 'obliques'],
    [8, 12],
    60,
    2.5,
    { ...BW, swapGroup: 'core-stability', aliases: ['Quadruped Reach'] },
  ),
  ex(
    'pallof-press',
    'Pallof Press',
    I,
    'anti-rotation',
    'CABLE',
    ['obliques'],
    ['abs'],
    [10, 15],
    60,
    2.5,
    { swapGroup: 'core-stability' },
  ),
  ex(
    'cable-woodchop',
    'Cable Woodchop',
    I,
    'rotation',
    'CABLE',
    ['obliques'],
    ['abs'],
    [10, 15],
    60,
    2.5,
    { swapGroup: 'core-stability', aliases: ['Woodchopper', 'Cable Wood Chop', 'Cable Chop'] },
  ),
  // Extras
  ex(
    'dumbbell-shrug',
    'Dumbbell Shrug',
    I,
    'shrug',
    'DUMBBELL',
    ['traps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'shrug', aliases: ['Shrug'] },
  ),
  ex(
    'barbell-shrug',
    'Barbell Shrug',
    I,
    'shrug',
    'BARBELL',
    ['traps'],
    ['forearms'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'shrug', aliases: ['BB Shrug'] },
  ),
  ex(
    'farmers-carry',
    "Farmer's Carry",
    C,
    'carry',
    'DUMBBELL',
    ['forearms', 'traps'],
    ['abs', 'upper-back'],
    [30, 45],
    120,
    2,
    { ...PH, isTimed: true, swapGroup: 'carry', aliases: ["Farmer's Walk"] },
  ),
  ex(
    'suitcase-carry',
    'Suitcase Carry',
    C,
    'carry',
    'DUMBBELL',
    ['obliques', 'forearms'],
    ['traps', 'abs'],
    [30, 45],
    90,
    2,
    {
      ...PH,
      isTimed: true,
      swapGroup: 'carry',
      aliases: ['One-Arm Carry', "Single-Arm Farmer's Carry"],
    },
  ),
  ex(
    'cable-pull-through',
    'Cable Pull-Through',
    C,
    'hinge',
    'CABLE',
    ['glutes'],
    ['hamstrings'],
    [10, 15],
    90,
    2.5,
    { ...L, swapGroup: 'hinge' },
  ),
  ex(
    // T-05.10 (library staples, UX-05 A5, AC27-29): BODYWEIGHT_PLUS so
    // "+ Add weight" (Q-28) lets a held plate load it without a dip belt.
    // swapGroup 'hinge' groups it with the RDL/deadlift family as the
    // no-barbell posterior-chain accessory.
    'back-extension',
    'Back Extension',
    I,
    'hip-extension',
    'BODYWEIGHT',
    ['lower-back'],
    ['glutes', 'hamstrings'],
    [10, 15],
    90,
    2.5,
    {
      loadType: 'BODYWEIGHT_PLUS',
      swapGroup: 'hinge',
      heldLoad: true,
      aliases: ['Hyperextension', 'Roman Chair', 'Hyperextension Bench'],
    },
  ),
  ex(
    'hip-abduction-machine',
    'Hip Abduction Machine',
    I,
    'hip-abduction',
    'MACHINE',
    ['abductors'],
    ['glutes'],
    [12, 20],
    90,
    5,
    { ...L, swapGroup: 'hip-abduction', aliases: ['Hip Abduction', 'Seated Abduction'] },
  ),
  ex(
    'band-lateral-walk',
    'Banded Lateral Walk',
    I,
    'hip-abduction',
    'BAND',
    ['abductors'],
    ['glutes'],
    [10, 20],
    60,
    2.5,
    {
      ...L,
      swapGroup: 'hip-abduction',
      aliases: ['Lateral Band Walk', 'Band Walk', 'Monster Walk'],
    },
  ),
  ex(
    'hip-adduction-machine',
    'Hip Adduction Machine',
    I,
    'hip-adduction',
    'MACHINE',
    ['adductors'],
    [],
    [12, 20],
    90,
    5,
    {
      ...L,
      swapGroup: 'hip-adduction',
      aliases: ['Hip Adduction', 'Seated Adduction', 'Inner Thigh Machine'],
    },
  ),
  // ── Home variants (audit F-GYM-2-1) ──
  // Every template slot needs a real Dumbbell-only and Bodyweight-only option,
  // so the "Dumbbells + bench" and "Bodyweight" setups never prescribe a
  // barbell, machine or cable. Swap tables: templates.ts EQUIPMENT_SWAPS.
  // Dumbbell
  ex(
    'dumbbell-romanian-deadlift',
    'Dumbbell Romanian Deadlift',
    C,
    'hinge',
    'DUMBBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 12],
    120,
    2,
    { ...L, ...PH, swapGroup: 'hinge', aliases: ['DB RDL', 'Dumbbell RDL'] },
  ),
  ex(
    'dumbbell-hip-thrust',
    'Dumbbell Hip Thrust',
    C,
    'hip-extension',
    'DUMBBELL',
    ['glutes'],
    ['hamstrings'],
    [10, 15],
    90,
    2,
    { ...L, swapGroup: 'hip-thrust', aliases: ['DB Hip Thrust'] },
  ),
  ex(
    'dumbbell-overhead-triceps-extension',
    'Dumbbell Overhead Triceps Extension',
    I,
    'elbow-extension-overhead',
    'DUMBBELL',
    ['triceps'],
    [],
    [10, 15],
    90,
    2,
    { swapGroup: 'triceps-extension', aliases: ['Seated Triceps Press', 'DB French Press'] },
  ),
  ex(
    'dumbbell-skull-crusher',
    'Dumbbell Skull Crusher',
    I,
    'elbow-extension',
    'DUMBBELL',
    ['triceps'],
    [],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'triceps-extension', aliases: ['Lying Dumbbell Triceps Extension'] },
  ),
  ex(
    'dumbbell-triceps-kickback',
    'Dumbbell Triceps Kickback',
    I,
    'elbow-extension',
    'DUMBBELL',
    ['triceps'],
    [],
    [12, 15],
    60,
    2,
    { ...PH, swapGroup: 'triceps-extension', aliases: ['Triceps Kickback', 'DB Kickback'] },
  ),
  ex(
    'dumbbell-reverse-fly',
    'Dumbbell Reverse Fly',
    I,
    'rear-delt',
    'DUMBBELL',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    90,
    2,
    { ...PH, swapGroup: 'rear-delt', aliases: ['Rear-Delt Dumbbell Fly', 'Reverse Flye'] },
  ),
  ex(
    'dumbbell-fly',
    'Dumbbell Fly',
    I,
    'chest-fly',
    'DUMBBELL',
    ['chest'],
    ['front-delts'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'chest-fly', aliases: ['Dumbbell Flye', 'DB Fly'] },
  ),
  ex(
    'incline-dumbbell-fly',
    'Incline Dumbbell Fly',
    I,
    'chest-fly',
    'DUMBBELL',
    ['chest'],
    ['front-delts'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'chest-fly', aliases: ['Incline DB Fly', 'Incline Flye'] },
  ),
  ex(
    'incline-dumbbell-row',
    'Chest-Supported Dumbbell Row',
    C,
    'horizontal-pull',
    'DUMBBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    90,
    2,
    { ...PH, swapGroup: 'horizontal-row', aliases: ['Incline Dumbbell Row', 'DB Seal Row'] },
  ),
  ex(
    'bent-over-dumbbell-row',
    'Bent-Over Dumbbell Row',
    C,
    'horizontal-pull',
    'DUMBBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts', 'lower-back'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'horizontal-row', aliases: ['Two-Arm Dumbbell Row', 'DB Bent-Over Row'] },
  ),
  ex(
    'dumbbell-calf-raise',
    'Dumbbell Calf Raise',
    I,
    'calf-raise',
    'DUMBBELL',
    ['calves'],
    [],
    [12, 20],
    60,
    2,
    { ...L, ...PH, swapGroup: 'calf-raise', aliases: ['Standing Dumbbell Calf Raise'] },
  ),
  // Bodyweight — reps first, then sets (BW_ADD_SET), then a harder variation
  // from the same swap group (STALL_SUGGEST_SWAP).
  ex(
    'bodyweight-squat',
    'Bodyweight Squat',
    C,
    'squat',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [15, 30],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'squat', aliases: ['Air Squat'] },
  ),
  ex(
    'pistol-squat',
    'Pistol Squat',
    C,
    'squat',
    'BODYWEIGHT',
    ['quads'],
    ['glutes'],
    [3, 8],
    120,
    2.5,
    { ...L, ...BW, swapGroup: 'squat', aliases: ['Single-Leg Squat', 'Pistol'] },
  ),
  ex('wall-sit', 'Wall Sit', I, 'squat', 'BODYWEIGHT', ['quads'], ['glutes'], [30, 60], 60, 2.5, {
    ...L,
    ...BW,
    isTimed: true,
    swapGroup: 'squat',
    aliases: ['Wall Squat Hold'],
  }),
  ex(
    'reverse-lunge',
    'Reverse Lunge',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 20],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Rear Lunge', 'Bodyweight Lunge'] },
  ),
  ex(
    'lateral-lunge',
    'Lateral Lunge',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads', 'adductors'],
    ['glutes'],
    [8, 15],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Side Lunge'] },
  ),
  ex(
    'step-up',
    'Bodyweight Step-Up',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads'],
    ['glutes'],
    [10, 20],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Step-Up', 'Box Step-Up'] },
  ),
  ex(
    'bodyweight-bulgarian-split-squat',
    'Bodyweight Bulgarian Split Squat',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 20],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Bodyweight BSS', 'Split Squat'] },
  ),
  ex(
    'single-leg-romanian-deadlift',
    'Single-Leg Romanian Deadlift',
    C,
    'hinge',
    'BODYWEIGHT',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 15],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'hinge', aliases: ['Single-Leg RDL', 'SL RDL'] },
  ),
  ex(
    'slider-leg-curl',
    'Slider Leg Curl',
    I,
    'knee-flexion',
    'BODYWEIGHT',
    ['hamstrings'],
    ['glutes'],
    [8, 15],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'leg-curl', aliases: ['Towel Leg Curl', 'Sliding Leg Curl'] },
  ),
  ex(
    'nordic-curl',
    'Nordic Curl',
    I,
    'knee-flexion',
    'BODYWEIGHT',
    ['hamstrings'],
    [],
    [3, 8],
    120,
    2.5,
    { ...L, ...BW, swapGroup: 'leg-curl', aliases: ['Nordic Hamstring Curl'] },
  ),
  ex(
    // Needs a glute-ham developer, like back-extension needs its bench:
    // tagged BODYWEIGHT (reps-first), listed after the slider and Nordic
    // curls so the engine's closest-alternative tie-break prefers those.
    'glute-ham-raise',
    'Glute-Ham Raise',
    I,
    'knee-flexion',
    'BODYWEIGHT',
    ['hamstrings'],
    ['glutes', 'calves'],
    [5, 10],
    120,
    2.5,
    { ...L, ...BW, swapGroup: 'leg-curl', aliases: ['GHR', 'Glute Ham Raise'] },
  ),
  ex(
    'glute-bridge',
    'Glute Bridge',
    C,
    'hip-extension',
    'BODYWEIGHT',
    ['glutes'],
    ['hamstrings'],
    [12, 25],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'hip-thrust', aliases: ['Bridge', 'Hip Bridge'] },
  ),
  ex(
    'single-leg-glute-bridge',
    'Single-Leg Glute Bridge',
    C,
    'hip-extension',
    'BODYWEIGHT',
    ['glutes'],
    ['hamstrings'],
    [8, 15],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'hip-thrust', aliases: ['Single-Leg Bridge'] },
  ),
  ex(
    'donkey-kick',
    'Donkey Kick',
    I,
    'hip-extension',
    'BODYWEIGHT',
    ['glutes'],
    ['hamstrings'],
    [12, 20],
    60,
    2.5,
    {
      ...L,
      ...BW,
      swapGroup: 'glute-kickback',
      aliases: ['Quadruped Kickback', 'Kneeling Glute Kickback'],
    },
  ),
  ex(
    'clamshell',
    'Clamshell',
    I,
    'hip-abduction',
    'BODYWEIGHT',
    ['abductors'],
    ['glutes'],
    [12, 20],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'hip-abduction', aliases: ['Clam Shell', 'Banded Clamshell'] },
  ),
  ex(
    'single-leg-calf-raise',
    'Single-Leg Calf Raise',
    I,
    'calf-raise',
    'BODYWEIGHT',
    ['calves'],
    [],
    [10, 20],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'calf-raise', aliases: ['One-Leg Calf Raise'] },
  ),
  ex(
    'inverted-row',
    'Inverted Row',
    C,
    'horizontal-pull',
    'BODYWEIGHT',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 15],
    90,
    2.5,
    { ...BW, swapGroup: 'horizontal-row', aliases: ['Bodyweight Row', 'Australian Pull-Up'] },
  ),
  ex(
    'incline-push-up',
    'Incline Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'horizontal-press', aliases: ['Hands-Elevated Push-Up'] },
  ),
  ex(
    'kneeling-push-up',
    'Kneeling Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 20],
    60,
    2.5,
    { ...BW, swapGroup: 'horizontal-press', aliases: ['Knee Push-Up', 'Modified Push-Up'] },
  ),
  ex(
    'decline-push-up',
    'Decline Push-Up',
    C,
    'incline-push',
    'BODYWEIGHT',
    ['chest'],
    ['front-delts', 'triceps'],
    [6, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'incline-press', aliases: ['Feet-Elevated Push-Up'] },
  ),
  ex(
    'diamond-push-up',
    'Diamond Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['triceps'],
    ['chest', 'front-delts'],
    [6, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'triceps-compound', aliases: ['Close-Grip Push-Up', 'Triangle Push-Up'] },
  ),
  ex(
    'bench-dip',
    'Bench Dip',
    C,
    'dip',
    'BODYWEIGHT',
    ['triceps'],
    ['chest', 'front-delts'],
    [8, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'triceps-compound', aliases: ['Bench Triceps Dip', 'Chair Dip'] },
  ),
  ex(
    'pike-push-up',
    'Pike Push-Up',
    C,
    'vertical-push',
    'BODYWEIGHT',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [6, 15],
    120,
    2.5,
    { ...BW, swapGroup: 'vertical-press', aliases: ['Pike Press-Up'] },
  ),

  // ─── Cardio (T-42.1, 06 §6) — the 12-entry W2 minimal slice. The other 18
  // (incl. every INTERVALS entry) land in W5 (T-42.6). ───────────────────────
  cardio('treadmill-walk', 'Treadmill Walk', 'TREADMILL', ExerciseTrackingType.DURATION_DISTANCE),
  cardio(
    'treadmill-incline-walk',
    'Treadmill Incline Walk',
    'TREADMILL',
    ExerciseTrackingType.DURATION_DISTANCE,
  ),
  cardio('treadmill-run', 'Treadmill Run', 'TREADMILL', ExerciseTrackingType.DURATION_DISTANCE),
  cardio('outdoor-walk', 'Outdoor Walk', 'OUTDOOR', ExerciseTrackingType.DURATION_DISTANCE),
  cardio('outdoor-run', 'Outdoor Run', 'OUTDOOR', ExerciseTrackingType.DURATION_DISTANCE),
  cardio('outdoor-cycle', 'Outdoor Cycle', 'OUTDOOR', ExerciseTrackingType.DURATION_DISTANCE),
  cardio(
    'stationary-bike-upright',
    'Stationary Bike (Upright)',
    'BIKE',
    ExerciseTrackingType.DURATION_DISTANCE,
    { aliases: ['Upright Bike', 'Exercise Bike'] },
  ),
  cardio(
    'stationary-bike-recumbent',
    'Stationary Bike (Recumbent)',
    'BIKE',
    ExerciseTrackingType.DURATION_DISTANCE,
    { aliases: ['Recumbent Bike'] },
  ),
  cardio('spin-class', 'Spin Class', 'BIKE', ExerciseTrackingType.DURATION, {
    aliases: ['Indoor Cycling Class'],
  }),
  cardio('elliptical', 'Elliptical', 'ELLIPTICAL', ExerciseTrackingType.DURATION_DISTANCE, {
    aliases: ['Cross-Trainer'],
  }),
  cardio('rowing-machine', 'Rowing Machine', 'ROWER', ExerciseTrackingType.DURATION_DISTANCE, {
    aliases: ['Indoor Row', 'Erg'],
  }),
  cardio('stair-climber', 'Stair Climber', 'STAIR_CLIMBER', ExerciseTrackingType.DURATION, {
    aliases: ['Stepmill', 'StairMaster'],
  }),

  // ─── Quick-log activities (WP-20, owner decision 2026-10-04) ────────────────
  // What "Log an activity" records: a class or session done elsewhere. All
  // DURATION on purpose — that type renders on EVERY shipped client (see
  // client-level.ts), so an activity reads back on 1.0.1 and earlier even with
  // `cardioLogging` off. The chip → id map (with `spin-class` as the cycling
  // chip) lives in activity-log.ts; the BODYWEIGHT-equipment rows carry
  // loadType BODYWEIGHT only to satisfy the catalog's equipment invariant.
  cardio('pilates-class', 'Pilates Class', 'BODYWEIGHT', ExerciseTrackingType.DURATION, {
    loadType: 'BODYWEIGHT',
    aliases: ['Pilates', 'Reformer Pilates', 'Mat Pilates'],
  }),
  cardio('yoga-class', 'Yoga Class', 'BODYWEIGHT', ExerciseTrackingType.DURATION, {
    loadType: 'BODYWEIGHT',
    aliases: ['Yoga', 'Hot Yoga', 'Vinyasa'],
  }),
  cardio('hiit-class', 'HIIT / Bootcamp Class', 'BODYWEIGHT', ExerciseTrackingType.DURATION, {
    loadType: 'BODYWEIGHT',
    aliases: ['HIIT', 'Bootcamp', 'Circuit Class'],
  }),
  cardio('dance-class', 'Dance / Zumba Class', 'BODYWEIGHT', ExerciseTrackingType.DURATION, {
    loadType: 'BODYWEIGHT',
    aliases: ['Zumba', 'Dance Class', 'Dance Fitness'],
  }),
  cardio('swimming', 'Swimming', 'POOL', ExerciseTrackingType.DURATION, {
    aliases: ['Swim', 'Pool Swim', 'Lap Swim'],
  }),
  cardio('running', 'Running', 'OUTDOOR', ExerciseTrackingType.DURATION, {
    aliases: ['Run', 'Jog', 'Jogging'],
  }),
  cardio('walking', 'Walking', 'OUTDOOR', ExerciseTrackingType.DURATION, {
    aliases: ['Walk', 'Hike', 'Hiking'],
  }),
  cardio('other-activity', 'Other Activity', 'BODYWEIGHT', ExerciseTrackingType.DURATION, {
    loadType: 'BODYWEIGHT',
    aliases: ['Other Class', 'Other Workout'],
  }),
];

const EMPTY: ExerciseContent = {
  cues: [],
  mistakes: [],
  blurb: null,
  freeExerciseDbId: null,
  videoId: null,
  videoStartSec: null,
  videoChannel: null,
};

export const EXERCISE_CATALOG: readonly ExerciseCatalogEntry[] = STRUCTURE.map((s) => {
  const content = EXERCISE_CONTENT[s.id] ?? EMPTY;
  return {
    ...s,
    ...content,
    aliases: [...new Set([...(s.aliases ?? []), ...(content.aliases ?? [])])],
  };
});

export const EXERCISE_BY_ID: ReadonlyMap<string, ExerciseCatalogEntry> = new Map(
  EXERCISE_CATALOG.map((e) => [e.id, e]),
);

/**
 * Catalog slugs whose vendored photo(s) show the wrong exercise (a
 * free-exercise-db id near-miss) — audited via
 * scripts/gym/exercise-photo-contact-sheet.ts. Both ExerciseImage (mobile)
 * and its web twin show the icon placeholder instead of these, even though
 * imageKeysFor still returns the files (T-05.11, UX-05 A6, D-22 a). Record
 * an addition here in apps/api/static/exercises/README.md "Hidden photos"
 * too.
 *
 * Empty since WP-25: `plank` (free-exercise-db's photo showed a kneeling lunge
 * stretch) got a correct photo under a new file name. The set stays exported
 * because app builds in the field import it.
 */
export const HIDDEN_EXERCISE_IMAGE_IDS: ReadonlySet<string> = new Set<string>();
