// ─── Curated exercise library ────────────────────────────────────────────────
// THE source of truth for the shared exercise pool. The API upserts it into the
// `exercises` table at boot (ensureExerciseLibrary — prod never runs the seed).
// Structural fields drive the engine (increments, volume, templates); content
// fields (cues/mistakes/blurb/media) come from docs/gym/exercise-library-research.md.
// Slugs are PERMANENT ids: sessions reference them. Never rename — add aliases.

import type { ExerciseMeta } from './engine';
import { EXERCISE_CONTENT, type ExerciseContent } from './exercise-content';
import type { Muscle } from './vocab';

export interface ExerciseCatalogEntry extends ExerciseMeta {
  aliases: string[];
  /** 3–4 imperative cues, ≤ 12 words each ("Drive your elbows down to your hips"). */
  cues: string[];
  /** 2 common mistakes, ≤ 12 words each. */
  mistakes: string[];
  blurb: string | null;
  /** free-exercise-db id (public domain photos), or null. */
  freeExerciseDbId: string | null;
  videoId: string | null;
  videoStartSec: number | null;
  videoChannel: string | null;
}

type Struct = Omit<
  ExerciseCatalogEntry,
  | 'cues'
  | 'mistakes'
  | 'blurb'
  | 'freeExerciseDbId'
  | 'videoId'
  | 'videoStartSec'
  | 'videoChannel'
  | 'aliases'
> & { aliases?: string[] };

const C = 'COMPOUND' as const;
const I = 'ISOLATION' as const;

function ex(
  id: string,
  name: string,
  category: typeof C | typeof I,
  movementPattern: string,
  equipment: ExerciseCatalogEntry['equipment'],
  primaryMuscles: Muscle[],
  secondaryMuscles: Muscle[],
  [repMin, repMax]: [number, number],
  restSec: number,
  incrementKg: number,
  opts: Partial<Struct> = {},
): Struct {
  return {
    id,
    name,
    category,
    movementPattern,
    equipment,
    loadType: 'WEIGHTED',
    primaryMuscles,
    secondaryMuscles,
    repMin,
    repMax,
    restSec,
    incrementKg,
    perHand: false,
    isLowerBody: false,
    isTimed: false,
    swapGroup: null,
    ...opts,
  };
}

const L = { isLowerBody: true } as const;
const PH = { perHand: true } as const;
/** Reps-only progression (loadModel NONE): no load, so no belt / plates. */
const BW = { loadType: 'BODYWEIGHT' } as const;

/** Structural definitions — content is merged in below from EXERCISE_CONTENT. */
const STRUCTURE: Struct[] = [
  // Chest
  ex(
    'barbell-bench-press',
    'Barbell Bench Press',
    C,
    'horizontal-push',
    'BARBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [6, 10],
    180,
    2.5,
    { swapGroup: 'horizontal-press', aliases: ['Bench Press', 'Flat Bench'] },
  ),
  ex(
    'dumbbell-bench-press',
    'Dumbbell Bench Press',
    C,
    'horizontal-push',
    'DUMBBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'horizontal-press', aliases: ['DB Bench Press'] },
  ),
  ex(
    'incline-dumbbell-press',
    'Incline Dumbbell Press',
    C,
    'incline-push',
    'DUMBBELL',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'incline-press', aliases: ['Incline DB Press'] },
  ),
  ex(
    'machine-chest-press',
    'Machine Chest Press',
    C,
    'horizontal-push',
    'MACHINE',
    ['chest'],
    ['front-delts', 'triceps'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-press' },
  ),
  ex(
    'cable-fly',
    'Cable Fly',
    I,
    'chest-fly',
    'CABLE',
    ['chest'],
    ['front-delts'],
    [12, 15],
    90,
    2.5,
    { swapGroup: 'chest-fly', aliases: ['Pec Deck', 'Cable Crossover'] },
  ),
  ex(
    'push-up',
    'Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 20],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'horizontal-press', aliases: ['Press-Up'] },
  ),
  ex(
    'chest-dip',
    'Dip',
    C,
    'dip',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [6, 12],
    120,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'dip', aliases: ['Chest Dip', 'Parallel Bar Dip'] },
  ),
  // Back
  ex(
    'pull-up',
    'Pull-Up',
    C,
    'vertical-pull',
    'BODYWEIGHT',
    ['lats'],
    ['biceps', 'upper-back'],
    [5, 10],
    150,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'vertical-pull' },
  ),
  ex(
    'chin-up',
    'Chin-Up',
    C,
    'vertical-pull',
    'BODYWEIGHT',
    ['lats'],
    ['biceps', 'upper-back'],
    [5, 10],
    150,
    2.5,
    { loadType: 'BODYWEIGHT_PLUS', swapGroup: 'vertical-pull' },
  ),
  ex(
    'assisted-pull-up',
    'Assisted Pull-Up',
    C,
    'vertical-pull',
    'ASSISTED',
    ['lats'],
    ['biceps', 'upper-back'],
    [6, 10],
    120,
    5,
    { loadType: 'ASSISTED', swapGroup: 'vertical-pull', aliases: ['Assisted Pull-Up Machine'] },
  ),
  ex(
    'lat-pulldown',
    'Lat Pulldown',
    C,
    'vertical-pull',
    'CABLE',
    ['lats'],
    ['biceps', 'upper-back'],
    [8, 12],
    120,
    5,
    { swapGroup: 'vertical-pull', aliases: ['Pulldown'] },
  ),
  ex(
    'barbell-row',
    'Barbell Row',
    C,
    'horizontal-pull',
    'BARBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts', 'lower-back'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'horizontal-row', aliases: ['Bent-Over Row'] },
  ),
  ex(
    'chest-supported-row',
    'Chest-Supported Row',
    C,
    'horizontal-pull',
    'MACHINE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-row', aliases: ['T-Bar Row', 'Seal Row'] },
  ),
  ex(
    'seated-cable-row',
    'Seated Cable Row',
    C,
    'horizontal-pull',
    'CABLE',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    120,
    5,
    { swapGroup: 'horizontal-row', aliases: ['Cable Row'] },
  ),
  ex(
    'single-arm-dumbbell-row',
    'Single-Arm Dumbbell Row',
    C,
    'horizontal-pull',
    'DUMBBELL',
    ['lats', 'upper-back'],
    ['biceps', 'rear-delts'],
    [8, 12],
    90,
    2,
    { ...PH, swapGroup: 'horizontal-row', aliases: ['One-Arm DB Row'] },
  ),
  ex(
    'face-pull',
    'Face Pull',
    I,
    'rear-delt',
    'CABLE',
    ['rear-delts'],
    ['upper-back', 'traps'],
    [12, 20],
    90,
    2.5,
    { swapGroup: 'rear-delt' },
  ),
  ex(
    'straight-arm-pulldown',
    'Straight-Arm Pulldown',
    I,
    'lat-isolation',
    'CABLE',
    ['lats'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'lat-isolation' },
  ),
  // Shoulders
  ex(
    'overhead-press',
    'Overhead Press',
    C,
    'vertical-push',
    'BARBELL',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'vertical-press', aliases: ['OHP', 'Military Press'] },
  ),
  ex(
    'seated-dumbbell-shoulder-press',
    'Seated Dumbbell Shoulder Press',
    C,
    'vertical-push',
    'DUMBBELL',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [8, 12],
    120,
    2,
    { ...PH, swapGroup: 'vertical-press', aliases: ['DB Shoulder Press'] },
  ),
  ex(
    'dumbbell-lateral-raise',
    'Dumbbell Lateral Raise',
    I,
    'lateral-raise',
    'DUMBBELL',
    ['side-delts'],
    [],
    [12, 20],
    90,
    2,
    { ...PH, swapGroup: 'lateral-raise', aliases: ['Lateral Raise', 'Side Raise'] },
  ),
  ex(
    'cable-lateral-raise',
    'Cable Lateral Raise',
    I,
    'lateral-raise',
    'CABLE',
    ['side-delts'],
    [],
    [12, 20],
    90,
    2.5,
    { swapGroup: 'lateral-raise' },
  ),
  ex(
    'reverse-pec-deck',
    'Reverse Pec Deck',
    I,
    'rear-delt',
    'MACHINE',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    90,
    5,
    { swapGroup: 'rear-delt', aliases: ['Rear-Delt Fly'] },
  ),
  // Arms
  ex(
    'barbell-curl',
    'Barbell Curl',
    I,
    'elbow-flexion',
    'BARBELL',
    ['biceps'],
    ['forearms'],
    [8, 12],
    90,
    2.5,
    { swapGroup: 'biceps-curl' },
  ),
  ex(
    'dumbbell-curl',
    'Dumbbell Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['DB Curl'] },
  ),
  ex(
    'incline-dumbbell-curl',
    'Incline Dumbbell Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    [],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl', aliases: ['Incline Curl'] },
  ),
  ex(
    'hammer-curl',
    'Hammer Curl',
    I,
    'elbow-flexion',
    'DUMBBELL',
    ['biceps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'biceps-curl' },
  ),
  ex(
    'preacher-curl',
    'Preacher Curl',
    I,
    'elbow-flexion',
    'EZ_BAR',
    ['biceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'biceps-curl', aliases: ['EZ-Bar Preacher Curl', 'Cable Preacher Curl'] },
  ),
  ex(
    'triceps-pushdown',
    'Triceps Pushdown',
    I,
    'elbow-extension',
    'CABLE',
    ['triceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Rope Pushdown', 'Pressdown'] },
  ),
  ex(
    'overhead-cable-triceps-extension',
    'Overhead Cable Triceps Extension',
    I,
    'elbow-extension-overhead',
    'CABLE',
    ['triceps'],
    [],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Overhead Triceps Extension'] },
  ),
  ex(
    'skull-crusher',
    'Skull Crusher',
    I,
    'elbow-extension',
    'EZ_BAR',
    ['triceps'],
    [],
    [8, 12],
    90,
    2.5,
    { swapGroup: 'triceps-extension', aliases: ['Lying Triceps Extension'] },
  ),
  ex(
    'close-grip-bench-press',
    'Close-Grip Bench Press',
    C,
    'horizontal-push',
    'BARBELL',
    ['triceps'],
    ['chest', 'front-delts'],
    [6, 10],
    150,
    2.5,
    { swapGroup: 'triceps-compound', aliases: ['CGBP'] },
  ),
  // Legs
  ex(
    'back-squat',
    'Back Squat',
    C,
    'squat',
    'BARBELL',
    ['quads'],
    ['glutes', 'adductors', 'lower-back'],
    [5, 8],
    180,
    2.5,
    { ...L, swapGroup: 'squat', aliases: ['Squat', 'Barbell Squat'] },
  ),
  ex(
    'front-squat',
    'Front Squat',
    C,
    'squat',
    'BARBELL',
    ['quads'],
    ['glutes', 'upper-back'],
    [5, 8],
    180,
    2.5,
    { ...L, swapGroup: 'squat' },
  ),
  ex('hack-squat', 'Hack Squat', C, 'squat', 'MACHINE', ['quads'], ['glutes'], [8, 12], 150, 5, {
    ...L,
    swapGroup: 'squat',
  }),
  ex(
    'goblet-squat',
    'Goblet Squat',
    C,
    'squat',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    2,
    { ...L, swapGroup: 'squat' },
  ),
  ex(
    'leg-press',
    'Leg Press',
    C,
    'squat',
    'MACHINE',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 15],
    150,
    5,
    { ...L, swapGroup: 'squat' },
  ),
  ex(
    'romanian-deadlift',
    'Romanian Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [6, 10],
    150,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['RDL'] },
  ),
  ex(
    'deadlift',
    'Deadlift',
    C,
    'hinge',
    'BARBELL',
    ['glutes', 'hamstrings'],
    ['quads', 'lower-back', 'upper-back', 'traps', 'forearms'],
    [4, 6],
    180,
    2.5,
    { ...L, swapGroup: 'hinge', aliases: ['Conventional Deadlift'] },
  ),
  ex(
    'bulgarian-split-squat',
    'Bulgarian Split Squat',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 12],
    120,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['BSS', 'Rear-Foot-Elevated Split Squat'] },
  ),
  ex(
    'walking-lunge',
    'Walking Lunge',
    C,
    'lunge',
    'DUMBBELL',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 16],
    120,
    2,
    { ...L, ...PH, swapGroup: 'lunge', aliases: ['Lunge'] },
  ),
  ex(
    'leg-extension',
    'Leg Extension',
    I,
    'knee-extension',
    'MACHINE',
    ['quads'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'knee-extension' },
  ),
  ex(
    'seated-leg-curl',
    'Seated Leg Curl',
    I,
    'knee-flexion',
    'MACHINE',
    ['hamstrings'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'leg-curl' },
  ),
  ex(
    'lying-leg-curl',
    'Lying Leg Curl',
    I,
    'knee-flexion',
    'MACHINE',
    ['hamstrings'],
    ['calves'],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'leg-curl' },
  ),
  ex(
    'hip-thrust',
    'Hip Thrust',
    C,
    'hip-extension',
    'BARBELL',
    ['glutes'],
    ['hamstrings'],
    [8, 12],
    120,
    2.5,
    { ...L, swapGroup: 'hip-thrust', aliases: ['Barbell Hip Thrust'] },
  ),
  ex(
    'standing-calf-raise',
    'Standing Calf Raise',
    I,
    'calf-raise',
    'MACHINE',
    ['calves'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'calf-raise' },
  ),
  ex(
    'seated-calf-raise',
    'Seated Calf Raise',
    I,
    'calf-raise',
    'MACHINE',
    ['calves'],
    [],
    [10, 15],
    90,
    5,
    { ...L, swapGroup: 'calf-raise' },
  ),
  // Core
  ex(
    'hanging-knee-raise',
    'Hanging Knee Raise',
    I,
    'core-flexion',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'core-flexion', aliases: ['Hanging Leg Raise'] },
  ),
  ex(
    'cable-crunch',
    'Cable Crunch',
    I,
    'core-flexion',
    'CABLE',
    ['abs'],
    ['obliques'],
    [10, 15],
    90,
    2.5,
    { swapGroup: 'core-flexion', aliases: ['Rope Crunch'] },
  ),
  ex(
    'plank',
    'Plank',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    ['obliques'],
    [30, 60],
    60,
    2.5,
    { loadType: 'BODYWEIGHT', isTimed: true, swapGroup: 'core-stability' },
  ),
  ex(
    'ab-wheel-rollout',
    'Ab Wheel Rollout',
    I,
    'anti-extension',
    'BODYWEIGHT',
    ['abs'],
    ['lats', 'obliques'],
    [6, 12],
    90,
    2.5,
    { loadType: 'BODYWEIGHT', swapGroup: 'core-stability', aliases: ['Ab Rollout'] },
  ),
  ex(
    'pallof-press',
    'Pallof Press',
    I,
    'anti-rotation',
    'CABLE',
    ['obliques'],
    ['abs'],
    [10, 15],
    60,
    2.5,
    { swapGroup: 'core-stability' },
  ),
  // Extras
  ex(
    'dumbbell-shrug',
    'Dumbbell Shrug',
    I,
    'shrug',
    'DUMBBELL',
    ['traps'],
    ['forearms'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'shrug', aliases: ['Shrug'] },
  ),
  ex(
    'farmers-carry',
    "Farmer's Carry",
    C,
    'carry',
    'DUMBBELL',
    ['forearms', 'traps'],
    ['abs', 'upper-back'],
    [30, 45],
    120,
    2,
    { ...PH, isTimed: true, swapGroup: 'carry', aliases: ["Farmer's Walk"] },
  ),
  ex(
    'cable-pull-through',
    'Cable Pull-Through',
    C,
    'hinge',
    'CABLE',
    ['glutes'],
    ['hamstrings'],
    [10, 15],
    90,
    2.5,
    { ...L, swapGroup: 'hinge' },
  ),
  ex(
    'hip-abduction-machine',
    'Hip Abduction Machine',
    I,
    'hip-abduction',
    'MACHINE',
    ['abductors'],
    ['glutes'],
    [12, 20],
    90,
    5,
    { ...L, swapGroup: 'hip-abduction', aliases: ['Hip Abduction', 'Seated Abduction'] },
  ),
  // ── Home variants (audit F-GYM-2-1) ──
  // Every template slot needs a real Dumbbell-only and Bodyweight-only option,
  // so the "Dumbbells + bench" and "Bodyweight" setups never prescribe a
  // barbell, machine or cable. Swap tables: templates.ts EQUIPMENT_SWAPS.
  // Dumbbell
  ex(
    'dumbbell-romanian-deadlift',
    'Dumbbell Romanian Deadlift',
    C,
    'hinge',
    'DUMBBELL',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 12],
    120,
    2,
    { ...L, ...PH, swapGroup: 'hinge', aliases: ['DB RDL', 'Dumbbell RDL'] },
  ),
  ex(
    'dumbbell-hip-thrust',
    'Dumbbell Hip Thrust',
    C,
    'hip-extension',
    'DUMBBELL',
    ['glutes'],
    ['hamstrings'],
    [10, 15],
    90,
    2,
    { ...L, swapGroup: 'hip-thrust', aliases: ['DB Hip Thrust'] },
  ),
  ex(
    'dumbbell-overhead-triceps-extension',
    'Dumbbell Overhead Triceps Extension',
    I,
    'elbow-extension-overhead',
    'DUMBBELL',
    ['triceps'],
    [],
    [10, 15],
    90,
    2,
    { swapGroup: 'triceps-extension', aliases: ['Seated Triceps Press', 'DB French Press'] },
  ),
  ex(
    'dumbbell-skull-crusher',
    'Dumbbell Skull Crusher',
    I,
    'elbow-extension',
    'DUMBBELL',
    ['triceps'],
    [],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'triceps-extension', aliases: ['Lying Dumbbell Triceps Extension'] },
  ),
  ex(
    'dumbbell-reverse-fly',
    'Dumbbell Reverse Fly',
    I,
    'rear-delt',
    'DUMBBELL',
    ['rear-delts'],
    ['upper-back'],
    [12, 20],
    90,
    2,
    { ...PH, swapGroup: 'rear-delt', aliases: ['Rear-Delt Dumbbell Fly', 'Reverse Flye'] },
  ),
  ex(
    'dumbbell-fly',
    'Dumbbell Fly',
    I,
    'chest-fly',
    'DUMBBELL',
    ['chest'],
    ['front-delts'],
    [10, 15],
    90,
    2,
    { ...PH, swapGroup: 'chest-fly', aliases: ['Dumbbell Flye', 'DB Fly'] },
  ),
  ex(
    'incline-dumbbell-row',
    'Chest-Supported Dumbbell Row',
    C,
    'horizontal-pull',
    'DUMBBELL',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 12],
    90,
    2,
    { ...PH, swapGroup: 'horizontal-row', aliases: ['Incline Dumbbell Row', 'DB Seal Row'] },
  ),
  ex(
    'dumbbell-calf-raise',
    'Dumbbell Calf Raise',
    I,
    'calf-raise',
    'DUMBBELL',
    ['calves'],
    [],
    [12, 20],
    60,
    2,
    { ...L, ...PH, swapGroup: 'calf-raise', aliases: ['Standing Dumbbell Calf Raise'] },
  ),
  // Bodyweight — reps first, then sets (BW_ADD_SET), then a harder variation
  // from the same swap group (STALL_SUGGEST_SWAP).
  ex(
    'bodyweight-squat',
    'Bodyweight Squat',
    C,
    'squat',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [15, 30],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'squat', aliases: ['Air Squat'] },
  ),
  ex(
    'reverse-lunge',
    'Reverse Lunge',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [10, 20],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Rear Lunge', 'Bodyweight Lunge'] },
  ),
  ex(
    'bodyweight-bulgarian-split-squat',
    'Bodyweight Bulgarian Split Squat',
    C,
    'lunge',
    'BODYWEIGHT',
    ['quads'],
    ['glutes', 'adductors'],
    [8, 20],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'lunge', aliases: ['Bodyweight BSS', 'Split Squat'] },
  ),
  ex(
    'single-leg-romanian-deadlift',
    'Single-Leg Romanian Deadlift',
    C,
    'hinge',
    'BODYWEIGHT',
    ['hamstrings'],
    ['glutes', 'lower-back'],
    [8, 15],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'hinge', aliases: ['Single-Leg RDL', 'SL RDL'] },
  ),
  ex(
    'slider-leg-curl',
    'Slider Leg Curl',
    I,
    'knee-flexion',
    'BODYWEIGHT',
    ['hamstrings'],
    ['glutes'],
    [8, 15],
    90,
    2.5,
    { ...L, ...BW, swapGroup: 'leg-curl', aliases: ['Towel Leg Curl', 'Sliding Leg Curl'] },
  ),
  ex(
    'nordic-curl',
    'Nordic Curl',
    I,
    'knee-flexion',
    'BODYWEIGHT',
    ['hamstrings'],
    [],
    [3, 8],
    120,
    2.5,
    { ...L, ...BW, swapGroup: 'leg-curl', aliases: ['Nordic Hamstring Curl'] },
  ),
  ex(
    'glute-bridge',
    'Glute Bridge',
    C,
    'hip-extension',
    'BODYWEIGHT',
    ['glutes'],
    ['hamstrings'],
    [12, 25],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'hip-thrust', aliases: ['Bridge', 'Hip Bridge'] },
  ),
  ex(
    'single-leg-glute-bridge',
    'Single-Leg Glute Bridge',
    C,
    'hip-extension',
    'BODYWEIGHT',
    ['glutes'],
    ['hamstrings'],
    [8, 15],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'hip-thrust', aliases: ['Single-Leg Bridge'] },
  ),
  ex(
    'single-leg-calf-raise',
    'Single-Leg Calf Raise',
    I,
    'calf-raise',
    'BODYWEIGHT',
    ['calves'],
    [],
    [10, 20],
    60,
    2.5,
    { ...L, ...BW, swapGroup: 'calf-raise', aliases: ['One-Leg Calf Raise'] },
  ),
  ex(
    'inverted-row',
    'Inverted Row',
    C,
    'horizontal-pull',
    'BODYWEIGHT',
    ['upper-back', 'lats'],
    ['biceps', 'rear-delts'],
    [8, 15],
    90,
    2.5,
    { ...BW, swapGroup: 'horizontal-row', aliases: ['Bodyweight Row', 'Australian Pull-Up'] },
  ),
  ex(
    'incline-push-up',
    'Incline Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['chest'],
    ['triceps', 'front-delts'],
    [8, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'horizontal-press', aliases: ['Hands-Elevated Push-Up'] },
  ),
  ex(
    'decline-push-up',
    'Decline Push-Up',
    C,
    'incline-push',
    'BODYWEIGHT',
    ['chest'],
    ['front-delts', 'triceps'],
    [6, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'incline-press', aliases: ['Feet-Elevated Push-Up'] },
  ),
  ex(
    'diamond-push-up',
    'Diamond Push-Up',
    C,
    'horizontal-push',
    'BODYWEIGHT',
    ['triceps'],
    ['chest', 'front-delts'],
    [6, 20],
    90,
    2.5,
    { ...BW, swapGroup: 'triceps-compound', aliases: ['Close-Grip Push-Up', 'Triangle Push-Up'] },
  ),
  ex(
    'pike-push-up',
    'Pike Push-Up',
    C,
    'vertical-push',
    'BODYWEIGHT',
    ['front-delts'],
    ['side-delts', 'triceps'],
    [6, 15],
    120,
    2.5,
    { ...BW, swapGroup: 'vertical-press', aliases: ['Pike Press-Up'] },
  ),
];

const EMPTY: ExerciseContent = {
  cues: [],
  mistakes: [],
  blurb: null,
  freeExerciseDbId: null,
  videoId: null,
  videoStartSec: null,
  videoChannel: null,
};

export const EXERCISE_CATALOG: readonly ExerciseCatalogEntry[] = STRUCTURE.map((s) => {
  const content = EXERCISE_CONTENT[s.id] ?? EMPTY;
  return {
    ...s,
    ...content,
    aliases: [...new Set([...(s.aliases ?? []), ...(content.aliases ?? [])])],
  };
});

export const EXERCISE_BY_ID: ReadonlyMap<string, ExerciseCatalogEntry> = new Map(
  EXERCISE_CATALOG.map((e) => [e.id, e]),
);
