#!/usr/bin/env node
// Extracts the FDC values the nutrition engine's golden tests use
// (packages/utils/src/nutrition/fdc-golden.fixture.ts). Every number in that
// fixture is READ from the USDA FDC SR Legacy CSVs here, never typed by hand
// or by a model (plan-ingredient-catalog §0, §5.5).
//
//   node scripts/ingredients/golden-fixture.mjs [path/to/fdc-sr-legacy]
//
// Default source dir: scripts/ingredients/out/sources/fdc-sr-legacy (fetched by
// the catalog build's fetch script; git-ignored).
import { createReadStream, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = process.argv[2] ?? join(here, 'out/sources/fdc-sr-legacy');
const OUT = join(here, '../../packages/utils/src/nutrition/fdc-golden.fixture.ts');

/** key → FDC SR Legacy fdc_id. */
const FOODS = {
  chickenBreastRaw: 171077,
  chickenThighSkinOnRaw: 172385,
  riceWhiteDry: 169756,
  oliveOil: 171413,
  garlic: 169230,
  flourAllPurpose: 168894,
  egg: 171287,
  onion: 170000,
  broccoli: 170379,
  butter: 173410,
  milkWhole: 171265,
  oatsDry: 173904,
  tomato: 170457,
  banana: 173944,
  spinach: 168462,
  avocado: 171705,
  lentilsDry: 172420,
  sugar: 169655,
  salt: 173468,
  potato: 170026,
  beefGround90: 174030,
  chickpeasDry: 173756,
  honey: 169640,
  almonds: 170567,
  carrot: 170393,
  greekYogurtLowfat: 170903,
  salmonFarmed: 175167,
  redPepper: 170108,
  feta: 173420,
  lemonJuice: 167747,
  quinoaCooked: 168917,
};
const NUTRIENTS = {
  1008: 'kcal',
  1003: 'protein',
  1005: 'carbsByDifference',
  1004: 'fat',
  1079: 'fiber',
};

function splitCsv(line) {
  const out = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (quoted) {
      if (c === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (c === '"') quoted = false;
      else cur += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') {
      out.push(cur);
      cur = '';
    } else cur += c;
  }
  out.push(cur);
  return out;
}

async function rows(file, onRow) {
  const rl = createInterface({ input: createReadStream(join(SRC, file)), crlfDelay: Infinity });
  let header;
  for await (const line of rl) {
    const cells = splitCsv(line);
    if (!header) header = cells;
    else onRow(Object.fromEntries(header.map((h, i) => [h, cells[i]])));
  }
}

const wanted = new Set(Object.values(FOODS).map(String));
const desc = {};
const values = {};
const portions = {};
const units = {};
await rows('food.csv', (r) => {
  if (wanted.has(r.fdc_id)) desc[r.fdc_id] = r.description;
});
await rows('measure_unit.csv', (r) => {
  units[r.id] = r.name;
});
await rows('food_nutrient.csv', (r) => {
  const key = NUTRIENTS[r.nutrient_id];
  if (key && wanted.has(r.fdc_id)) (values[r.fdc_id] ??= {})[key] = Number(r.amount);
});
await rows('food_portion.csv', (r) => {
  if (!wanted.has(r.fdc_id)) return;
  const unit = units[r.measure_unit_id] === 'undetermined' ? '' : units[r.measure_unit_id];
  const label = [r.amount, unit, r.modifier].filter(Boolean).join(' ');
  (portions[r.fdc_id] ??= []).push({ label, gramWeight: Number(r.gram_weight) });
});

const lines = [
  '// GENERATED by scripts/ingredients/golden-fixture.mjs from USDA FoodData Central',
  '// SR Legacy (April 2018, CC0). Do not edit by hand: re-run the script.',
  '// Values are per 100 g as published; carbs here are carbohydrate BY DIFFERENCE',
  '// (the golden tests apply the EU conversion, carbs − fiber, D2).',
  '',
  'export interface FdcGoldenFood {',
  '  fdcId: number;',
  '  description: string;',
  '  kcal: number;',
  '  protein: number;',
  '  carbsByDifference: number;',
  '  fat: number;',
  '  fiber: number;',
  '  portions: { label: string; gramWeight: number }[];',
  '}',
  '',
  'export const FDC_GOLDEN = {',
];
for (const [key, id] of Object.entries(FOODS)) {
  const v = values[id];
  if (!v || !desc[id]) throw new Error(`fdc ${id} (${key}) not found in ${SRC}`);
  for (const n of Object.values(NUTRIENTS))
    if (typeof v[n] !== 'number') throw new Error(`fdc ${id} missing ${n}`);
  lines.push(
    `  ${key}: ${JSON.stringify({ fdcId: id, description: desc[id], kcal: v.kcal, protein: v.protein, carbsByDifference: v.carbsByDifference, fat: v.fat, fiber: v.fiber, portions: portions[id] ?? [] })},`,
  );
}
lines.push('} satisfies Record<string, FdcGoldenFood>;', '');
writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${Object.keys(FOODS).length} foods to ${OUT}`);
