import { render, screen } from '@testing-library/react-native';
import { AiGeneratedChip } from '../../src/components/ai-generated-chip';

// UX-26 AC5 / T-26.6: the AI chip renders on AI-generated recipes only.

describe('AiGeneratedChip', () => {
  it('renders on an AI-generated recipe', async () => {
    await render(<AiGeneratedChip recipe={{ aiGenerated: true }} />);
    expect(screen.getByText('AI-generated')).toBeTruthy();
    expect(screen.getByLabelText('This recipe was generated by AI')).toBeTruthy();
  });

  it.each([{ aiGenerated: false }, {}, null, undefined])(
    'renders nothing when the recipe is not flagged (%j)',
    async (recipe) => {
      await render(<AiGeneratedChip recipe={recipe} />);
      expect(screen.queryByText('AI-generated')).toBeNull();
    },
  );
});
