import type { GroceryCategory } from '../../lib/grocery-ai/types.js';

// ─── Ingredient → grocery category inference ──────────────────────────────────
// The single keyword map for categorising ingredients. It used to exist twice
// (here and a Title-Case copy in meal-plan.service) with diverging values, so
// the same ingredient could land in different aisles on different screens.

const CATEGORY_KEYWORDS: Record<string, GroceryCategory> = {
  tomato: 'produce',
  spinach: 'produce',
  onion: 'produce',
  garlic: 'produce',
  lemon: 'produce',
  lime: 'produce',
  avocado: 'produce',
  mushroom: 'produce',
  pepper: 'produce',
  lettuce: 'produce',
  cucumber: 'produce',
  zucchini: 'produce',
  carrot: 'produce',
  broccoli: 'produce',
  celery: 'produce',
  kale: 'produce',
  apple: 'produce',
  banana: 'produce',
  berry: 'produce',
  strawberry: 'produce',
  blueberry: 'produce',
  raspberry: 'produce',
  fruit: 'produce',
  shallot: 'produce',
  herb: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  coriander: 'produce',
  basil: 'produce',
  mint: 'produce',
  chive: 'produce',
  potato: 'produce',
  courgette: 'produce',
  aubergine: 'produce',
  eggplant: 'produce',
  cauliflower: 'produce',
  cabbage: 'produce',
  leek: 'produce',
  ginger: 'produce',
  // "chili powder" is a spice — must outrank the produce "chili" below
  'chili powder': 'grains',
  chili: 'produce',
  chilli: 'produce',
  pea: 'produce',
  leaves: 'produce',
  rocket: 'produce',
  arugula: 'produce',
  squash: 'produce',
  pumpkin: 'produce',
  beetroot: 'produce',
  asparagus: 'produce',
  grape: 'produce',
  orange: 'produce',
  mango: 'produce',
  pineapple: 'produce',
  peach: 'produce',
  pear: 'produce',
  melon: 'produce',
  fennel: 'produce',
  radish: 'produce',
  scallion: 'produce',
  chicken: 'proteins',
  beef: 'proteins',
  salmon: 'proteins',
  tuna: 'proteins',
  egg: 'proteins',
  tofu: 'proteins',
  shrimp: 'proteins',
  turkey: 'proteins',
  pork: 'proteins',
  lamb: 'proteins',
  cod: 'proteins',
  fish: 'proteins',
  pepperoni: 'proteins',
  tempeh: 'proteins',
  seitan: 'proteins',
  prawn: 'proteins',
  sardine: 'proteins',
  anchovy: 'proteins',
  bacon: 'proteins',
  ham: 'proteins',
  sausage: 'proteins',
  duck: 'proteins',
  trout: 'proteins',
  mackerel: 'proteins',
  milk: 'dairy',
  cheese: 'dairy',
  yogurt: 'dairy',
  yoghurt: 'dairy',
  butter: 'dairy',
  cream: 'dairy',
  parmesan: 'dairy',
  mozzarella: 'dairy',
  feta: 'dairy',
  halloumi: 'dairy',
  paneer: 'dairy',
  ricotta: 'dairy',
  cheddar: 'dairy',
  ghee: 'dairy',
  kefir: 'dairy',
  rice: 'grains',
  pasta: 'grains',
  flour: 'grains',
  bread: 'grains',
  breadcrumb: 'grains',
  oat: 'grains',
  quinoa: 'grains',
  lentil: 'grains',
  bean: 'grains',
  oil: 'grains',
  vinegar: 'grains',
  soy: 'grains',
  honey: 'grains',
  almond: 'grains',
  walnut: 'grains',
  cashew: 'grains',
  nut: 'grains',
  // nut butters are pantry, not dairy — must outrank "butter"
  'peanut butter': 'grains',
  'almond butter': 'grains',
  peanut: 'grains',
  chickpea: 'grains',
  coconut: 'grains',
  tortilla: 'grains',
  wrap: 'grains',
  pita: 'grains',
  roti: 'grains',
  naan: 'grains',
  couscous: 'grains',
  barley: 'grains',
  buckwheat: 'grains',
  bulgur: 'grains',
  millet: 'grains',
  polenta: 'grains',
  cornmeal: 'grains',
  granola: 'grains',
  muesli: 'grains',
  cereal: 'grains',
  noodle: 'grains',
  spaghetti: 'grains',
  tahini: 'grains',
  seed: 'grains',
  syrup: 'grains',
  sugar: 'grains',
  pistachio: 'grains',
  pecan: 'grains',
  hazelnut: 'grains',
  sesame: 'grains',
  cocoa: 'grains',
  // Audit F-SHOP-1-2: 18 of 80 lines landed in "Other" (steak, falafel,
  // stock, spices, olives, sweetcorn…). "grains" is the "Grains & Pantry"
  // aisle in both apps, so spices, jars and tins go there.
  steak: 'proteins',
  sirloin: 'proteins',
  mince: 'proteins',
  veal: 'proteins',
  venison: 'proteins',
  falafel: 'proteins',
  meatball: 'proteins',
  chorizo: 'proteins',
  salami: 'proteins',
  prosciutto: 'proteins',
  pancetta: 'proteins',
  crab: 'proteins',
  mussel: 'proteins',
  scallop: 'proteins',
  squid: 'proteins',
  haddock: 'proteins',
  halibut: 'proteins',
  tilapia: 'proteins',
  'sea bass': 'proteins',
  edamame: 'proteins',
  'protein powder': 'grains',
  'green bean': 'produce',
  'runner bean': 'produce',
  'broad bean': 'produce',
  'bean sprout': 'produce',
  artichoke: 'produce',
  sweetcorn: 'produce',
  corn: 'produce',
  rosemary: 'produce',
  thyme: 'produce',
  dill: 'produce',
  sage: 'produce',
  tarragon: 'produce',
  lemongrass: 'produce',
  greens: 'produce',
  salad: 'produce',
  romaine: 'produce',
  watercress: 'produce',
  chard: 'produce',
  'bok choy': 'produce',
  'pak choi': 'produce',
  okra: 'produce',
  parsnip: 'produce',
  turnip: 'produce',
  beet: 'produce',
  jalapeno: 'produce',
  jalapeño: 'produce',
  plum: 'produce',
  apricot: 'produce',
  fig: 'produce',
  kiwi: 'produce',
  pomegranate: 'produce',
  cherry: 'produce',
  date: 'produce',
  cumin: 'grains',
  paprika: 'grains',
  turmeric: 'grains',
  cinnamon: 'grains',
  nutmeg: 'grains',
  cardamom: 'grains',
  saffron: 'grains',
  oregano: 'grains',
  'bay leaf': 'grains',
  'bay leaves': 'grains',
  curry: 'grains',
  masala: 'grains',
  'ras el hanout': 'grains',
  "za'atar": 'grains',
  sumac: 'grains',
  allspice: 'grains',
  vanilla: 'grains',
  yeast: 'grains',
  cornstarch: 'grains',
  'corn starch': 'grains',
  olive: 'grains',
  caper: 'grains',
  pickle: 'grains',
  gherkin: 'grains',
  jam: 'grains',
  chocolate: 'grains',
  raisin: 'grains',
  ciabatta: 'grains',
  baguette: 'grains',
  bagel: 'grains',
  brioche: 'grains',
  sourdough: 'grains',
  crouton: 'grains',
  cracker: 'grains',
  'creme fraiche': 'dairy',
  'crème fraîche': 'dairy',
  mascarpone: 'dairy',
  skyr: 'dairy',
  quark: 'dairy',
  cottage: 'dairy',
};

// Words that turn any ingredient into a pantry product, whatever it is made
// of: "tomato paste", "vegetable stock", "garlic powder", "chili flakes",
// "balsamic glaze", "lemon vinaigrette". Checked on the LAST word before
// the keyword map, which would otherwise file them under their base food.
const PANTRY_HEADS = new Set([
  'stock',
  'broth',
  'bouillon',
  'sauce',
  'paste',
  'powder',
  'seasoning',
  'spice',
  'flake',
  'extract',
  'oil',
  'vinegar',
  'glaze',
  'vinaigrette',
  'dressing',
  'passata',
  'salsa',
  'seed',
  'syrup',
  'cube',
  'ketchup',
  'mayonnaise',
  'mustard',
]);

/** "flakes" → "flake"; enough for the head-word check. */
function lastWordSingular(name: string): string {
  const words = name
    .toLowerCase()
    .replace(/[^a-z\s-]/g, ' ')
    .trim()
    .split(/\s+/);
  const last = words[words.length - 1] ?? '';
  if (last.endsWith('ies')) return `${last.slice(0, -3)}y`;
  if (last.endsWith('s') && !last.endsWith('ss')) return last.slice(0, -1);
  return last;
}

// Longest keyword first so "pepperoni" wins over "pepper" when both match a
// candidate boundary (defence in depth on top of the word-boundary regex).
const MATCHERS: { pattern: RegExp; category: GroceryCategory }[] = Object.entries(CATEGORY_KEYWORDS)
  .sort(([a], [b]) => b.length - a.length)
  .map(([keyword, category]) => ({
    // Word-boundary match, not substring: the old `.includes()` sent
    // "pepperoni" to produce (via "pepper") and "coconut" everywhere "nut"
    // appeared. Plurals are tolerated including -es and y→ies — the old
    // bare `s?` missed "tomatoes" and "berries", which is how cherry
    // tomatoes ended up in "Other" (prod-followups #7).
    pattern: keyword.endsWith('y')
      ? new RegExp(String.raw`\b${keyword.slice(0, -1)}(?:y|ies)\b`, 'i')
      : new RegExp(String.raw`\b${keyword}(?:s|es)?\b`, 'i'),
    category,
  }));

export function inferCategory(ingredientName: string): GroceryCategory {
  if (/\bfrozen\b/i.test(ingredientName)) return 'frozen';
  if (/\b(canned|tinned|jarred|dried|sun-dried|sundried)\b/i.test(ingredientName)) return 'grains';
  if (PANTRY_HEADS.has(lastWordSingular(ingredientName))) return 'grains';
  for (const { pattern, category } of MATCHERS) {
    if (pattern.test(ingredientName)) return category;
  }
  return 'other';
}
