import type { GroceryCategory } from '../../lib/grocery-ai/types.js';

// ─── Ingredient → grocery category inference ──────────────────────────────────
// The single keyword map for categorising ingredients. It used to exist twice
// (here and a Title-Case copy in meal-plan.service) with diverging values, so
// the same ingredient could land in different aisles on different screens.

const CATEGORY_KEYWORDS: Record<string, GroceryCategory> = {
  tomato: 'produce',
  spinach: 'produce',
  onion: 'produce',
  garlic: 'produce',
  lemon: 'produce',
  lime: 'produce',
  avocado: 'produce',
  mushroom: 'produce',
  pepper: 'produce',
  lettuce: 'produce',
  cucumber: 'produce',
  zucchini: 'produce',
  carrot: 'produce',
  broccoli: 'produce',
  celery: 'produce',
  kale: 'produce',
  apple: 'produce',
  banana: 'produce',
  berry: 'produce',
  strawberry: 'produce',
  blueberry: 'produce',
  raspberry: 'produce',
  fruit: 'produce',
  shallot: 'produce',
  herb: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  coriander: 'produce',
  basil: 'produce',
  mint: 'produce',
  chive: 'produce',
  potato: 'produce',
  courgette: 'produce',
  aubergine: 'produce',
  eggplant: 'produce',
  cauliflower: 'produce',
  cabbage: 'produce',
  leek: 'produce',
  ginger: 'produce',
  // "chili powder" is a spice — must outrank the produce "chili" below
  'chili powder': 'other',
  chili: 'produce',
  chilli: 'produce',
  pea: 'produce',
  leaves: 'produce',
  rocket: 'produce',
  arugula: 'produce',
  squash: 'produce',
  pumpkin: 'produce',
  beetroot: 'produce',
  asparagus: 'produce',
  grape: 'produce',
  orange: 'produce',
  mango: 'produce',
  pineapple: 'produce',
  peach: 'produce',
  pear: 'produce',
  melon: 'produce',
  fennel: 'produce',
  radish: 'produce',
  scallion: 'produce',
  chicken: 'proteins',
  beef: 'proteins',
  salmon: 'proteins',
  tuna: 'proteins',
  egg: 'proteins',
  tofu: 'proteins',
  shrimp: 'proteins',
  turkey: 'proteins',
  pork: 'proteins',
  lamb: 'proteins',
  cod: 'proteins',
  fish: 'proteins',
  pepperoni: 'proteins',
  tempeh: 'proteins',
  seitan: 'proteins',
  prawn: 'proteins',
  sardine: 'proteins',
  anchovy: 'proteins',
  bacon: 'proteins',
  ham: 'proteins',
  sausage: 'proteins',
  duck: 'proteins',
  trout: 'proteins',
  mackerel: 'proteins',
  milk: 'dairy',
  cheese: 'dairy',
  yogurt: 'dairy',
  yoghurt: 'dairy',
  butter: 'dairy',
  cream: 'dairy',
  parmesan: 'dairy',
  mozzarella: 'dairy',
  feta: 'dairy',
  halloumi: 'dairy',
  paneer: 'dairy',
  ricotta: 'dairy',
  cheddar: 'dairy',
  ghee: 'dairy',
  kefir: 'dairy',
  rice: 'grains',
  pasta: 'grains',
  flour: 'grains',
  bread: 'grains',
  breadcrumb: 'grains',
  oat: 'grains',
  quinoa: 'grains',
  lentil: 'grains',
  bean: 'grains',
  oil: 'grains',
  vinegar: 'grains',
  soy: 'grains',
  honey: 'grains',
  almond: 'grains',
  walnut: 'grains',
  cashew: 'grains',
  nut: 'grains',
  // nut butters are pantry, not dairy — must outrank "butter"
  'peanut butter': 'grains',
  'almond butter': 'grains',
  peanut: 'grains',
  chickpea: 'grains',
  coconut: 'grains',
  tortilla: 'grains',
  wrap: 'grains',
  pita: 'grains',
  roti: 'grains',
  naan: 'grains',
  couscous: 'grains',
  barley: 'grains',
  buckwheat: 'grains',
  bulgur: 'grains',
  millet: 'grains',
  polenta: 'grains',
  cornmeal: 'grains',
  granola: 'grains',
  muesli: 'grains',
  cereal: 'grains',
  noodle: 'grains',
  spaghetti: 'grains',
  tahini: 'grains',
  seed: 'grains',
  syrup: 'grains',
  sugar: 'grains',
  pistachio: 'grains',
  pecan: 'grains',
  hazelnut: 'grains',
  sesame: 'grains',
  cocoa: 'grains',
};

// Longest keyword first so "pepperoni" wins over "pepper" when both match a
// candidate boundary (defence in depth on top of the word-boundary regex).
const MATCHERS: { pattern: RegExp; category: GroceryCategory }[] = Object.entries(CATEGORY_KEYWORDS)
  .sort(([a], [b]) => b.length - a.length)
  .map(([keyword, category]) => ({
    // Word-boundary match, not substring: the old `.includes()` sent
    // "pepperoni" to produce (via "pepper") and "coconut" everywhere "nut"
    // appeared. Plurals are tolerated including -es and y→ies — the old
    // bare `s?` missed "tomatoes" and "berries", which is how cherry
    // tomatoes ended up in "Other" (prod-followups #7).
    pattern: keyword.endsWith('y')
      ? new RegExp(String.raw`\b${keyword.slice(0, -1)}(?:y|ies)\b`, 'i')
      : new RegExp(String.raw`\b${keyword}(?:s|es)?\b`, 'i'),
    category,
  }));

export function inferCategory(ingredientName: string): GroceryCategory {
  for (const { pattern, category } of MATCHERS) {
    if (pattern.test(ingredientName)) return category;
  }
  return 'other';
}
