export { prisma, type PrismaClient } from './client';
export {
  UserRepository,
  userRepository,
  type IUserRepository,
  type FindManyOptions,
  type CreateUserData,
  type UpdateUserData,
  ChefProfileRepository,
  chefProfileRepository,
  type IChefProfileRepository,
  type UpsertChefProfileData,
  type ActivityLevel,
  type Goal,
  DietaryPreferencesRepository,
  dietaryPreferencesRepository,
  type IDietaryPreferencesRepository,
  type UpsertDietaryPreferencesData,
  MealPlanRepository,
  mealPlanRepository,
  type IMealPlanRepository,
  type CreateRecipeData,
  type CreateMealPlanData,
  type PlanMealSlotJson,
  // Instant week, then live tailoring (premium)
  MealPlanTailoringRepository,
  mealPlanTailoringRepository,
  stableSlotsJson,
  type IMealPlanTailoringRepository,
  type CreateTailoringData,
  type TailoringProgressPatch,
  type TailoringSnapshots,
  type TailoringUserGate,
  FavouriteRecipeRepository,
  favouriteRecipeRepository,
  type IFavouriteRecipeRepository,
  type FavouriteRecipeWithRecipe,
  type CreateManualRecipeData,
  MealRatingRepository,
  mealRatingRepository,
  type IMealRatingRepository,
  DailyLogRepository,
  dailyLogRepository,
  type IDailyLogRepository,
  type LoggedMealEntry,
  type UpsertDailyLogData,
  WeightEntryRepository,
  weightEntryRepository,
  type IWeightEntryRepository,
  type CreateWeightEntryData,
  ChefReviewRepository,
  chefReviewRepository,
  type IChefReviewRepository,
  type UpsertChefReviewData,
  HouseholdMemberRepository,
  householdMemberRepository,
  type IHouseholdMemberRepository,
  type CreateHouseholdMemberData,
  type UpdateHouseholdMemberData,
  PantryItemRepository,
  pantryItemRepository,
  type IPantryItemRepository,
  type UpsertPantryItemData,
  FeedbackRepository,
  feedbackRepository,
  type IFeedbackRepository,
  type CreateFeedbackData,
  // Gym (gym_plan.md §4.1)
  ExerciseRepository,
  exerciseRepository,
  type IExerciseRepository,
  type ExerciseWriteData,
  type CuratedExerciseUpdate,
  GymProfileRepository,
  gymProfileRepository,
  type IGymProfileRepository,
  type GymProfileWriteData,
  type GymProfileUpdateData,
  type InitialProgressionData,
  type CompleteSetupData,
  RoutineRepository,
  routineRepository,
  type IRoutineRepository,
  type RoutineWithDays,
  type RoutineDayWithExercises,
  type RoutineCreateData,
  type RoutineDayWriteData,
  type RoutineExerciseWriteData,
  type RoutineListRow,
  type ReplaceRoutineResult,
  WorkoutSessionRepository,
  workoutSessionRepository,
  type IWorkoutSessionRepository,
  type SessionWithChildren,
  type SessionExerciseWithSets,
  type SessionDocWriteData,
  type SessionExerciseWriteData,
  type SessionSetWriteData,
  type StoredSessionSnapshot,
  type UpsertSessionResult,
  type UpsertSessionOptions,
  type SessionCursor,
  ExerciseProgressionRepository,
  exerciseProgressionRepository,
  type IExerciseProgressionRepository,
  type ProgressionStateWrite,
  TrainingPauseRepository,
  trainingPauseRepository,
  type ITrainingPauseRepository,
  type CreateTrainingPauseData,
  // Weekly emails (audit P2-5)
  WeeklyEmailRepository,
  weeklyEmailRepository,
  type IWeeklyEmailRepository,
  type WeeklyEmailKind,
  type WeeklyEmailRecipient,
  type WeeklyEmailPreferences,
  type WeekLogRow,
  // Wave-0 schema contracts (T-00.10)
  SafetyReportRepository,
  safetyReportRepository,
  type ISafetyReportRepository,
  type CreateSafetyReportData,
  TargetChangeRepository,
  targetChangeRepository,
  type ITargetChangeRepository,
  type CreateTargetChangeData,
  IngredientPriceRepository,
  ingredientPriceRepository,
  type IIngredientPriceRepository,
  type IngredientCatalogRow,
  ConsentEventRepository,
  consentEventRepository,
  type IConsentEventRepository,
  type RecordConsentEventData,
  // Following (docs/friends/implementation-plan.md §2.4)
  SocialProfileRepository,
  socialProfileRepository,
  socialUserSelect,
  type ISocialProfileRepository,
  type SocialDbClient,
  type SocialKeysetCursor,
  type SocialUserRow,
  type SocialProfileWithUser,
  type SocialSearchCursor,
  type PopularProfileRow,
  type CreateSocialProfileData,
  type UpdateSocialProfileData,
  type DeleteCascadeSocialResult,
  FollowRepository,
  followRepository,
  type IFollowRepository,
  type CreateFollowData,
  type FollowPair,
  type FollowCounts,
  type MutualCandidateRow,
  type ExpiredFollowRequest,
  BlockRepository,
  blockRepository,
  type IBlockRepository,
  SuggestionDismissalRepository,
  suggestionDismissalRepository,
  type ISuggestionDismissalRepository,
  UserReportRepository,
  userReportRepository,
  type IUserReportRepository,
  type CreateUserReportData,
  type ReportCountsSince,
  ModerationRepository,
  moderationRepository,
  type IModerationRepository,
  type ModerationLogEntry,
  type ModerationWeeklyCounts,
  type FilterableRecipeRow,
  NotificationRepository,
  notificationRepository,
  type INotificationRepository,
  type SocialNotificationData,
  FriendRecipeRepository,
  friendRecipeRepository,
  type IFriendRecipeRepository,
  type ListSharedRecipesOptions,
} from './repositories/index';

// Ingredient catalog validators (docs/plan-ingredient-catalog.md §4.5) — pure, no I/O
export {
  validateCatalog,
  validateEntry,
  summarizeIssues,
  normalizeAlias,
  energyCheck,
  euEnergyKcal,
  ENERGY_ALLOW_LIST,
  CATALOG_CATEGORIES,
  NUTRITION_SOURCES,
  VOLUME_UNITS,
  COUNT_PORTION_UNITS,
  COUNT_PORTION_CATEGORIES,
  DENSITY_CATEGORIES,
  DENSITY_SLUG_PATTERN,
  type CatalogEntry,
  type CatalogAlias,
  type CatalogPortion,
  type CatalogCategory,
  type CatalogNutritionSource,
  type CountPortionUnit,
  type ValidationIssue,
  type ValidationRule,
  type ValidationSeverity,
  type ValidateOptions,
} from './catalog/index';

// Re-export Prisma types for convenience
export type {
  User,
  Account,
  Session,
  Post,
  Tag,
  PostTag,
  UserProfile,
  ChefProfile,
  DietaryPreferences,
  Recipe,
  MealPlan,
  MealPlanDay,
  MealPlanTailoring,
  FavouriteRecipe,
  MealRating,
  DailyLog,
  WeightEntry,
  ChefReview,
  HouseholdMember,
  PantryItem,
  IngredientPrice,
  ShoppingList,
  Exercise,
  GymProfile,
  Routine,
  RoutineDay,
  RoutineExercise,
  WorkoutSession,
  SessionExercise,
  SessionSet,
  ExerciseProgression,
  TrainingPause,
  EmailSend,
  // Wave-0 schema contracts (T-00.10)
  SafetyReport,
  TargetChange,
  ConsentEvent,
  // Following (docs/friends/implementation-plan.md §2.2)
  SocialProfile,
  Follow,
  Block,
  SuggestionDismissal,
  UserReport,
  ModerationLog,
  Notification,
} from '@prisma/client';
export {
  AiCallType,
  UserRole,
  PostStatus,
  Prisma,
  BiologicalSex,
  MealPlanStatus,
  MealPlanOrigin,
  MealPlanTailoringStatus,
  ImageStatus,
  OnboardingIntent,
  OnboardingJob,
  TargetMode,
  TargetChangeKind,
  ConsentKind,
  // Following (docs/friends/implementation-plan.md §2.1)
  ProfileVisibility,
  FollowStatus,
  NotificationKind,
  ReportReason,
  RecipeHiddenReason,
  ModerationAction,
} from '@prisma/client';
