export { prisma, type PrismaClient } from './client';
export {
  UserRepository,
  userRepository,
  type IUserRepository,
  type FindManyOptions,
  type CreateUserData,
  type UpdateUserData,
  ChefProfileRepository,
  chefProfileRepository,
  type IChefProfileRepository,
  type UpsertChefProfileData,
  type ActivityLevel,
  type BiologicalSex,
  type Goal,
  DietaryPreferencesRepository,
  dietaryPreferencesRepository,
  type IDietaryPreferencesRepository,
  type UpsertDietaryPreferencesData,
  MealPlanRepository,
  mealPlanRepository,
  type IMealPlanRepository,
  type CreateRecipeData,
  type CreateMealPlanData,
  FavouriteRecipeRepository,
  favouriteRecipeRepository,
  type IFavouriteRecipeRepository,
  type FavouriteRecipeWithRecipe,
} from './repositories/index';

// Re-export Prisma types for convenience
export type {
  User,
  Account,
  Session,
  Post,
  Tag,
  PostTag,
  UserProfile,
  ChefProfile,
  DietaryPreferences,
  Recipe,
  MealPlan,
  MealPlanDay,
  FavouriteRecipe,
} from '@prisma/client';
export { UserRole, PostStatus, Prisma, BiologicalSex, MealPlanStatus } from '@prisma/client';
