export { prisma, type PrismaClient } from './client';
export {
  UserRepository,
  userRepository,
  type IUserRepository,
  type FindManyOptions,
  type CreateUserData,
  type UpdateUserData,
  ChefProfileRepository,
  chefProfileRepository,
  type IChefProfileRepository,
  type UpsertChefProfileData,
  type ActivityLevel,
  type Goal,
  DietaryPreferencesRepository,
  dietaryPreferencesRepository,
  type IDietaryPreferencesRepository,
  type UpsertDietaryPreferencesData,
  MealPlanRepository,
  mealPlanRepository,
  type IMealPlanRepository,
  type CreateRecipeData,
  type CreateMealPlanData,
  FavouriteRecipeRepository,
  favouriteRecipeRepository,
  type IFavouriteRecipeRepository,
  type FavouriteRecipeWithRecipe,
  type CreateManualRecipeData,
  MealRatingRepository,
  mealRatingRepository,
  type IMealRatingRepository,
  DailyLogRepository,
  dailyLogRepository,
  type IDailyLogRepository,
  type LoggedMealEntry,
  type UpsertDailyLogData,
  WeightEntryRepository,
  weightEntryRepository,
  type IWeightEntryRepository,
  type CreateWeightEntryData,
} from './repositories/index';

// Re-export Prisma types for convenience
export type {
  User,
  Account,
  Session,
  Post,
  Tag,
  PostTag,
  UserProfile,
  ChefProfile,
  DietaryPreferences,
  Recipe,
  MealPlan,
  MealPlanDay,
  FavouriteRecipe,
  MealRating,
  DailyLog,
  WeightEntry,
  IngredientPrice,
  ShoppingList,
} from '@prisma/client';
export {
  AiCallType,
  UserRole,
  PostStatus,
  Prisma,
  BiologicalSex,
  MealPlanStatus,
  ImageStatus,
} from '@prisma/client';
