import type { RecipeData } from '../ai/types.js';
import { buildPollinationsUrl } from '../image-gen/pollinations.js';
import { buildRecipeImagePrompt } from '../image-gen/prompt.js';

// ─── Curated pool expansion (P1-2) ────────────────────────────────────────────
// 42 additional generic recipes so the free tier survives safety filtering:
// every meal type keeps ≥3 compliant options for each of the common
// restrictions (vegan, vegetarian, pescatarian, gluten-free, dairy-free) and
// for the major allergens (nuts, dairy, eggs, gluten). dietaryTags here are
// load-bearing — the safety filter requires them AND cross-checks ingredient
// names, so tag a recipe only when its ingredient list genuinely complies.
//
// Images are deterministic Pollinations URLs (seeded from name + cuisine, CDN
// cached after first render) — same pipeline premium images use, no auth.

const img = (name: string, cuisine: string) =>
  buildPollinationsUrl(buildRecipeImagePrompt(name, cuisine), name, cuisine);

type R = Omit<RecipeData, 'imageUrl'> & { imageUrl?: string };

const withImage = (r: R): RecipeData => ({ ...r, imageUrl: img(r.name, r.cuisineType) });

// ── Breakfasts ────────────────────────────────────────────────────────────────

export const EXTRA_BREAKFAST_POOL: RecipeData[] = (
  [
    {
      id: 'cur-b-101',
      name: 'Tofu Scramble with Peppers',
      description:
        'Golden turmeric-spiced tofu scrambled with red peppers and spring onions. A savoury plant-based start with plenty of protein.',
      ingredients: [
        { name: 'firm tofu', quantity: 200, unit: 'g' },
        { name: 'red pepper', quantity: 80, unit: 'g' },
        { name: 'spring onions', quantity: 2, unit: 'pieces' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
        { name: 'salt and black pepper', quantity: 1, unit: 'to taste' },
      ],
      instructions: [
        'Drain and pat the tofu dry, then crumble it with a fork.',
        'Heat the oil in a pan and soften the pepper and spring onions for 3 minutes.',
        'Add the tofu and turmeric; cook for 5 minutes, stirring.',
        'Season and serve hot.',
      ],
      nutritionInfo: { calories: 350, protein: 24, carbs: 12, fat: 22, fiber: 4 },
      cuisineType: 'American',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 10,
      servings: 1,
    },
    {
      id: 'cur-b-102',
      name: 'Chia Pudding with Mango and Coconut',
      description:
        'Chia seeds soaked overnight in coconut milk, topped with fresh mango and toasted coconut flakes.',
      ingredients: [
        { name: 'chia seeds', quantity: 40, unit: 'g' },
        { name: 'coconut milk', quantity: 200, unit: 'ml' },
        { name: 'mango', quantity: 100, unit: 'g' },
        { name: 'coconut flakes', quantity: 10, unit: 'g' },
        { name: 'maple syrup', quantity: 10, unit: 'ml' },
      ],
      instructions: [
        'Stir chia seeds, coconut milk, and maple syrup in a jar.',
        'Refrigerate overnight (at least 4 hours).',
        'Top with diced mango and coconut flakes before serving.',
      ],
      nutritionInfo: { calories: 420, protein: 10, carbs: 42, fat: 24, fiber: 14 },
      cuisineType: 'Tropical',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 5,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-b-103',
      name: 'Berry Banana Smoothie Bowl',
      description:
        'Thick blended smoothie bowl of frozen berries, banana and soy milk, finished with fresh fruit and pumpkin seeds.',
      ingredients: [
        { name: 'frozen mixed berries', quantity: 150, unit: 'g' },
        { name: 'banana', quantity: 1, unit: 'medium' },
        { name: 'soy milk', quantity: 150, unit: 'ml' },
        { name: 'pumpkin seeds', quantity: 10, unit: 'g' },
        { name: 'fresh strawberries', quantity: 50, unit: 'g' },
      ],
      instructions: [
        'Blend the frozen berries, banana, and soy milk until thick and smooth.',
        'Pour into a bowl.',
        'Top with sliced strawberries and pumpkin seeds.',
      ],
      nutritionInfo: { calories: 360, protein: 12, carbs: 62, fat: 8, fiber: 10 },
      cuisineType: 'American',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-b-104',
      name: 'Buckwheat Porridge with Berries',
      description:
        'Warm buckwheat groats simmered with cinnamon and rice milk, topped with blueberries.',
      ingredients: [
        { name: 'buckwheat groats', quantity: 70, unit: 'g' },
        { name: 'rice milk', quantity: 250, unit: 'ml' },
        { name: 'blueberries', quantity: 80, unit: 'g' },
        { name: 'cinnamon', quantity: 0.5, unit: 'tsp' },
        { name: 'maple syrup', quantity: 10, unit: 'ml' },
      ],
      instructions: [
        'Rinse the buckwheat and simmer in rice milk for 12–15 minutes until tender.',
        'Stir in cinnamon and maple syrup.',
        'Serve topped with blueberries.',
      ],
      nutritionInfo: { calories: 390, protein: 10, carbs: 78, fat: 4, fiber: 7 },
      cuisineType: 'European',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
      prepTimeMins: 5,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-b-105',
      name: 'Scrambled Eggs on Rye Toast',
      description: 'Soft scrambled eggs with chives on dark rye toast.',
      ingredients: [
        { name: 'eggs', quantity: 3, unit: 'large' },
        { name: 'rye bread', quantity: 2, unit: 'slices' },
        { name: 'chives', quantity: 5, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tsp' },
        { name: 'salt and black pepper', quantity: 1, unit: 'to taste' },
      ],
      instructions: [
        'Toast the rye bread.',
        'Whisk the eggs with salt and pepper.',
        'Scramble gently in oil over low heat until just set.',
        'Pile onto the toast and finish with snipped chives.',
      ],
      nutritionInfo: { calories: 400, protein: 23, carbs: 32, fat: 19, fiber: 4 },
      cuisineType: 'European',
      dietaryTags: ['vegetarian', 'dairy-free'],
      prepTimeMins: 5,
      cookTimeMins: 8,
      servings: 1,
    },
    {
      id: 'cur-b-106',
      name: 'Cottage Cheese Pancakes with Berries',
      description:
        'Fluffy high-protein pancakes made with cottage cheese, served with raspberries.',
      ingredients: [
        { name: 'cottage cheese', quantity: 120, unit: 'g' },
        { name: 'eggs', quantity: 2, unit: 'large' },
        { name: 'plain flour', quantity: 50, unit: 'g' },
        { name: 'raspberries', quantity: 80, unit: 'g' },
        { name: 'honey', quantity: 10, unit: 'ml' },
      ],
      instructions: [
        'Whisk cottage cheese, eggs, and flour into a thick batter.',
        'Fry small pancakes over medium heat, 2 minutes per side.',
        'Serve with raspberries and a drizzle of honey.',
      ],
      nutritionInfo: { calories: 430, protein: 30, carbs: 48, fat: 12, fiber: 5 },
      cuisineType: 'European',
      dietaryTags: ['vegetarian', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 10,
      servings: 1,
    },
    {
      id: 'cur-b-107',
      name: 'Shakshuka with Peppers',
      description:
        'Eggs poached in a spiced tomato and red pepper sauce — a warming North African classic.',
      ingredients: [
        { name: 'eggs', quantity: 2, unit: 'large' },
        { name: 'canned tomatoes', quantity: 250, unit: 'g' },
        { name: 'red pepper', quantity: 100, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'cumin', quantity: 1, unit: 'tsp' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Soften the onion and pepper in oil, then add spices.',
        'Pour in the tomatoes and simmer for 10 minutes.',
        'Make two wells, crack in the eggs, cover, and poach for 6 minutes.',
        'Serve straight from the pan.',
      ],
      nutritionInfo: { calories: 380, protein: 18, carbs: 24, fat: 24, fiber: 6 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-b-108',
      name: 'Ham and Cheese Breakfast Sandwich',
      description: 'Toasted wholegrain sandwich with ham, cheddar, tomato and rocket.',
      ingredients: [
        { name: 'wholegrain bread', quantity: 2, unit: 'slices' },
        { name: 'ham', quantity: 60, unit: 'g' },
        { name: 'cheddar cheese', quantity: 30, unit: 'g' },
        { name: 'tomato', quantity: 0.5, unit: 'medium' },
        { name: 'rocket', quantity: 20, unit: 'g' },
      ],
      instructions: [
        'Toast the bread lightly.',
        'Layer ham, cheddar, sliced tomato, and rocket.',
        'Press and toast in a dry pan for 2 minutes per side until the cheese melts.',
      ],
      nutritionInfo: { calories: 420, protein: 26, carbs: 36, fat: 18, fiber: 5 },
      cuisineType: 'American',
      dietaryTags: ['high-protein'],
      prepTimeMins: 5,
      cookTimeMins: 5,
      servings: 1,
    },
    {
      id: 'cur-b-109',
      name: 'Vanilla Protein Shake with Strawberries',
      description: 'Quick blended shake of whey protein, strawberries and semi-skimmed milk.',
      ingredients: [
        { name: 'vanilla whey protein powder', quantity: 30, unit: 'g' },
        { name: 'strawberries', quantity: 120, unit: 'g' },
        { name: 'semi-skimmed milk', quantity: 250, unit: 'ml' },
        { name: 'ice cubes', quantity: 4, unit: 'pieces' },
      ],
      instructions: ['Blend everything until smooth.', 'Serve cold.'],
      nutritionInfo: { calories: 310, protein: 34, carbs: 28, fat: 6, fiber: 3 },
      cuisineType: 'American',
      dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'],
      prepTimeMins: 5,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-b-110',
      name: 'Fruit Salad with Coconut Yogurt',
      description: 'Fresh melon, kiwi, and orange with a scoop of coconut yogurt and mint.',
      ingredients: [
        { name: 'melon', quantity: 150, unit: 'g' },
        { name: 'kiwi', quantity: 1, unit: 'medium' },
        { name: 'orange', quantity: 1, unit: 'medium' },
        { name: 'coconut yogurt', quantity: 120, unit: 'g' },
        { name: 'fresh mint', quantity: 3, unit: 'g' },
      ],
      instructions: [
        'Chop the fruit into bite-sized pieces.',
        'Spoon the coconut yogurt on top.',
        'Finish with torn mint leaves.',
      ],
      nutritionInfo: { calories: 330, protein: 6, carbs: 52, fat: 12, fiber: 8 },
      cuisineType: 'Tropical',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
      prepTimeMins: 10,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-b-111',
      name: 'Sweet Potato Hash with Fried Eggs',
      description: 'Crispy sweet potato and onion hash topped with two fried eggs.',
      ingredients: [
        { name: 'sweet potato', quantity: 200, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'eggs', quantity: 2, unit: 'large' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
        { name: 'smoked paprika', quantity: 0.5, unit: 'tsp' },
      ],
      instructions: [
        'Dice the sweet potato small and fry in oil for 10 minutes until crisp.',
        'Add the onion and paprika; cook 5 more minutes.',
        'Fry the eggs and slide on top of the hash.',
      ],
      nutritionInfo: { calories: 440, protein: 17, carbs: 46, fat: 21, fiber: 7 },
      cuisineType: 'American',
      dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free'],
      prepTimeMins: 10,
      cookTimeMins: 18,
      servings: 1,
    },
    {
      id: 'cur-b-112',
      name: 'Turkey Sausage and Spinach Frittata',
      description: 'Oven-baked frittata with lean turkey sausage, spinach, and cherry tomatoes.',
      ingredients: [
        { name: 'eggs', quantity: 3, unit: 'large' },
        { name: 'turkey sausage', quantity: 80, unit: 'g' },
        { name: 'baby spinach', quantity: 50, unit: 'g' },
        { name: 'cherry tomatoes', quantity: 60, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tsp' },
      ],
      instructions: [
        'Brown the sliced sausage in an ovenproof pan.',
        'Add spinach until wilted, then pour over the beaten eggs.',
        'Add halved tomatoes and bake at 180°C for 12 minutes until set.',
      ],
      nutritionInfo: { calories: 410, protein: 32, carbs: 8, fat: 28, fiber: 2 },
      cuisineType: 'Italian',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein', 'keto'],
      prepTimeMins: 10,
      cookTimeMins: 18,
      servings: 1,
    },
  ] as R[]
).map(withImage);

// ── Lunches ───────────────────────────────────────────────────────────────────

export const EXTRA_LUNCH_POOL: RecipeData[] = (
  [
    {
      id: 'cur-l-101',
      name: 'Chickpea and Avocado Salad Bowl',
      description:
        'Chickpeas, avocado, cucumber and cherry tomatoes over leaves with a lemon-olive oil dressing.',
      ingredients: [
        { name: 'canned chickpeas', quantity: 150, unit: 'g' },
        { name: 'avocado', quantity: 0.5, unit: 'medium' },
        { name: 'cucumber', quantity: 100, unit: 'g' },
        { name: 'cherry tomatoes', quantity: 100, unit: 'g' },
        { name: 'mixed leaves', quantity: 60, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Rinse and drain the chickpeas.',
        'Chop the vegetables and toss everything with oil and lemon.',
        'Season and serve.',
      ],
      nutritionInfo: { calories: 480, protein: 15, carbs: 42, fat: 28, fiber: 14 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-l-102',
      name: 'Tomato Basil Soup with Grilled Cheese',
      description: 'Silky tomato-basil soup with a golden grilled cheddar sandwich for dunking.',
      ingredients: [
        { name: 'canned tomatoes', quantity: 400, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'fresh basil', quantity: 10, unit: 'g' },
        { name: 'wholegrain bread', quantity: 2, unit: 'slices' },
        { name: 'cheddar cheese', quantity: 40, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Soften the onion in oil, add tomatoes, and simmer 15 minutes.',
        'Blend with the basil until smooth.',
        'Grill the cheese sandwich until golden and serve alongside.',
      ],
      nutritionInfo: { calories: 540, protein: 20, carbs: 52, fat: 28, fiber: 8 },
      cuisineType: 'American',
      dietaryTags: ['vegetarian'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-l-103',
      name: 'Falafel Pita with Tzatziki',
      description: 'Warm pita stuffed with falafel, salad, and cooling cucumber tzatziki.',
      ingredients: [
        { name: 'falafel', quantity: 4, unit: 'pieces' },
        { name: 'pita bread', quantity: 1, unit: 'piece' },
        { name: 'tzatziki', quantity: 60, unit: 'g' },
        { name: 'tomato', quantity: 0.5, unit: 'medium' },
        { name: 'cucumber', quantity: 50, unit: 'g' },
        { name: 'red onion', quantity: 20, unit: 'g' },
      ],
      instructions: [
        'Warm the pita and the falafel.',
        'Split the pita and fill with falafel and chopped salad.',
        'Spoon in the tzatziki.',
      ],
      nutritionInfo: { calories: 520, protein: 18, carbs: 62, fat: 22, fiber: 9 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegetarian'],
      prepTimeMins: 10,
      cookTimeMins: 5,
      servings: 1,
    },
    {
      id: 'cur-l-104',
      name: 'Rice Noodle Veggie Stir-Fry',
      description: 'Rice noodles tossed with crisp vegetables in a ginger-garlic soy sauce.',
      ingredients: [
        { name: 'rice noodles', quantity: 80, unit: 'g' },
        { name: 'broccoli', quantity: 100, unit: 'g' },
        { name: 'carrot', quantity: 80, unit: 'g' },
        { name: 'red pepper', quantity: 80, unit: 'g' },
        { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
        { name: 'fresh ginger', quantity: 10, unit: 'g' },
        { name: 'garlic', quantity: 2, unit: 'cloves' },
        { name: 'sesame oil', quantity: 1, unit: 'tsp' },
      ],
      instructions: [
        'Soak the rice noodles per the packet.',
        'Stir-fry the vegetables with ginger and garlic over high heat.',
        'Add the noodles and soy sauce; toss for 2 minutes and finish with sesame oil.',
      ],
      nutritionInfo: { calories: 470, protein: 12, carbs: 82, fat: 11, fiber: 8 },
      cuisineType: 'Asian',
      dietaryTags: ['vegan', 'dairy-free'],
      prepTimeMins: 10,
      cookTimeMins: 10,
      servings: 1,
    },
    {
      id: 'cur-l-105',
      name: 'Stuffed Bell Peppers with Rice and Beans',
      description: 'Roasted peppers filled with herbed rice, black beans and sweetcorn.',
      ingredients: [
        { name: 'bell peppers', quantity: 2, unit: 'pieces' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'canned black beans', quantity: 100, unit: 'g' },
        { name: 'sweetcorn', quantity: 60, unit: 'g' },
        { name: 'tomato passata', quantity: 100, unit: 'ml' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Halve and deseed the peppers.',
        'Mix rice, beans, corn, and passata; stuff the peppers.',
        'Drizzle with oil and bake at 190°C for 25 minutes.',
      ],
      nutritionInfo: { calories: 490, protein: 14, carbs: 78, fat: 13, fiber: 12 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 15,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-l-106',
      name: 'Grilled Chicken and Quinoa Bowl',
      description: 'Char-grilled chicken breast over quinoa with roasted courgette and lemon.',
      ingredients: [
        { name: 'chicken breast', quantity: 150, unit: 'g' },
        { name: 'quinoa', quantity: 70, unit: 'g' },
        { name: 'courgette', quantity: 100, unit: 'g' },
        { name: 'lemon', quantity: 0.5, unit: 'piece' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Cook the quinoa in salted water.',
        'Grill the chicken and courgette slices.',
        'Assemble and dress with lemon juice and oil.',
      ],
      nutritionInfo: { calories: 560, protein: 45, carbs: 52, fat: 18, fiber: 7 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-l-107',
      name: 'Beef Burrito Bowl',
      description: 'Seasoned lean beef over rice with black beans, salsa, and avocado.',
      ingredients: [
        { name: 'lean beef mince', quantity: 130, unit: 'g' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'canned black beans', quantity: 80, unit: 'g' },
        { name: 'tomato salsa', quantity: 60, unit: 'g' },
        { name: 'avocado', quantity: 0.5, unit: 'medium' },
        { name: 'cumin', quantity: 1, unit: 'tsp' },
      ],
      instructions: [
        'Brown the beef with cumin and a pinch of salt.',
        'Layer rice, beans, beef, salsa, and sliced avocado in a bowl.',
      ],
      nutritionInfo: { calories: 620, protein: 38, carbs: 62, fat: 24, fiber: 11 },
      cuisineType: 'Mexican',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 12,
      servings: 1,
    },
    {
      id: 'cur-l-108',
      name: 'Caprese Sandwich on Ciabatta',
      description: 'Mozzarella, tomato and basil on ciabatta with balsamic glaze.',
      ingredients: [
        { name: 'ciabatta roll', quantity: 1, unit: 'piece' },
        { name: 'mozzarella', quantity: 80, unit: 'g' },
        { name: 'tomato', quantity: 1, unit: 'medium' },
        { name: 'fresh basil', quantity: 8, unit: 'g' },
        { name: 'balsamic glaze', quantity: 1, unit: 'tbsp' },
        { name: 'olive oil', quantity: 1, unit: 'tsp' },
      ],
      instructions: [
        'Split and lightly toast the ciabatta.',
        'Layer sliced mozzarella, tomato, and basil.',
        'Finish with balsamic glaze and olive oil.',
      ],
      nutritionInfo: { calories: 520, protein: 24, carbs: 48, fat: 26, fiber: 4 },
      cuisineType: 'Italian',
      dietaryTags: ['vegetarian'],
      prepTimeMins: 8,
      cookTimeMins: 2,
      servings: 1,
    },
    {
      id: 'cur-l-109',
      name: 'Miso Soup with Rice and Edamame',
      description: 'Umami miso broth with wakame, tofu, and edamame beans over steamed rice.',
      ingredients: [
        { name: 'miso paste', quantity: 20, unit: 'g' },
        { name: 'silken tofu', quantity: 100, unit: 'g' },
        { name: 'edamame beans', quantity: 80, unit: 'g' },
        { name: 'wakame seaweed', quantity: 3, unit: 'g' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'spring onions', quantity: 1, unit: 'piece' },
      ],
      instructions: [
        'Dissolve the miso in 400 ml of hot (not boiling) water.',
        'Add cubed tofu, edamame, and wakame; warm through gently.',
        'Serve with the rice and sliced spring onion.',
      ],
      nutritionInfo: { calories: 450, protein: 22, carbs: 66, fat: 10, fiber: 7 },
      cuisineType: 'Japanese',
      dietaryTags: ['vegan', 'dairy-free'],
      prepTimeMins: 5,
      cookTimeMins: 10,
      servings: 1,
    },
    {
      id: 'cur-l-110',
      name: 'Sweet Potato and Black Bean Chili',
      description: 'Smoky one-pot chili of sweet potato, black beans and tomatoes.',
      ingredients: [
        { name: 'sweet potato', quantity: 200, unit: 'g' },
        { name: 'canned black beans', quantity: 150, unit: 'g' },
        { name: 'canned tomatoes', quantity: 200, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'chili powder', quantity: 1, unit: 'tsp' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Soften the onion in oil with the spices.',
        'Add diced sweet potato, beans, and tomatoes.',
        'Simmer for 25 minutes until the potato is tender.',
      ],
      nutritionInfo: { calories: 510, protein: 16, carbs: 84, fat: 12, fiber: 18 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-l-111',
      name: 'Salmon Poke Bowl',
      description: 'Cubed salmon over sushi rice with cucumber, radish, and soy-lime dressing.',
      ingredients: [
        { name: 'sushi-grade salmon', quantity: 120, unit: 'g' },
        { name: 'cooked sushi rice', quantity: 150, unit: 'g' },
        { name: 'cucumber', quantity: 80, unit: 'g' },
        { name: 'radishes', quantity: 40, unit: 'g' },
        { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp' },
        { name: 'spring onions', quantity: 1, unit: 'piece' },
      ],
      instructions: [
        'Cube the salmon and toss with soy and lime.',
        'Arrange over the rice with sliced cucumber and radish.',
        'Top with spring onion.',
      ],
      nutritionInfo: { calories: 540, protein: 34, carbs: 62, fat: 16, fiber: 3 },
      cuisineType: 'Hawaiian',
      dietaryTags: ['pescatarian', 'dairy-free', 'high-protein'],
      prepTimeMins: 15,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-l-112',
      name: 'Greek Salad with Grilled Halloumi',
      description: 'Classic Greek salad with olives and warm griddled halloumi.',
      ingredients: [
        { name: 'halloumi', quantity: 80, unit: 'g' },
        { name: 'tomato', quantity: 1, unit: 'medium' },
        { name: 'cucumber', quantity: 100, unit: 'g' },
        { name: 'red onion', quantity: 30, unit: 'g' },
        { name: 'olives', quantity: 40, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
        { name: 'dried oregano', quantity: 0.5, unit: 'tsp' },
      ],
      instructions: [
        'Chop the vegetables and toss with olives, oil, and oregano.',
        'Griddle the halloumi slices until golden.',
        'Lay the halloumi over the salad and serve warm.',
      ],
      nutritionInfo: { calories: 480, protein: 22, carbs: 14, fat: 38, fiber: 4 },
      cuisineType: 'Greek',
      dietaryTags: ['vegetarian', 'gluten-free', 'keto'],
      prepTimeMins: 10,
      cookTimeMins: 6,
      servings: 1,
    },
  ] as R[]
).map(withImage);

// ── Dinners ───────────────────────────────────────────────────────────────────

export const EXTRA_DINNER_POOL: RecipeData[] = (
  [
    {
      id: 'cur-d-101',
      name: 'Chickpea Coconut Curry with Rice',
      description: 'Creamy coconut chickpea curry with spinach, served over basmati rice.',
      ingredients: [
        { name: 'canned chickpeas', quantity: 200, unit: 'g' },
        { name: 'coconut milk', quantity: 200, unit: 'ml' },
        { name: 'baby spinach', quantity: 60, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'curry powder', quantity: 1.5, unit: 'tsp' },
        { name: 'basmati rice', quantity: 70, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Cook the rice.',
        'Soften the onion in oil, add curry powder, then chickpeas and coconut milk.',
        'Simmer 12 minutes; stir in the spinach until wilted.',
        'Serve over the rice.',
      ],
      nutritionInfo: { calories: 680, protein: 19, carbs: 84, fat: 30, fiber: 13 },
      cuisineType: 'Indian',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-d-102',
      name: 'Mushroom Risotto',
      description: 'Slow-stirred arborio risotto with chestnut mushrooms and parmesan.',
      ingredients: [
        { name: 'arborio rice', quantity: 80, unit: 'g' },
        { name: 'chestnut mushrooms', quantity: 150, unit: 'g' },
        { name: 'vegetable stock', quantity: 500, unit: 'ml' },
        { name: 'parmesan cheese', quantity: 25, unit: 'g' },
        { name: 'onion', quantity: 50, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Sauté the mushrooms and onion in oil.',
        'Add the rice, then ladle in hot stock gradually, stirring, for 18 minutes.',
        'Finish with grated parmesan.',
      ],
      nutritionInfo: { calories: 560, protein: 17, carbs: 82, fat: 18, fiber: 5 },
      cuisineType: 'Italian',
      dietaryTags: ['vegetarian', 'gluten-free'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-d-103',
      name: 'Baked Falafel Bowl with Quinoa',
      description: 'Oven-baked falafel over quinoa with roasted vegetables and lemon dressing.',
      ingredients: [
        { name: 'falafel', quantity: 5, unit: 'pieces' },
        { name: 'quinoa', quantity: 70, unit: 'g' },
        { name: 'courgette', quantity: 100, unit: 'g' },
        { name: 'red pepper', quantity: 80, unit: 'g' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Cook the quinoa.',
        'Roast the vegetables and warm the falafel at 200°C for 15 minutes.',
        'Assemble and dress with lemon and oil.',
      ],
      nutritionInfo: { calories: 620, protein: 21, carbs: 74, fat: 27, fiber: 13 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegan', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-d-104',
      name: 'Grilled Steak with Roasted Vegetables',
      description: 'Sirloin steak with roasted peppers, courgette, and baby potatoes.',
      ingredients: [
        { name: 'sirloin steak', quantity: 180, unit: 'g' },
        { name: 'baby potatoes', quantity: 200, unit: 'g' },
        { name: 'red pepper', quantity: 80, unit: 'g' },
        { name: 'courgette', quantity: 100, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
        { name: 'rosemary', quantity: 2, unit: 'g' },
      ],
      instructions: [
        'Roast the potatoes and vegetables with oil and rosemary at 200°C for 30 minutes.',
        'Grill the steak 3 minutes per side; rest for 5.',
        'Slice and serve.',
      ],
      nutritionInfo: { calories: 650, protein: 45, carbs: 44, fat: 32, fiber: 7 },
      cuisineType: 'American',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein', 'paleo'],
      prepTimeMins: 10,
      cookTimeMins: 35,
      servings: 1,
    },
    {
      id: 'cur-d-105',
      name: 'Baked Cod with Potatoes and Green Beans',
      description: 'Flaky baked cod with lemon, crushed new potatoes and green beans.',
      ingredients: [
        { name: 'cod fillet', quantity: 160, unit: 'g' },
        { name: 'new potatoes', quantity: 200, unit: 'g' },
        { name: 'green beans', quantity: 100, unit: 'g' },
        { name: 'lemon', quantity: 0.5, unit: 'piece' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Boil the potatoes, then crush lightly with half the oil.',
        'Bake the cod with lemon slices at 190°C for 14 minutes.',
        'Steam the green beans and plate everything together.',
      ],
      nutritionInfo: { calories: 520, protein: 38, carbs: 46, fat: 18, fiber: 7 },
      cuisineType: 'European',
      dietaryTags: ['pescatarian', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-d-106',
      name: 'Vegetable Paella',
      description: 'Saffron rice with artichokes, peppers, peas, and green beans.',
      ingredients: [
        { name: 'paella rice', quantity: 80, unit: 'g' },
        { name: 'artichoke hearts', quantity: 80, unit: 'g' },
        { name: 'red pepper', quantity: 80, unit: 'g' },
        { name: 'peas', quantity: 60, unit: 'g' },
        { name: 'green beans', quantity: 60, unit: 'g' },
        { name: 'saffron', quantity: 1, unit: 'pinch' },
        { name: 'vegetable stock', quantity: 400, unit: 'ml' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Sauté the pepper in oil, add rice and saffron.',
        'Pour in stock and simmer without stirring for 18 minutes.',
        'Add the remaining vegetables for the last 8 minutes; rest before serving.',
      ],
      nutritionInfo: { calories: 560, protein: 14, carbs: 92, fat: 15, fiber: 10 },
      cuisineType: 'Spanish',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-d-107',
      name: 'Turkey Bolognese with Spaghetti',
      description: 'Lean turkey ragù with tomatoes and herbs over wholewheat spaghetti.',
      ingredients: [
        { name: 'lean turkey mince', quantity: 150, unit: 'g' },
        { name: 'wholewheat spaghetti', quantity: 80, unit: 'g' },
        { name: 'canned tomatoes', quantity: 250, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'garlic', quantity: 2, unit: 'cloves' },
        { name: 'Italian seasoning', quantity: 1, unit: 'tsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Brown the turkey with onion and garlic.',
        'Add tomatoes and herbs; simmer 15 minutes.',
        'Cook the spaghetti and toss with the sauce.',
      ],
      nutritionInfo: { calories: 640, protein: 45, carbs: 76, fat: 16, fiber: 11 },
      cuisineType: 'Italian',
      dietaryTags: ['dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-d-108',
      name: 'Stuffed Aubergine with Rice and Herbs',
      description: 'Roasted aubergine halves filled with herbed tomato rice and parsley.',
      ingredients: [
        { name: 'aubergine', quantity: 1, unit: 'large' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'canned tomatoes', quantity: 150, unit: 'g' },
        { name: 'parsley', quantity: 10, unit: 'g' },
        { name: 'garlic', quantity: 2, unit: 'cloves' },
        { name: 'olive oil', quantity: 1.5, unit: 'tbsp' },
      ],
      instructions: [
        'Halve and score the aubergine; roast cut-side up at 200°C for 25 minutes.',
        'Mix rice with tomatoes, garlic, and parsley.',
        'Fill the aubergine halves and bake 10 more minutes.',
      ],
      nutritionInfo: { calories: 520, protein: 11, carbs: 74, fat: 21, fiber: 12 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 35,
      servings: 1,
    },
    {
      id: 'cur-d-109',
      name: 'Chicken Fajita Bowl',
      description: 'Spiced chicken strips with charred peppers and onion over rice.',
      ingredients: [
        { name: 'chicken breast', quantity: 150, unit: 'g' },
        { name: 'red pepper', quantity: 100, unit: 'g' },
        { name: 'onion', quantity: 80, unit: 'g' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'fajita seasoning', quantity: 1, unit: 'tbsp' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Toss the chicken strips in fajita seasoning.',
        'Sear with peppers and onion over high heat for 8 minutes.',
        'Serve over rice with a squeeze of lime.',
      ],
      nutritionInfo: { calories: 600, protein: 44, carbs: 62, fat: 18, fiber: 6 },
      cuisineType: 'Mexican',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-d-110',
      name: 'Tofu Pad Thai',
      description: 'Rice noodles with crispy tofu, bean sprouts, and tamarind-lime sauce.',
      ingredients: [
        { name: 'rice noodles', quantity: 80, unit: 'g' },
        { name: 'firm tofu', quantity: 150, unit: 'g' },
        { name: 'bean sprouts', quantity: 80, unit: 'g' },
        { name: 'spring onions', quantity: 2, unit: 'pieces' },
        { name: 'tamarind paste', quantity: 1, unit: 'tbsp' },
        { name: 'soy sauce', quantity: 1.5, unit: 'tbsp' },
        { name: 'lime', quantity: 0.5, unit: 'piece' },
        { name: 'vegetable oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Soak the noodles; fry cubed tofu until golden.',
        'Add noodles, tamarind, and soy; toss over high heat.',
        'Fold in sprouts and spring onions; serve with lime.',
      ],
      nutritionInfo: { calories: 590, protein: 26, carbs: 78, fat: 20, fiber: 6 },
      cuisineType: 'Thai',
      dietaryTags: ['vegan', 'dairy-free'],
      prepTimeMins: 15,
      cookTimeMins: 12,
      servings: 1,
    },
    {
      id: 'cur-d-111',
      name: 'Courgette Noodle Beef Bolognese',
      description: 'Rich beef ragù served over ribbons of courgette instead of pasta.',
      ingredients: [
        { name: 'lean beef mince', quantity: 150, unit: 'g' },
        { name: 'courgette', quantity: 250, unit: 'g' },
        { name: 'canned tomatoes', quantity: 250, unit: 'g' },
        { name: 'onion', quantity: 60, unit: 'g' },
        { name: 'garlic', quantity: 2, unit: 'cloves' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Brown the beef with onion and garlic.',
        'Add tomatoes and simmer 20 minutes.',
        'Spiralise the courgette, sauté 2 minutes, and top with the ragù.',
      ],
      nutritionInfo: { calories: 480, protein: 37, carbs: 20, fat: 28, fiber: 6 },
      cuisineType: 'Italian',
      dietaryTags: ['gluten-free', 'dairy-free', 'high-protein', 'keto', 'paleo'],
      prepTimeMins: 15,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-d-112',
      name: 'Creamy Tuscan Chicken with Rice',
      description: 'Pan-seared chicken in a creamy sun-dried tomato and spinach sauce.',
      ingredients: [
        { name: 'chicken breast', quantity: 150, unit: 'g' },
        { name: 'single cream', quantity: 100, unit: 'ml' },
        { name: 'sun-dried tomatoes', quantity: 30, unit: 'g' },
        { name: 'baby spinach', quantity: 60, unit: 'g' },
        { name: 'cooked rice', quantity: 150, unit: 'g' },
        { name: 'garlic', quantity: 2, unit: 'cloves' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      ],
      instructions: [
        'Sear the chicken until cooked through; set aside.',
        'Soften garlic and sun-dried tomatoes, add cream and spinach.',
        'Return the chicken, coat in the sauce, and serve over rice.',
      ],
      nutritionInfo: { calories: 680, protein: 46, carbs: 58, fat: 28, fiber: 4 },
      cuisineType: 'Italian',
      dietaryTags: ['gluten-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
  ] as R[]
).map(withImage);

// ── Snacks ────────────────────────────────────────────────────────────────────

export const EXTRA_SNACK_POOL: RecipeData[] = (
  [
    {
      id: 'cur-s-101',
      name: 'Rice Cakes with Avocado',
      description: 'Crunchy rice cakes topped with smashed avocado, lime, and chilli flakes.',
      ingredients: [
        { name: 'rice cakes', quantity: 2, unit: 'pieces' },
        { name: 'avocado', quantity: 0.5, unit: 'medium' },
        { name: 'lime juice', quantity: 1, unit: 'tsp' },
        { name: 'chilli flakes', quantity: 1, unit: 'pinch' },
      ],
      instructions: [
        'Mash the avocado with lime.',
        'Spread on the rice cakes and top with chilli.',
      ],
      nutritionInfo: { calories: 220, protein: 4, carbs: 22, fat: 14, fiber: 6 },
      cuisineType: 'American',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
      prepTimeMins: 5,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-s-102',
      name: 'Greek Yogurt with Honey',
      description: 'Thick Greek yogurt drizzled with honey and a pinch of cinnamon.',
      ingredients: [
        { name: 'Greek yogurt', quantity: 170, unit: 'g' },
        { name: 'honey', quantity: 15, unit: 'ml' },
        { name: 'cinnamon', quantity: 1, unit: 'pinch' },
      ],
      instructions: ['Spoon the yogurt into a bowl.', 'Drizzle with honey and dust with cinnamon.'],
      nutritionInfo: { calories: 210, protein: 17, carbs: 24, fat: 5, fiber: 0 },
      cuisineType: 'Greek',
      dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'],
      prepTimeMins: 2,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-s-103',
      name: 'Crispy Roasted Chickpeas',
      description: 'Oven-roasted chickpeas with smoked paprika — a crunchy, high-fibre snack.',
      ingredients: [
        { name: 'canned chickpeas', quantity: 150, unit: 'g' },
        { name: 'olive oil', quantity: 1, unit: 'tsp' },
        { name: 'smoked paprika', quantity: 0.5, unit: 'tsp' },
        { name: 'salt', quantity: 1, unit: 'pinch' },
      ],
      instructions: [
        'Pat the chickpeas dry and toss with oil and paprika.',
        'Roast at 200°C for 25 minutes, shaking halfway, until crisp.',
      ],
      nutritionInfo: { calories: 230, protein: 11, carbs: 30, fat: 7, fiber: 9 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 5,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-s-104',
      name: 'Dark Chocolate and Strawberries',
      description: 'Fresh strawberries with squares of 70% dark chocolate.',
      ingredients: [
        { name: 'strawberries', quantity: 150, unit: 'g' },
        { name: 'dark chocolate (70%)', quantity: 25, unit: 'g' },
      ],
      instructions: ['Rinse the strawberries.', 'Serve with the chocolate squares.'],
      nutritionInfo: { calories: 190, protein: 3, carbs: 24, fat: 10, fiber: 5 },
      cuisineType: 'European',
      dietaryTags: ['vegetarian', 'gluten-free'],
      prepTimeMins: 2,
      cookTimeMins: 0,
      servings: 1,
    },
    {
      id: 'cur-s-105',
      name: 'Boiled Eggs with Sea Salt',
      description: 'Two soft-boiled eggs with flaky sea salt and cracked pepper.',
      ingredients: [
        { name: 'eggs', quantity: 2, unit: 'large' },
        { name: 'sea salt', quantity: 1, unit: 'pinch' },
        { name: 'black pepper', quantity: 1, unit: 'pinch' },
      ],
      instructions: [
        'Boil the eggs for 7 minutes; cool in cold water.',
        'Peel, halve, and season.',
      ],
      nutritionInfo: { calories: 160, protein: 13, carbs: 1, fat: 11, fiber: 0 },
      cuisineType: 'European',
      dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'keto', 'high-protein'],
      prepTimeMins: 2,
      cookTimeMins: 8,
      servings: 1,
    },
    {
      id: 'cur-s-106',
      name: 'Edamame with Chilli Flakes',
      description: 'Steamed edamame pods tossed with sea salt and chilli flakes.',
      ingredients: [
        { name: 'edamame beans in pods', quantity: 150, unit: 'g' },
        { name: 'sea salt', quantity: 1, unit: 'pinch' },
        { name: 'chilli flakes', quantity: 1, unit: 'pinch' },
      ],
      instructions: ['Steam the pods for 5 minutes.', 'Toss with salt and chilli flakes.'],
      nutritionInfo: { calories: 180, protein: 17, carbs: 12, fat: 7, fiber: 8 },
      cuisineType: 'Japanese',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 2,
      cookTimeMins: 5,
      servings: 1,
    },
  ] as R[]
).map(withImage);
