import type { RecipeData } from '../ai/types.js';
import { buildPollinationsUrl } from '../image-gen/pollinations.js';
import { buildRecipeImagePrompt } from '../image-gen/prompt.js';

// ─── Curated pool: diet variety (WP-14 lane C) ────────────────────────────────
// Gap-fill recipes so multi-week plans for restricted diets stop repeating:
// vegan and vegan + gluten-free breakfasts, lunches and dinners, plus
// vegetarian, pescatarian and gluten-free dinners. Same contract as
// extra-pool.ts: every line carries a catalog `slug` with a unit that row can
// weigh (the served nutrition is COMPUTED from the catalog; `nutritionInfo`
// here is only a rough placeholder), and `dietaryTags` are load-bearing — a
// recipe is tagged only when its ingredients AND method genuinely comply
// (safety.ts scans names, ingredients and steps; variety-pool.test.ts asserts
// every tag against the ingredient-derived verdict).
//
// Deliberately kept free of label-dependent gluten ingredients (stock, curry
// powder, soy sauce, baking powder, oats) in the gluten-free recipes: those
// recipes spice from scratch and use plain water.

const img = (name: string, cuisine: string) =>
  buildPollinationsUrl(buildRecipeImagePrompt(name, cuisine), name, cuisine);

type R = Omit<RecipeData, 'imageUrl'> & { imageUrl?: string };

const withImage = (r: R): RecipeData => ({ ...r, imageUrl: img(r.name, r.cuisineType) });

// ── Breakfasts ────────────────────────────────────────────────────────────────

export const VARIETY_BREAKFAST_POOL: RecipeData[] = (
  [
    {
      id: 'cur-v-001',
      name: 'Besan Chilla (Savoury Chickpea Pancakes)',
      description:
        'Thin, protein-rich pancakes from chickpea besan with tomato, spinach and spring onion, pan-fried until golden.',
      ingredients: [
        { name: 'besan (chickpea)', quantity: 70, unit: 'g', slug: 'flour-chickpea' },
        { name: 'water', quantity: 110, unit: 'ml', slug: 'water' },
        { name: 'tomato', quantity: 1, unit: 'medium', slug: 'tomato-raw' },
        { name: 'baby spinach', quantity: 40, unit: 'g', slug: 'spinach-raw' },
        { name: 'spring onions', quantity: 2, unit: 'medium', slug: 'spring-onion-raw' },
        { name: 'ground cumin', quantity: 0.5, unit: 'tsp', slug: 'cumin' },
        { name: 'turmeric', quantity: 0.25, unit: 'tsp', slug: 'turmeric' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Whisk the besan with the water, cumin, turmeric and a pinch of salt into a smooth, pourable batter.',
        'Stir in the finely chopped tomato, spinach and spring onions.',
        'Heat a little oil in a non-stick pan and pour in a ladleful of batter, spreading it thin.',
        'Cook 2–3 minutes per side until golden and set. Repeat with the remaining batter.',
      ],
      nutritionInfo: { calories: 420, protein: 19, carbs: 41, fat: 20, fiber: 9 },
      cuisineType: 'Indian',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-v-002',
      name: 'Sweet Potato and Black Bean Breakfast Hash',
      description:
        'Crisp-edged sweet potato with smoky black beans, peppers and creamy avocado: a hearty, fibre-rich plant-based breakfast.',
      ingredients: [
        { name: 'sweet potato', quantity: 150, unit: 'g', slug: 'sweet-potato-raw' },
        { name: 'black beans, canned', quantity: 120, unit: 'g', slug: 'black-beans-canned' },
        { name: 'red pepper', quantity: 0.5, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'onion', quantity: 0.5, unit: 'medium', slug: 'onion-raw' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'ground cumin', quantity: 0.5, unit: 'tsp', slug: 'cumin' },
        { name: 'avocado', quantity: 0.5, unit: 'piece', slug: 'avocado-raw' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Dice the sweet potato small and fry in the oil over medium-high heat for 8–10 minutes until tender and browned.',
        'Add the chopped onion and pepper with the paprika and cumin; cook 4 minutes.',
        'Stir in the drained black beans and heat through.',
        'Serve topped with sliced avocado, a squeeze of lime and a pinch of salt.',
      ],
      nutritionInfo: { calories: 520, protein: 14, carbs: 66, fat: 24, fiber: 18 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-v-003',
      name: 'Coconut Quinoa Breakfast Bowl',
      description:
        'Quinoa simmered in coconut milk and cinnamon, topped with banana, blueberries and pumpkin seeds.',
      ingredients: [
        { name: 'quinoa', quantity: 50, unit: 'g', slug: 'quinoa-dry' },
        { name: 'coconut milk', quantity: 60, unit: 'ml', slug: 'coconut-milk-canned' },
        { name: 'water', quantity: 120, unit: 'ml', slug: 'water' },
        { name: 'banana', quantity: 1, unit: 'medium', slug: 'banana-raw' },
        { name: 'blueberries', quantity: 60, unit: 'g', slug: 'blueberries-raw' },
        { name: 'cinnamon', quantity: 0.5, unit: 'tsp', slug: 'cinnamon' },
        { name: 'maple syrup', quantity: 1, unit: 'tsp', slug: 'maple-syrup' },
        { name: 'pumpkin seeds', quantity: 10, unit: 'g', slug: 'pumpkin-seeds' },
      ],
      instructions: [
        'Rinse the quinoa and simmer with the water, coconut milk and cinnamon for 15 minutes until fluffy and thick.',
        'Spoon into a bowl and drizzle with the maple syrup.',
        'Top with sliced banana, blueberries and pumpkin seeds.',
      ],
      nutritionInfo: { calories: 510, protein: 13, carbs: 74, fat: 18, fiber: 9 },
      cuisineType: 'Tropical',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 5,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-v-004',
      name: 'Ginger Rice Congee with Tofu',
      description:
        'Silky, slow-simmered rice porridge with fresh ginger, mushrooms and soft tofu cubes. Comforting and light on the stomach.',
      ingredients: [
        { name: 'white rice', quantity: 60, unit: 'g', slug: 'rice-white-dry' },
        { name: 'water', quantity: 450, unit: 'ml', slug: 'water' },
        { name: 'fresh ginger', quantity: 10, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'firm tofu', quantity: 120, unit: 'g', slug: 'tofu-firm' },
        { name: 'white mushrooms', quantity: 60, unit: 'g', slug: 'mushroom-white-raw' },
        { name: 'spring onions', quantity: 2, unit: 'medium', slug: 'spring-onion-raw' },
        { name: 'sesame oil', quantity: 1, unit: 'tsp', slug: 'sesame-oil' },
        { name: 'roasted peanuts', quantity: 10, unit: 'g', slug: 'peanuts-roasted' },
        { name: 'White pepper', quantity: 1, unit: 'to taste', slug: 'white-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Rinse the rice and simmer it with the water and sliced ginger for 25 minutes, stirring now and then, until it breaks down into a thick porridge.',
        'Add the sliced mushrooms and cubed tofu for the last 5 minutes.',
        'Season with salt and white pepper.',
        'Ladle into a bowl and finish with spring onions, sesame oil and crushed peanuts.',
      ],
      nutritionInfo: { calories: 440, protein: 19, carbs: 56, fat: 14, fiber: 4 },
      cuisineType: 'Asian',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 5,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-005',
      name: 'Peanut Butter Banana Porridge',
      description:
        'Creamy rolled oats cooked in soy milk with banana, peanut butter and chia: slow-release energy for a busy morning.',
      ingredients: [
        { name: 'rolled oats', quantity: 50, unit: 'g', slug: 'oats-rolled' },
        { name: 'unsweetened soy milk', quantity: 250, unit: 'ml', slug: 'soy-milk-unsweetened' },
        { name: 'banana', quantity: 1, unit: 'medium', slug: 'banana-raw' },
        { name: 'peanut butter', quantity: 1, unit: 'tbsp', slug: 'peanut-butter' },
        { name: 'chia seeds', quantity: 8, unit: 'g', slug: 'chia-seeds' },
        { name: 'cinnamon', quantity: 0.5, unit: 'tsp', slug: 'cinnamon' },
      ],
      instructions: [
        'Simmer the oats with the soy milk and half the sliced banana for 5 minutes, stirring, until thick.',
        'Stir in the cinnamon and chia seeds.',
        'Top with the remaining banana and a spoonful of peanut butter.',
      ],
      nutritionInfo: { calories: 520, protein: 22, carbs: 70, fat: 20, fiber: 12 },
      cuisineType: 'American',
      dietaryTags: ['vegan', 'dairy-free', 'high-fiber'],
      prepTimeMins: 3,
      cookTimeMins: 7,
      servings: 1,
    },
    {
      id: 'cur-v-006',
      name: 'Smashed Chickpea and Avocado on Rye',
      description:
        'Lemony smashed chickpeas and avocado piled on dark rye with cherry tomatoes and smoked paprika.',
      ingredients: [
        { name: 'rye bread', quantity: 2, unit: 'slice', slug: 'bread-rye' },
        { name: 'chickpeas, canned', quantity: 80, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'avocado', quantity: 0.5, unit: 'piece', slug: 'avocado-raw' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'cherry tomatoes', quantity: 5, unit: 'piece', slug: 'cherry-tomato-raw' },
        { name: 'smoked paprika', quantity: 0.5, unit: 'tsp', slug: 'paprika' },
        { name: 'olive oil', quantity: 1, unit: 'tsp', slug: 'olive-oil' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Mash the chickpeas and avocado roughly with the lemon juice, salt and pepper.',
        'Toast the rye bread and drizzle with the oil.',
        'Pile the smash onto the toast and top with halved cherry tomatoes and paprika.',
      ],
      nutritionInfo: { calories: 500, protein: 16, carbs: 55, fat: 24, fiber: 15 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['vegan', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 3,
      servings: 1,
    },
    {
      id: 'cur-v-007',
      name: 'Tofu Breakfast Burrito',
      description:
        'Turmeric-spiced tofu scramble with black beans, peppers and avocado, rolled in a warm wholewheat tortilla.',
      ingredients: [
        {
          name: 'small wholewheat tortillas',
          quantity: 2,
          unit: 'piece',
          slug: 'tortilla-whole-wheat',
        },
        { name: 'firm tofu', quantity: 120, unit: 'g', slug: 'tofu-firm' },
        { name: 'black beans, canned', quantity: 50, unit: 'g', slug: 'black-beans-canned' },
        { name: 'red pepper', quantity: 0.5, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'avocado', quantity: 0.25, unit: 'piece', slug: 'avocado-raw' },
        { name: 'olive oil', quantity: 1, unit: 'tsp', slug: 'olive-oil' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'ground cumin', quantity: 0.5, unit: 'tsp', slug: 'cumin' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Crumble the tofu and fry in the oil with the diced pepper, turmeric and cumin for 5 minutes.',
        'Stir in the black beans and a pinch of salt and warm through.',
        'Warm the tortillas in a dry pan.',
        'Fill with the tofu mixture and sliced avocado, then roll up tightly.',
      ],
      nutritionInfo: { calories: 560, protein: 28, carbs: 58, fat: 24, fiber: 12 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 10,
      servings: 1,
    },
  ] as R[]
).map(withImage);

// ── Lunches ───────────────────────────────────────────────────────────────────

export const VARIETY_LUNCH_POOL: RecipeData[] = (
  [
    {
      id: 'cur-v-101',
      name: 'Moroccan Chickpea and Quinoa Salad',
      description:
        'Warmly spiced chickpeas and quinoa with cucumber, tomato, dried apricot and fresh herbs in a lemony dressing.',
      ingredients: [
        { name: 'quinoa', quantity: 50, unit: 'g', slug: 'quinoa-dry' },
        { name: 'chickpeas, canned', quantity: 120, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'cucumber', quantity: 80, unit: 'g', slug: 'cucumber-raw' },
        { name: 'tomato', quantity: 1, unit: 'medium', slug: 'tomato-raw' },
        { name: 'red onion', quantity: 0.5, unit: 'small', slug: 'red-onion-raw' },
        { name: 'dried apricots', quantity: 20, unit: 'g', slug: 'apricots-dried' },
        { name: 'fresh parsley', quantity: 10, unit: 'g', slug: 'parsley-fresh' },
        { name: 'fresh mint', quantity: 5, unit: 'g', slug: 'mint-fresh' },
        { name: 'lemon juice', quantity: 1.5, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'ground cumin', quantity: 0.5, unit: 'tsp', slug: 'cumin' },
        { name: 'cinnamon', quantity: 0.25, unit: 'tsp', slug: 'cinnamon' },
        { name: 'pumpkin seeds', quantity: 10, unit: 'g', slug: 'pumpkin-seeds' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Rinse the quinoa and simmer in twice its volume of water for 15 minutes; fluff and cool slightly.',
        'Dice the cucumber, tomato, onion and apricots and chop the herbs.',
        'Whisk the lemon juice, oil, cumin, cinnamon and salt.',
        'Toss everything with the chickpeas and quinoa and scatter over the pumpkin seeds.',
      ],
      nutritionInfo: { calories: 640, protein: 22, carbs: 78, fat: 26, fiber: 16 },
      cuisineType: 'North African',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 15,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-v-102',
      name: 'Black Bean and Rice Burrito Bowl',
      description:
        'Cumin-spiced rice and black beans with sweetcorn, tomato, romaine and avocado, finished with fresh lime.',
      ingredients: [
        { name: 'white rice', quantity: 55, unit: 'g', slug: 'rice-white-dry' },
        { name: 'black beans, canned', quantity: 130, unit: 'g', slug: 'black-beans-canned' },
        { name: 'sweetcorn, frozen', quantity: 60, unit: 'g', slug: 'sweet-corn-frozen' },
        { name: 'tomato', quantity: 1, unit: 'medium', slug: 'tomato-raw' },
        { name: 'romaine lettuce', quantity: 40, unit: 'g', slug: 'lettuce-romaine-raw' },
        { name: 'avocado', quantity: 0.5, unit: 'piece', slug: 'avocado-raw' },
        { name: 'red onion', quantity: 0.5, unit: 'small', slug: 'red-onion-raw' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'ground cumin', quantity: 0.5, unit: 'tsp', slug: 'cumin' },
        { name: 'smoked paprika', quantity: 0.5, unit: 'tsp', slug: 'paprika' },
        { name: 'olive oil', quantity: 1, unit: 'tsp', slug: 'olive-oil' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Cook the rice in plenty of boiling water for 12 minutes, then drain.',
        'Warm the beans and sweetcorn with the cumin, paprika and oil for 4 minutes.',
        'Dice the tomato, onion and avocado and shred the lettuce.',
        'Build the bowl: rice, bean mix and fresh toppings, then dress with lime juice and salt.',
      ],
      nutritionInfo: { calories: 640, protein: 20, carbs: 95, fat: 20, fiber: 20 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 15,
      servings: 1,
    },
    {
      id: 'cur-v-103',
      name: 'Warm Lentil and Roasted Pepper Salad',
      description:
        'Tender green lentils tossed warm with roasted peppers, rocket, walnuts and a balsamic-Dijon dressing.',
      ingredients: [
        {
          name: 'cooked green lentils',
          quantity: 200,
          unit: 'g',
          slug: 'lentils-green-cooked-ciqual',
        },
        { name: 'roasted red peppers', quantity: 80, unit: 'g', slug: 'roasted-red-peppers' },
        { name: 'rocket', quantity: 30, unit: 'g', slug: 'arugula-raw' },
        { name: 'cucumber', quantity: 60, unit: 'g', slug: 'cucumber-raw' },
        { name: 'red onion', quantity: 0.5, unit: 'small', slug: 'red-onion-raw' },
        { name: 'walnuts', quantity: 15, unit: 'g', slug: 'walnuts' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'balsamic vinegar', quantity: 1, unit: 'tbsp', slug: 'vinegar-balsamic' },
        { name: 'Dijon mustard', quantity: 1, unit: 'tsp', slug: 'mustard-dijon' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Warm the cooked lentils in a pan for 3 minutes.',
        'Whisk the oil, balsamic vinegar, mustard, salt and pepper into a dressing.',
        'Slice the roasted peppers, cucumber and onion.',
        'Toss the warm lentils with the vegetables and dressing, fold in the rocket and top with chopped walnuts.',
      ],
      nutritionInfo: { calories: 520, protein: 24, carbs: 49, fat: 26, fiber: 17 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 5,
      servings: 1,
    },
    {
      id: 'cur-v-104',
      name: 'Hummus and Roasted Vegetable Wrap',
      description:
        'Wholewheat wrap spread with hummus and filled with roasted courgette and peppers, chickpeas and fresh spinach.',
      ingredients: [
        { name: 'wholewheat tortillas', quantity: 2, unit: 'piece', slug: 'tortilla-whole-wheat' },
        { name: 'hummus', quantity: 60, unit: 'g', slug: 'hummus' },
        { name: 'courgette', quantity: 100, unit: 'g', slug: 'zucchini-raw' },
        { name: 'red pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'chickpeas, canned', quantity: 60, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'baby spinach', quantity: 20, unit: 'g', slug: 'spinach-raw' },
        { name: 'olive oil', quantity: 1, unit: 'tsp', slug: 'olive-oil' },
        { name: 'smoked paprika', quantity: 0.5, unit: 'tsp', slug: 'paprika' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Slice the courgette and pepper, toss with the oil, paprika and salt, and roast at 220°C for 20 minutes.',
        'Warm the tortillas in a dry pan and spread with the hummus.',
        'Layer on the spinach, roasted vegetables and chickpeas.',
        'Roll up tightly and halve to serve.',
      ],
      nutritionInfo: { calories: 520, protein: 19, carbs: 62, fat: 19, fiber: 15 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegan', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-v-105',
      name: 'Peanut Noodle Bowl with Edamame',
      description:
        'Rice noodles and crunchy vegetables in a lime-peanut dressing with edamame for plant protein.',
      ingredients: [
        { name: 'rice noodles', quantity: 70, unit: 'g', slug: 'rice-noodles-dry' },
        { name: 'frozen edamame', quantity: 80, unit: 'g', slug: 'edamame-frozen' },
        { name: 'carrot', quantity: 1, unit: 'medium', slug: 'carrot-raw' },
        { name: 'red cabbage', quantity: 50, unit: 'g', slug: 'cabbage-red-raw' },
        { name: 'cucumber', quantity: 50, unit: 'g', slug: 'cucumber-raw' },
        { name: 'peanut butter', quantity: 1, unit: 'tbsp', slug: 'peanut-butter' },
        { name: 'soy sauce', quantity: 1, unit: 'tbsp', slug: 'soy-sauce' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'garlic', quantity: 1, unit: 'clove', slug: 'garlic-raw' },
        { name: 'fresh ginger', quantity: 5, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'sesame oil', quantity: 1, unit: 'tsp', slug: 'sesame-oil' },
        { name: 'sriracha', quantity: 1, unit: 'tsp', slug: 'sriracha' },
      ],
      instructions: [
        'Soak or boil the rice noodles per the packet, then drain and rinse under cold water.',
        'Cook the edamame in boiling water for 4 minutes and drain.',
        'Whisk the peanut butter, soy sauce, lime juice, grated garlic and ginger, sesame oil, sriracha and 2 tablespoons of warm water.',
        'Toss the noodles with the julienned carrot, shredded cabbage, cucumber, edamame and dressing.',
      ],
      nutritionInfo: { calories: 560, protein: 22, carbs: 78, fat: 18, fiber: 10 },
      cuisineType: 'Thai',
      dietaryTags: ['vegan', 'dairy-free', 'high-protein'],
      prepTimeMins: 15,
      cookTimeMins: 10,
      servings: 1,
    },
    {
      id: 'cur-v-106',
      name: 'Spiced Carrot and Red Lentil Soup',
      description:
        'A velvety, gently spiced soup of carrots and red lentils with cumin, coriander and a swirl of coconut milk.',
      ingredients: [
        { name: 'red lentils', quantity: 60, unit: 'g', slug: 'red-lentils-dry' },
        { name: 'carrots', quantity: 200, unit: 'g', slug: 'carrot-raw' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'water', quantity: 500, unit: 'ml', slug: 'water' },
        { name: 'coconut milk', quantity: 50, unit: 'ml', slug: 'coconut-milk-canned' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'ground coriander', quantity: 0.5, unit: 'tsp', slug: 'coriander-seed' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Soften the chopped onion and garlic in the oil for 5 minutes, then stir in the cumin, coriander and turmeric for 1 minute.',
        'Add the sliced carrots, rinsed lentils and water; bring to the boil and simmer 20 minutes until everything is soft.',
        'Blend until smooth, return to the pan and stir in the coconut milk.',
        'Season with salt and lemon juice and serve hot.',
      ],
      nutritionInfo: { calories: 580, protein: 21, carbs: 74, fat: 22, fiber: 18 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
  ] as R[]
).map(withImage);

// ── Dinners ───────────────────────────────────────────────────────────────────

export const VARIETY_DINNER_POOL: RecipeData[] = (
  [
    {
      id: 'cur-v-201',
      name: 'Chana Masala with Basmati Rice',
      description:
        'Chickpeas simmered in a tangy tomato, ginger and garlic masala, served over fluffy basmati rice.',
      ingredients: [
        { name: 'chickpeas, canned', quantity: 160, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'canned tomatoes', quantity: 200, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 3, unit: 'clove', slug: 'garlic-raw' },
        { name: 'fresh ginger', quantity: 10, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'ground coriander', quantity: 1, unit: 'tsp', slug: 'coriander-seed' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'cayenne pepper', quantity: 0.25, unit: 'tsp', slug: 'cayenne-pepper' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'basmati rice', quantity: 60, unit: 'g', slug: 'rice-basmati-dry' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Cook the basmati rice in boiling water for 10–12 minutes and drain.',
        'Fry the chopped onion in the oil for 6 minutes, then add the grated garlic and ginger and the spices for 1 minute.',
        'Add the tomatoes, chickpeas and a splash of water and simmer 15 minutes, crushing some of the chickpeas to thicken.',
        'Finish with lemon juice and salt and serve over the rice.',
      ],
      nutritionInfo: { calories: 620, protein: 20, carbs: 105, fat: 14, fiber: 18 },
      cuisineType: 'Indian',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-v-202',
      name: 'Coconut Tofu and Vegetable Curry',
      description:
        'Golden tofu and crisp vegetables in a fragrant ginger-turmeric coconut sauce with a squeeze of lime, over jasmine-style rice.',
      ingredients: [
        { name: 'firm tofu', quantity: 150, unit: 'g', slug: 'tofu-firm' },
        { name: 'coconut milk', quantity: 100, unit: 'ml', slug: 'coconut-milk-canned' },
        { name: 'broccoli', quantity: 100, unit: 'g', slug: 'broccoli-raw' },
        { name: 'red pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'courgette', quantity: 80, unit: 'g', slug: 'zucchini-raw' },
        { name: 'fresh ginger', quantity: 8, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'red chilli', quantity: 0.5, unit: 'piece', slug: 'chili-pepper-red-raw' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'ground coriander', quantity: 0.5, unit: 'tsp', slug: 'coriander-seed' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'sunflower oil', quantity: 1, unit: 'tsp', slug: 'sunflower-oil' },
        { name: 'white rice', quantity: 60, unit: 'g', slug: 'rice-white-dry' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Cook the rice in boiling water for 12 minutes and drain.',
        'Press the tofu dry, cube it and fry in the oil until golden on all sides; set aside.',
        'In the same pan, fry the garlic, ginger, chilli, turmeric and coriander for 1 minute, then add the coconut milk and 100 ml water.',
        'Add the broccoli, pepper and courgette and simmer 8 minutes until just tender.',
        'Return the tofu, season with salt and lime juice and serve over the rice.',
      ],
      nutritionInfo: { calories: 680, protein: 27, carbs: 76, fat: 30, fiber: 10 },
      cuisineType: 'Thai',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 15,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-v-203',
      name: 'Black Bean and Sweet Potato Chili',
      description:
        'A thick, smoky chili of black beans and sweet potato in rich tomato sauce, served over brown rice.',
      ingredients: [
        { name: 'black beans, canned', quantity: 150, unit: 'g', slug: 'black-beans-canned' },
        { name: 'sweet potato', quantity: 150, unit: 'g', slug: 'sweet-potato-raw' },
        { name: 'canned tomatoes', quantity: 200, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'green pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-green-raw' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'dried oregano', quantity: 0.5, unit: 'tsp', slug: 'oregano-dried' },
        { name: 'cayenne pepper', quantity: 0.25, unit: 'tsp', slug: 'cayenne-pepper' },
        { name: 'cocoa powder', quantity: 1, unit: 'tsp', slug: 'cocoa-powder' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'brown rice', quantity: 45, unit: 'g', slug: 'rice-brown-dry' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Start the brown rice in boiling water; it needs about 25 minutes.',
        'Fry the chopped onion, garlic and pepper in the oil for 5 minutes, then add the spices and cocoa for 1 minute.',
        'Add the diced sweet potato, tomatoes, black beans and 100 ml water. Simmer 20 minutes until the sweet potato is soft and the sauce thick.',
        'Season with salt and serve over the drained rice.',
      ],
      nutritionInfo: { calories: 650, protein: 22, carbs: 118, fat: 11, fiber: 26 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-204',
      name: 'Lentil Bolognese Spaghetti',
      description:
        'Hearty tomato and lentil ragu with carrot, celery and herbs, tossed through spaghetti. All the comfort of bolognese, entirely plant-based.',
      ingredients: [
        { name: 'spaghetti', quantity: 70, unit: 'g', slug: 'pasta-dry' },
        {
          name: 'cooked green lentils',
          quantity: 150,
          unit: 'g',
          slug: 'lentils-green-cooked-ciqual',
        },
        { name: 'canned tomatoes', quantity: 200, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'tomato paste', quantity: 1, unit: 'tbsp', slug: 'tomato-paste' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'carrot', quantity: 1, unit: 'medium', slug: 'carrot-raw' },
        { name: 'celery', quantity: 1, unit: 'stalk', slug: 'celery-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'dried oregano', quantity: 1, unit: 'tsp', slug: 'oregano-dried' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'fresh basil', quantity: 5, unit: 'leaf', slug: 'basil-fresh' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Finely chop the onion, carrot, celery and garlic and soften in the oil for 8 minutes.',
        'Stir in the tomato paste and oregano, then add the tomatoes and lentils. Simmer 15 minutes, adding a splash of water if it gets dry.',
        'Cook the spaghetti in salted boiling water until al dente and drain.',
        'Toss the pasta through the ragu, season and top with torn basil.',
      ],
      nutritionInfo: { calories: 650, protein: 26, carbs: 112, fat: 11, fiber: 18 },
      cuisineType: 'Italian',
      dietaryTags: ['vegan', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-v-205',
      name: 'Tofu and Broccoli Stir-Fry with Brown Rice',
      description:
        'Crisp-seared tofu with broccoli, carrot and red pepper in a ginger-garlic soy glaze, with a handful of cashews.',
      ingredients: [
        { name: 'firm tofu', quantity: 180, unit: 'g', slug: 'tofu-firm' },
        { name: 'broccoli', quantity: 150, unit: 'g', slug: 'broccoli-raw' },
        { name: 'carrot', quantity: 1, unit: 'medium', slug: 'carrot-raw' },
        { name: 'red pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'fresh ginger', quantity: 8, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'soy sauce', quantity: 1.5, unit: 'tbsp', slug: 'soy-sauce' },
        { name: 'sesame oil', quantity: 1, unit: 'tsp', slug: 'sesame-oil' },
        { name: 'sunflower oil', quantity: 2, unit: 'tsp', slug: 'sunflower-oil' },
        { name: 'spring onions', quantity: 2, unit: 'medium', slug: 'spring-onion-raw' },
        { name: 'cashews', quantity: 10, unit: 'g', slug: 'cashews-roasted' },
        { name: 'brown rice', quantity: 65, unit: 'g', slug: 'rice-brown-dry' },
      ],
      instructions: [
        'Cook the brown rice in boiling water for about 25 minutes and drain.',
        'Press the tofu dry, cube it and sear in the sunflower oil over high heat until golden; remove from the pan.',
        'Stir-fry the broccoli, sliced carrot and pepper for 4–5 minutes, adding the garlic and ginger for the last minute.',
        'Return the tofu with the soy sauce, sesame oil and 2 tablespoons of water and toss for 1 minute.',
        'Serve over the rice, topped with spring onions and cashews.',
      ],
      nutritionInfo: { calories: 640, protein: 32, carbs: 74, fat: 24, fiber: 12 },
      cuisineType: 'Asian',
      dietaryTags: ['vegan', 'dairy-free', 'high-protein'],
      prepTimeMins: 15,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-v-206',
      name: 'Chickpea and Apricot Tagine with Quinoa',
      description:
        'A sweet-savoury North African stew of chickpeas, carrot and apricots in warm cinnamon and ginger, served on quinoa.',
      ingredients: [
        { name: 'chickpeas, canned', quantity: 120, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'dried apricots', quantity: 30, unit: 'g', slug: 'apricots-dried' },
        { name: 'carrot', quantity: 1, unit: 'large', slug: 'carrot-raw' },
        { name: 'courgette', quantity: 80, unit: 'g', slug: 'zucchini-raw' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'canned tomatoes', quantity: 150, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'cinnamon', quantity: 0.5, unit: 'tsp', slug: 'cinnamon' },
        { name: 'ground ginger', quantity: 0.5, unit: 'tsp', slug: 'ginger-ground' },
        { name: 'paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'turmeric', quantity: 0.25, unit: 'tsp', slug: 'turmeric' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'quinoa', quantity: 50, unit: 'g', slug: 'quinoa-dry' },
        { name: 'fresh parsley', quantity: 5, unit: 'g', slug: 'parsley-fresh' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Soften the chopped onion in the oil for 5 minutes, then add the garlic and all the spices for 1 minute.',
        'Add the sliced carrot, courgette, apricots, chickpeas, tomatoes and 150 ml water. Cover and simmer 25 minutes.',
        'Meanwhile, cook the rinsed quinoa in twice its volume of water for 15 minutes.',
        'Season the tagine with salt and serve on the quinoa with parsley.',
      ],
      nutritionInfo: { calories: 640, protein: 21, carbs: 104, fat: 14, fiber: 22 },
      cuisineType: 'North African',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-207',
      name: 'Mexican Stuffed Peppers with Rice and Beans',
      description:
        'Roasted red peppers filled with cumin rice, black beans and sweetcorn, served with sliced avocado.',
      ingredients: [
        { name: 'red peppers', quantity: 2, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'white rice', quantity: 40, unit: 'g', slug: 'rice-white-dry' },
        { name: 'black beans, canned', quantity: 100, unit: 'g', slug: 'black-beans-canned' },
        { name: 'sweetcorn, frozen', quantity: 50, unit: 'g', slug: 'sweet-corn-frozen' },
        { name: 'canned tomatoes', quantity: 100, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'onion', quantity: 1, unit: 'small', slug: 'onion-raw' },
        { name: 'garlic', quantity: 1, unit: 'clove', slug: 'garlic-raw' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'avocado', quantity: 0.5, unit: 'piece', slug: 'avocado-raw' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Heat the oven to 200°C. Halve the peppers lengthways and remove the seeds.',
        'Cook the rice in boiling water for 12 minutes and drain.',
        'Fry the chopped onion and garlic in half the oil, add the spices, tomatoes, beans, sweetcorn and cooked rice, and warm through for 5 minutes.',
        'Fill the pepper halves, brush the tops with the remaining oil and bake 20 minutes.',
        'Serve with sliced avocado, lime juice and a pinch of salt.',
      ],
      nutritionInfo: { calories: 670, protein: 18, carbs: 92, fat: 26, fiber: 22 },
      cuisineType: 'Mexican',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-208',
      name: 'Aloo Gobi (Potato and Cauliflower Curry)',
      description:
        'Tender potato and cauliflower in a turmeric-cumin masala with peas and tomato, served with basmati rice.',
      ingredients: [
        { name: 'potatoes', quantity: 250, unit: 'g', slug: 'potato-raw' },
        { name: 'cauliflower', quantity: 200, unit: 'g', slug: 'cauliflower-raw' },
        { name: 'frozen peas', quantity: 60, unit: 'g', slug: 'green-peas-frozen' },
        { name: 'canned tomatoes', quantity: 100, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 3, unit: 'clove', slug: 'garlic-raw' },
        { name: 'fresh ginger', quantity: 10, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'ground coriander', quantity: 1, unit: 'tsp', slug: 'coriander-seed' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'sunflower oil', quantity: 2, unit: 'tsp', slug: 'sunflower-oil' },
        { name: 'basmati rice', quantity: 45, unit: 'g', slug: 'rice-basmati-dry' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Cook the basmati rice in boiling water for 10–12 minutes and drain.',
        'Fry the chopped onion in the oil for 5 minutes, then add the garlic, ginger and spices for 1 minute.',
        'Add the diced potato, cauliflower florets, tomatoes and 100 ml water. Cover and cook 20 minutes, stirring occasionally.',
        'Stir in the peas for the last 3 minutes, season with salt and serve with the rice.',
      ],
      nutritionInfo: { calories: 650, protein: 17, carbs: 120, fat: 12, fiber: 17 },
      cuisineType: 'Indian',
      dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'high-fiber'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-209',
      name: 'Chickpea Shakshuka',
      description:
        'Eggs poached in a spiced tomato and pepper sauce with chickpeas, straight from the pan.',
      ingredients: [
        { name: 'eggs', quantity: 3, unit: 'large', slug: 'egg-whole-raw' },
        { name: 'canned tomatoes', quantity: 300, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'chickpeas, canned', quantity: 100, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'red pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'ground cumin', quantity: 1, unit: 'tsp', slug: 'cumin' },
        { name: 'paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'cayenne pepper', quantity: 0.25, unit: 'tsp', slug: 'cayenne-pepper' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'fresh parsley', quantity: 5, unit: 'g', slug: 'parsley-fresh' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Soften the sliced onion and pepper in the oil for 6 minutes, then add the garlic and spices for 1 minute.',
        'Add the tomatoes and chickpeas and simmer 10 minutes until thick.',
        'Make three wells in the sauce and crack in the eggs. Cover and cook 6–8 minutes until the whites are set.',
        'Scatter with parsley and serve from the pan.',
      ],
      nutritionInfo: { calories: 640, protein: 33, carbs: 52, fat: 31, fiber: 14 },
      cuisineType: 'Middle Eastern',
      dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-v-210',
      name: 'Greek Spinach Rice with Feta',
      description:
        'Spanakorizo: rice cooked down with spinach, spring onions, dill and lemon, finished with crumbled feta and chickpeas.',
      ingredients: [
        { name: 'white rice', quantity: 60, unit: 'g', slug: 'rice-white-dry' },
        { name: 'baby spinach', quantity: 200, unit: 'g', slug: 'spinach-raw' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'spring onions', quantity: 2, unit: 'medium', slug: 'spring-onion-raw' },
        { name: 'chickpeas, canned', quantity: 80, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'feta cheese', quantity: 50, unit: 'g', slug: 'feta' },
        { name: 'fresh dill', quantity: 5, unit: 'g', slug: 'dill-fresh' },
        { name: 'lemon juice', quantity: 2, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'tomato paste', quantity: 1, unit: 'tsp', slug: 'tomato-paste' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'water', quantity: 250, unit: 'ml', slug: 'water' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Soften the chopped onion and spring onions in the oil for 5 minutes.',
        'Stir in the rice and tomato paste, then add the water and bring to a simmer. Cover and cook 12 minutes.',
        'Fold in the spinach and chickpeas and cook 5 more minutes until the spinach has wilted and the rice is tender.',
        'Stir through the lemon juice and dill, season, and crumble the feta over the top.',
      ],
      nutritionInfo: { calories: 650, protein: 24, carbs: 84, fat: 24, fiber: 12 },
      cuisineType: 'Greek',
      dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 25,
      servings: 1,
    },
    {
      id: 'cur-v-211',
      name: 'Coconut Prawn Curry with Rice',
      description:
        'Juicy prawns in a ginger, chilli and turmeric coconut sauce with courgette and red pepper, spooned over rice.',
      ingredients: [
        { name: 'cooked king prawns', quantity: 120, unit: 'g', slug: 'shrimp-cooked' },
        { name: 'coconut milk', quantity: 100, unit: 'ml', slug: 'coconut-milk-canned' },
        { name: 'red pepper', quantity: 1, unit: 'medium', slug: 'bell-pepper-red-raw' },
        { name: 'courgette', quantity: 100, unit: 'g', slug: 'zucchini-raw' },
        { name: 'fresh ginger', quantity: 8, unit: 'g', slug: 'ginger-root-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'red chilli', quantity: 0.5, unit: 'piece', slug: 'chili-pepper-red-raw' },
        { name: 'turmeric', quantity: 0.5, unit: 'tsp', slug: 'turmeric' },
        { name: 'ground coriander', quantity: 0.5, unit: 'tsp', slug: 'coriander-seed' },
        { name: 'lime juice', quantity: 1, unit: 'tbsp', slug: 'lime-juice' },
        { name: 'sunflower oil', quantity: 1, unit: 'tsp', slug: 'sunflower-oil' },
        { name: 'white rice', quantity: 60, unit: 'g', slug: 'rice-white-dry' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Cook the rice in boiling water for 12 minutes and drain.',
        'Fry the garlic, ginger, chilli, turmeric and coriander in the oil for 1 minute.',
        'Add the coconut milk, 80 ml water, sliced pepper and courgette and simmer 8 minutes.',
        'Add the prawns for the last 2 minutes just to heat through, then season with lime juice and salt.',
        'Serve over the rice.',
      ],
      nutritionInfo: { calories: 640, protein: 34, carbs: 72, fat: 24, fiber: 5 },
      cuisineType: 'Thai',
      dietaryTags: ['pescatarian', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 20,
      servings: 1,
    },
    {
      id: 'cur-v-212',
      name: 'Spanish Cod with Chickpeas and Tomatoes',
      description:
        'Tender cod fillet baked over smoky paprika chickpeas, tomatoes and spinach, with a squeeze of lemon.',
      ingredients: [
        { name: 'cod fillet', quantity: 200, unit: 'g', slug: 'cod-raw' },
        { name: 'chickpeas, canned', quantity: 120, unit: 'g', slug: 'chickpeas-canned-drained' },
        { name: 'canned tomatoes', quantity: 200, unit: 'g', slug: 'tomatoes-canned' },
        { name: 'onion', quantity: 1, unit: 'medium', slug: 'onion-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'smoked paprika', quantity: 1, unit: 'tsp', slug: 'paprika' },
        { name: 'baby spinach', quantity: 60, unit: 'g', slug: 'spinach-raw' },
        { name: 'olive oil', quantity: 1, unit: 'tbsp', slug: 'olive-oil' },
        { name: 'lemon juice', quantity: 1, unit: 'tbsp', slug: 'lemon-juice' },
        { name: 'fresh parsley', quantity: 5, unit: 'g', slug: 'parsley-fresh' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Heat the oven to 200°C.',
        'Soften the sliced onion in the oil for 5 minutes, then add the garlic and paprika for 1 minute.',
        'Add the tomatoes and chickpeas and simmer 8 minutes, then fold in the spinach until wilted.',
        'Transfer to a baking dish, nestle the seasoned cod into the sauce and bake 12–15 minutes until it flakes.',
        'Finish with lemon juice and parsley.',
      ],
      nutritionInfo: { calories: 560, protein: 44, carbs: 40, fat: 22, fiber: 11 },
      cuisineType: 'Spanish',
      dietaryTags: ['pescatarian', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
    {
      id: 'cur-v-213',
      name: 'Sheet-Pan Salmon with Potatoes and Green Beans',
      description:
        'Lemon and garlic salmon roasted on one tray with crisp potatoes and green beans: minimal washing up.',
      ingredients: [
        { name: 'salmon fillet', quantity: 150, unit: 'g', slug: 'salmon-farmed-raw' },
        { name: 'potatoes', quantity: 250, unit: 'g', slug: 'potato-raw' },
        { name: 'green beans', quantity: 150, unit: 'g', slug: 'green-beans-raw' },
        { name: 'lemon', quantity: 0.5, unit: 'piece', slug: 'lemon-raw' },
        { name: 'garlic', quantity: 2, unit: 'clove', slug: 'garlic-raw' },
        { name: 'dried oregano', quantity: 1, unit: 'tsp', slug: 'oregano-dried' },
        { name: 'olive oil', quantity: 2, unit: 'tsp', slug: 'olive-oil' },
        { name: 'Black pepper', quantity: 1, unit: 'to taste', slug: 'black-pepper' },
        { name: 'Salt', quantity: 1, unit: 'to taste', slug: 'salt' },
      ],
      instructions: [
        'Heat the oven to 220°C. Cut the potatoes into small chunks, toss with half the oil, oregano and salt and roast 15 minutes.',
        'Add the green beans and crushed garlic to the tray, then place the salmon on top and drizzle with the remaining oil.',
        'Season the salmon, squeeze over half the lemon and roast 12–15 minutes until it flakes.',
        'Serve with lemon wedges.',
      ],
      nutritionInfo: { calories: 640, protein: 40, carbs: 55, fat: 28, fiber: 9 },
      cuisineType: 'Mediterranean',
      dietaryTags: ['pescatarian', 'gluten-free', 'dairy-free', 'high-protein'],
      prepTimeMins: 10,
      cookTimeMins: 30,
      servings: 1,
    },
  ] as R[]
).map(withImage);
